/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module geo_evidence_engine(clk, reset_n, append_req, uow_id, pre_state_hash, post_state_hash, candidate_hash, cert_id, causal_seq, append_ack, engine_busy, record_count, physical_evidence_root_256, semantic_evidence_root_256, semantic_evidence_test_64, current_evidence_root, latest_record);
  wire _00_;
  wire _01_;
  wire _02_;
  wire [31:0] _03_;
  wire [63:0] _04_;
  wire _05_;
  wire _06_;
  wire [37:0] _07_;
  wire [31:0] _08_;
  wire [30:0] _09_;
  wire [36:0] _10_;
  wire [31:0] _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire [63:0] _15_;
  wire [63:0] _16_;
  wire [63:0] _17_;
  wire [63:0] _18_;
  wire [63:0] _19_;
  wire [31:0] _20_;
  wire _21_;
  wire _22_;
  wire [63:0] _23_;
  wire [63:0] _24_;
  wire [63:0] _25_;
  wire [63:0] _26_;
  wire [63:0] _27_;
  wire [63:0] _28_;
  wire [63:0] _29_;
  wire [63:0] _30_;
  wire [63:0] _31_;
  wire [63:0] _32_;
  wire [63:0] _33_;
  wire [63:0] _34_;
  output append_ack;
  reg append_ack;
  input append_req;
  wire append_req;
  input [63:0] candidate_hash;
  wire [63:0] candidate_hash;
  input [31:0] causal_seq;
  wire [31:0] causal_seq;
  input [31:0] cert_id;
  wire [31:0] cert_id;
  input clk;
  wire clk;
  wire [63:0] \compress_step$func$fabric_p0/rtl/evidence/geo_evidence_engine.sv:194$189.cand_h ;
  wire [31:0] \compress_step$func$fabric_p0/rtl/evidence/geo_evidence_engine.sv:194$189.cert ;
  wire [31:0] \compress_step$func$fabric_p0/rtl/evidence/geo_evidence_engine.sv:194$189.id ;
  wire [63:0] \compress_step$func$fabric_p0/rtl/evidence/geo_evidence_engine.sv:194$189.post_h ;
  wire [63:0] \compress_step$func$fabric_p0/rtl/evidence/geo_evidence_engine.sv:194$189.pre_h ;
  wire [63:0] \compress_step$func$fabric_p0/rtl/evidence/geo_evidence_engine.sv:194$189.prev_r ;
  wire [31:0] \compress_step$func$fabric_p0/rtl/evidence/geo_evidence_engine.sv:194$189.seq ;
  wire [63:0] \compress_step$func$fabric_p0/rtl/evidence/geo_evidence_engine.sv:194$189.state ;
  wire [63:0] \compress_step$func$fabric_p0/rtl/evidence/geo_evidence_engine.sv:194$189.w0 ;
  wire [63:0] \compress_step$func$fabric_p0/rtl/evidence/geo_evidence_engine.sv:194$189.w1 ;
  wire [63:0] \compress_step$func$fabric_p0/rtl/evidence/geo_evidence_engine.sv:194$189.w2 ;
  wire [63:0] \compress_step$func$fabric_p0/rtl/evidence/geo_evidence_engine.sv:194$189.w3 ;
  wire [63:0] \compute_fp$func$fabric_p0/rtl/evidence/geo_evidence_engine.sv:218$190.cand_h ;
  wire [31:0] \compute_fp$func$fabric_p0/rtl/evidence/geo_evidence_engine.sv:218$190.cert ;
  wire [31:0] \compute_fp$func$fabric_p0/rtl/evidence/geo_evidence_engine.sv:218$190.id ;
  wire [63:0] \compute_fp$func$fabric_p0/rtl/evidence/geo_evidence_engine.sv:218$190.post_h ;
  wire [63:0] \compute_fp$func$fabric_p0/rtl/evidence/geo_evidence_engine.sv:218$190.pre_h ;
  wire [31:0] \compute_fp$func$fabric_p0/rtl/evidence/geo_evidence_engine.sv:218$190.seq ;
  output [63:0] current_evidence_root;
  wire [63:0] current_evidence_root;
  output engine_busy;
  wire engine_busy;
  output [415:0] latest_record;
  reg [415:0] latest_record;
  reg [255:0] phys_root_q;
  output [255:0] physical_evidence_root_256;
  wire [255:0] physical_evidence_root_256;
  input [63:0] post_state_hash;
  wire [63:0] post_state_hash;
  input [63:0] pre_state_hash;
  wire [63:0] pre_state_hash;
  output [31:0] record_count;
  reg [31:0] record_count;
  input reset_n;
  wire reset_n;
  reg [63:0] root_reg;
  reg [255:0] sem_root_q;
  reg [63:0] sem_test_q;
  output [255:0] semantic_evidence_root_256;
  wire [255:0] semantic_evidence_root_256;
  output [63:0] semantic_evidence_test_64;
  wire [63:0] semantic_evidence_test_64;
  wire [511:0] serialized_block_w;
  wire sha_phys_busy;
  wire [255:0] sha_phys_digest;
  wire sha_phys_done;
  reg sha_phys_init;
  reg sha_phys_start;
  reg [255:0] sha_phys_state_in;
  wire [511:0] sha_sem_block_in;
  wire sha_sem_busy;
  wire [255:0] sha_sem_digest;
  wire sha_sem_done;
  reg sha_sem_init;
  reg sha_sem_start;
  wire [255:0] sha_sem_state_in;
  input [31:0] uow_id;
  wire [31:0] uow_id;
  assign _03_ = record_count + 1'h1;
  assign _04_ = _30_ + root_reg;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) record_count <= 32'd0;
    else if (append_req) record_count <= _03_;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) latest_record[95:32] <= 64'h0000000000000000;
    else if (append_req) latest_record[95:32] <= _04_;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) latest_record[31:0] <= 32'd0;
    else if (append_req) latest_record[31:0] <= causal_seq;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) latest_record[159:96] <= 64'h0000000000000000;
    else if (append_req) latest_record[159:96] <= root_reg;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) latest_record[191:160] <= 32'd0;
    else if (append_req) latest_record[191:160] <= cert_id;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) latest_record[255:192] <= 64'h0000000000000000;
    else if (append_req) latest_record[255:192] <= candidate_hash;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) latest_record[319:256] <= 64'h0000000000000000;
    else if (append_req) latest_record[319:256] <= post_state_hash;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) latest_record[383:320] <= 64'h0000000000000000;
    else if (append_req) latest_record[383:320] <= pre_state_hash;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) latest_record[415:384] <= 32'd0;
    else if (append_req) latest_record[415:384] <= uow_id;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) sha_phys_init <= 1'h0;
    else if (_05_) sha_phys_init <= _14_;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) sha_phys_state_in <= 256'h6a09e667bb67ae853c6ef372a54ff53a510e527f9b05688c1f83d9ab5be0cd19;
    else if (_05_) sha_phys_state_in <= phys_root_q;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) sha_sem_init <= 1'h0;
    else if (_06_) sha_sem_init <= 1'h1;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) root_reg <= 64'h6a09e667bb67ae85;
    else if (append_req) root_reg <= _04_;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) phys_root_q <= 256'h6a09e667bb67ae853c6ef372a54ff53a510e527f9b05688c1f83d9ab5be0cd19;
    else if (sha_phys_done) phys_root_q <= sha_phys_digest;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) sem_root_q <= 256'h6a09e667bb67ae853c6ef372a54ff53a510e527f9b05688c1f83d9ab5be0cd19;
    else if (sha_sem_done) sem_root_q <= sha_sem_digest;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) sem_test_q <= 64'h0000000000000000;
    else if (append_req) sem_test_q <= _23_;
  reg [306:0] _53_;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) _53_ <= 307'h00000000000000000000000000000000000000000000000000000000000000000000000000000;
    else if (_06_) _53_ <= { uow_id, cert_id, causal_seq, 16'hffff, pre_state_hash, post_state_hash, candidate_hash, 3'h7 };
  assign { sha_sem_block_in[511:415], sha_sem_block_in[413], sha_sem_block_in[410], sha_sem_block_in[408:407], sha_sem_block_in[405], sha_sem_block_in[402], sha_sem_block_in[400], sha_sem_block_in[398], sha_sem_block_in[396:395], sha_sem_block_in[393], sha_sem_block_in[390], sha_sem_block_in[388:387], sha_sem_block_in[385], sha_sem_block_in[383:191], sha_sem_block_in[8], sha_sem_block_in[5] } = _53_;
  assign _12_ = ~ sha_phys_busy;
  assign _13_ = ~ sha_sem_busy;
  assign _05_ = & { _12_, append_req };
  assign _06_ = & { _13_, append_req };
  assign _07_ = ~ { uow_id[31], uow_id[29], uow_id[26], uow_id[24], uow_id[22], uow_id[19:12], uow_id[10], uow_id[8], uow_id[5:3], uow_id[1], cert_id[30], cert_id[28:24], cert_id[20:18], cert_id[16], cert_id[13:12], cert_id[10:9], cert_id[7:4], cert_id[0] };
  assign _08_ = ~ { pre_state_hash[62], pre_state_hash[60], pre_state_hash[56], pre_state_hash[51:49], pre_state_hash[46], pre_state_hash[44], pre_state_hash[41], pre_state_hash[38:31], pre_state_hash[29], pre_state_hash[27:26], pre_state_hash[24:21], pre_state_hash[18:17], pre_state_hash[15], pre_state_hash[9], pre_state_hash[7:6], pre_state_hash[4], pre_state_hash[0] };
  assign _09_ = ~ { post_state_hash[63], post_state_hash[60:59], post_state_hash[57:56], post_state_hash[50], post_state_hash[48], post_state_hash[46:45], post_state_hash[43], post_state_hash[39], post_state_hash[35:34], post_state_hash[29], post_state_hash[27], post_state_hash[25:24], post_state_hash[21:17], post_state_hash[14:13], post_state_hash[11:10], post_state_hash[4:0] };
  assign _10_ = ~ { root_reg[63], root_reg[61:56], root_reg[54], root_reg[52:51], root_reg[48], root_reg[46:38], root_reg[34:31], root_reg[29:28], root_reg[18], root_reg[16:13], root_reg[10], root_reg[7:6], root_reg[4], root_reg[2], root_reg[0] };
  assign _11_ = ~ { _34_[63], _34_[61], _34_[58], _34_[56:55], _34_[53], _34_[50], _34_[48], _34_[46], _34_[44:43], _34_[41], _34_[38], _34_[36:35], _34_[33], _34_[31], _34_[29], _34_[26], _34_[24:23], _34_[21], _34_[18], _34_[16], _34_[14], _34_[12:11], _34_[9], _34_[6], _34_[4:3], _34_[1] };
  assign _14_ = ! record_count;
  assign engine_busy = sha_phys_busy || sha_sem_busy;
  assign _15_ = _25_ * 64'hbf58476d1ce4e5b9;
  assign _16_ = _26_ * 64'h94d049bb133111eb;
  assign _17_ = _27_ * 64'hc4ceb9fe1a85ec53;
  assign _18_ = _28_ * 64'hff51afd7ed558ccd;
  assign _19_ = _29_ * 64'hc4ceb9fe1a85ec53;
  assign _20_ = ~ causal_seq;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) append_ack <= 1'h0;
    else append_ack <= _00_;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) sha_phys_start <= 1'h0;
    else sha_phys_start <= _01_;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) sha_sem_start <= 1'h0;
    else sha_sem_start <= _02_;
  assign _00_ = append_req ? 1'h1 : 1'h0;
  assign _21_ = sha_sem_busy ? 1'h0 : 1'h1;
  assign _02_ = append_req ? _21_ : 1'h0;
  assign _22_ = sha_phys_busy ? 1'h0 : 1'h1;
  assign _01_ = append_req ? _22_ : 1'h0;
  assign _23_ = sem_test_q ^ { _11_[31], _34_[62], _11_[30], _34_[60:59], _11_[29], _34_[57], _11_[28:27], _34_[54], _11_[26], _34_[52:51], _11_[25], _34_[49], _11_[24], _34_[47], _11_[23], _34_[45], _11_[22:21], _34_[42], _11_[20], _34_[40:39], _11_[19], _34_[37], _11_[18:17], _34_[34], _11_[16], _34_[32], _11_[15], _34_[30], _11_[14], _34_[28:27], _11_[13], _34_[25], _11_[12:11], _34_[22], _11_[10], _34_[20:19], _11_[9], _34_[17], _11_[8], _34_[15], _11_[7], _34_[13], _11_[6:5], _34_[10], _11_[4], _34_[8:7], _11_[3], _34_[5], _11_[2:1], _34_[2], _11_[0], _34_[0] };
  assign _24_ = candidate_hash ^ { causal_seq, _20_ };
  assign _25_ = { _10_[36], root_reg[62], _10_[35:30], root_reg[55], _10_[29], root_reg[53], _10_[28:27], root_reg[50:49], _10_[26], root_reg[47], _10_[25:17], root_reg[37:35], _10_[16:13], root_reg[30], _10_[12:11], root_reg[27:19], _10_[10], root_reg[17], _10_[9:6], root_reg[12:11], _10_[5], root_reg[9:8], _10_[4:3], root_reg[5], _10_[2], root_reg[3], _10_[1], root_reg[1], _10_[0] } ^ { 30'h00000000, _10_[36], root_reg[62], _10_[35:30], root_reg[55], _10_[29], root_reg[53], _10_[28:27], root_reg[50:49], _10_[26], root_reg[47], _10_[25:17], root_reg[37:35], _10_[16:13], root_reg[30] };
  assign _26_ = _15_ ^ { _07_[37], uow_id[30], _07_[36], uow_id[28:27], _07_[35], uow_id[25], _07_[34], uow_id[23], _07_[33], uow_id[21:20], _07_[32:25], uow_id[11], _07_[24], uow_id[9], _07_[23], uow_id[7:6], _07_[22:20], uow_id[2], _07_[19], uow_id[0], cert_id[31], _07_[18], cert_id[29], _07_[17:13], cert_id[23:21], _07_[12:10], cert_id[17], _07_[9], cert_id[15:14], _07_[8:7], cert_id[11], _07_[6:5], cert_id[8], _07_[4:1], cert_id[3:1], _07_[0] };
  assign _27_ = _16_ ^ { pre_state_hash[63], _08_[31], pre_state_hash[61], _08_[30], pre_state_hash[59:57], _08_[29], pre_state_hash[55:52], _08_[28:26], pre_state_hash[48:47], _08_[25], pre_state_hash[45], _08_[24], pre_state_hash[43:42], _08_[23], pre_state_hash[40:39], _08_[22:15], pre_state_hash[30], _08_[14], pre_state_hash[28], _08_[13:12], pre_state_hash[25], _08_[11:8], pre_state_hash[20:19], _08_[7:6], pre_state_hash[16], _08_[5], pre_state_hash[14:10], _08_[4], pre_state_hash[8], _08_[3:2], pre_state_hash[5], _08_[1], pre_state_hash[3:1], _08_[0] };
  assign _28_ = _17_ ^ { 27'h0000000, _17_[63:27] };
  assign _29_ = _18_ ^ { _09_[30], post_state_hash[62:61], _09_[29:28], post_state_hash[58], _09_[27:26], post_state_hash[55:51], _09_[25], post_state_hash[49], _09_[24], post_state_hash[47], _09_[23:22], post_state_hash[44], _09_[21], post_state_hash[42:40], _09_[20], post_state_hash[38:36], _09_[19:18], post_state_hash[33:30], _09_[17], post_state_hash[28], _09_[16], post_state_hash[26], _09_[15:14], post_state_hash[23:22], _09_[13:9], post_state_hash[16:15], _09_[8:7], post_state_hash[12], _09_[6:5], post_state_hash[9:5], _09_[4:0] };
  assign _30_ = _19_ ^ _24_;
  assign _31_ = { uow_id, cert_id } ^ pre_state_hash;
  assign _32_ = _31_ ^ post_state_hash;
  assign _33_ = _32_ ^ candidate_hash;
  assign _34_ = _33_ ^ { causal_seq, _20_ };
  geo_sha256_core u_sha256_phys (
    .block_in({ uow_id, cert_id, causal_seq, 32'ha5a55a5a, pre_state_hash, post_state_hash, candidate_hash, 192'h800000000000000000000000000000000000000000000120 }),
    .busy(sha_phys_busy),
    .clk(clk),
    .digest_out(sha_phys_digest),
    .done(sha_phys_done),
    .init_state(sha_phys_init),
    .rst_n(reset_n),
    .start(sha_phys_start),
    .state_in(sha_phys_state_in)
  );
  geo_sha256_core u_sha256_sem (
    .block_in({ sha_sem_block_in[511:415], 1'h0, sha_sem_block_in[413], 2'h0, sha_sem_block_in[410], 1'h0, sha_sem_block_in[408:407], 1'h0, sha_sem_block_in[405], 2'h0, sha_sem_block_in[402], 1'h0, sha_sem_block_in[400], 1'h0, sha_sem_block_in[398], 1'h0, sha_sem_block_in[396:395], 1'h0, sha_sem_block_in[393], 2'h0, sha_sem_block_in[390], 1'h0, sha_sem_block_in[388:387], 1'h0, sha_sem_block_in[385], 1'h0, sha_sem_block_in[383:191], 182'h0000000000000000000000000000000000000000000000, sha_sem_block_in[8], 2'h0, sha_sem_block_in[5], 5'h00 }),
    .busy(sha_sem_busy),
    .clk(clk),
    .digest_out(sha_sem_digest),
    .done(sha_sem_done),
    .init_state(sha_sem_init),
    .rst_n(reset_n),
    .start(sha_sem_start),
    .state_in(256'h6a09e667bb67ae853c6ef372a54ff53a510e527f9b05688c1f83d9ab5be0cd19)
  );
  assign \compress_step$func$fabric_p0/rtl/evidence/geo_evidence_engine.sv:194$189.cand_h  = 64'hxxxxxxxxxxxxxxxx;
  assign \compress_step$func$fabric_p0/rtl/evidence/geo_evidence_engine.sv:194$189.cert  = 32'hxxxxxxxx;
  assign \compress_step$func$fabric_p0/rtl/evidence/geo_evidence_engine.sv:194$189.id  = 32'hxxxxxxxx;
  assign \compress_step$func$fabric_p0/rtl/evidence/geo_evidence_engine.sv:194$189.post_h  = 64'hxxxxxxxxxxxxxxxx;
  assign \compress_step$func$fabric_p0/rtl/evidence/geo_evidence_engine.sv:194$189.pre_h  = 64'hxxxxxxxxxxxxxxxx;
  assign \compress_step$func$fabric_p0/rtl/evidence/geo_evidence_engine.sv:194$189.prev_r  = 64'hxxxxxxxxxxxxxxxx;
  assign \compress_step$func$fabric_p0/rtl/evidence/geo_evidence_engine.sv:194$189.seq  = 32'hxxxxxxxx;
  assign \compress_step$func$fabric_p0/rtl/evidence/geo_evidence_engine.sv:194$189.state  = 64'hxxxxxxxxxxxxxxxx;
  assign \compress_step$func$fabric_p0/rtl/evidence/geo_evidence_engine.sv:194$189.w0  = 64'hxxxxxxxxxxxxxxxx;
  assign \compress_step$func$fabric_p0/rtl/evidence/geo_evidence_engine.sv:194$189.w1  = 64'hxxxxxxxxxxxxxxxx;
  assign \compress_step$func$fabric_p0/rtl/evidence/geo_evidence_engine.sv:194$189.w2  = 64'hxxxxxxxxxxxxxxxx;
  assign \compress_step$func$fabric_p0/rtl/evidence/geo_evidence_engine.sv:194$189.w3  = 64'hxxxxxxxxxxxxxxxx;
  assign \compute_fp$func$fabric_p0/rtl/evidence/geo_evidence_engine.sv:218$190.cand_h  = 64'hxxxxxxxxxxxxxxxx;
  assign \compute_fp$func$fabric_p0/rtl/evidence/geo_evidence_engine.sv:218$190.cert  = 32'hxxxxxxxx;
  assign \compute_fp$func$fabric_p0/rtl/evidence/geo_evidence_engine.sv:218$190.id  = 32'hxxxxxxxx;
  assign \compute_fp$func$fabric_p0/rtl/evidence/geo_evidence_engine.sv:218$190.post_h  = 64'hxxxxxxxxxxxxxxxx;
  assign \compute_fp$func$fabric_p0/rtl/evidence/geo_evidence_engine.sv:218$190.pre_h  = 64'hxxxxxxxxxxxxxxxx;
  assign \compute_fp$func$fabric_p0/rtl/evidence/geo_evidence_engine.sv:218$190.seq  = 32'hxxxxxxxx;
  assign current_evidence_root = root_reg;
  assign physical_evidence_root_256 = phys_root_q;
  assign semantic_evidence_root_256 = sem_root_q;
  assign semantic_evidence_test_64 = sem_test_q;
  assign serialized_block_w = { uow_id, cert_id, causal_seq, 32'ha5a55a5a, pre_state_hash, post_state_hash, candidate_hash, 192'h800000000000000000000000000000000000000000000120 };
  assign { sha_sem_block_in[414], sha_sem_block_in[412:411], sha_sem_block_in[409], sha_sem_block_in[406], sha_sem_block_in[404:403], sha_sem_block_in[401], sha_sem_block_in[399], sha_sem_block_in[397], sha_sem_block_in[394], sha_sem_block_in[392:391], sha_sem_block_in[389], sha_sem_block_in[386], sha_sem_block_in[384], sha_sem_block_in[190:9], sha_sem_block_in[7:6], sha_sem_block_in[4:0] } = 205'h0000000000000000000000000000000000000000000000000000;
  assign sha_sem_state_in = 256'h6a09e667bb67ae853c6ef372a54ff53a510e527f9b05688c1f83d9ab5be0cd19;
endmodule

module geo_sha256_core(clk, rst_n, start, init_state, state_in, block_in, busy, done, digest_out);
  wire [31:0] _000_;
  wire [31:0] _001_;
  wire [31:0] _002_;
  wire [31:0] _003_;
  wire [31:0] _004_;
  wire [31:0] _005_;
  wire [31:0] _006_;
  wire [31:0] _007_;
  wire [31:0] _008_;
  wire [31:0] _009_;
  wire [31:0] _010_;
  wire [31:0] _011_;
  wire [31:0] _012_;
  wire [31:0] _013_;
  wire [31:0] _014_;
  wire _015_;
  wire [31:0] _016_;
  wire [31:0] _017_;
  wire [31:0] _018_;
  wire [31:0] _019_;
  wire [31:0] _020_;
  wire [31:0] _021_;
  wire [31:0] _022_;
  wire [31:0] _023_;
  wire [31:0] _024_;
  wire [31:0] _025_;
  wire [31:0] _026_;
  wire [31:0] _027_;
  wire [5:0] _028_;
  wire [1:0] _029_;
  wire [31:0] _030_;
  wire [31:0] _031_;
  wire [31:0] _032_;
  wire [31:0] _033_;
  wire [31:0] _034_;
  wire [31:0] _035_;
  wire [31:0] _036_;
  wire [31:0] _037_;
  wire [31:0] _038_;
  wire [31:0] _039_;
  wire [31:0] _040_;
  wire [31:0] _041_;
  wire [31:0] _042_;
  wire [5:0] _043_;
  wire [31:0] _044_;
  wire [31:0] _045_;
  wire [31:0] _046_;
  wire [31:0] _047_;
  wire [31:0] _048_;
  wire [31:0] _049_;
  wire [31:0] _050_;
  wire [31:0] _051_;
  wire [31:0] _052_;
  wire [31:0] _053_;
  wire [31:0] _054_;
  wire [31:0] _055_;
  wire [31:0] _056_;
  wire [31:0] _057_;
  wire [31:0] _058_;
  wire [31:0] _059_;
  wire [31:0] _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire [31:0] _089_;
  wire [31:0] _090_;
  wire [31:0] _091_;
  wire [31:0] _092_;
  wire [31:0] _093_;
  wire [31:0] _094_;
  wire [31:0] _095_;
  wire [31:0] _096_;
  wire [31:0] _097_;
  wire [31:0] _098_;
  wire [31:0] _099_;
  wire [31:0] _100_;
  wire [31:0] _101_;
  wire [31:0] _102_;
  wire [31:0] _103_;
  wire [31:0] _104_;
  wire [31:0] _105_;
  wire [31:0] _106_;
  wire [31:0] _107_;
  wire [31:0] _108_;
  wire [31:0] _109_;
  wire [31:0] _110_;
  wire [31:0] _111_;
  wire [31:0] _112_;
  wire [31:0] _113_;
  wire [31:0] _114_;
  wire [31:0] _115_;
  wire [31:0] _116_;
  wire [31:0] _117_;
  wire [31:0] _118_;
  wire [31:0] _119_;
  wire [31:0] _120_;
  wire [31:0] _121_;
  wire [31:0] _122_;
  wire [31:0] _123_;
  wire [31:0] _124_;
  wire [31:0] _125_;
  wire [31:0] _126_;
  wire [31:0] _127_;
  wire [31:0] _128_;
  wire [31:0] _129_;
  wire [31:0] _130_;
  wire [31:0] _131_;
  wire [31:0] _132_;
  wire [31:0] _133_;
  wire [31:0] _134_;
  wire [31:0] _135_;
  wire [31:0] _136_;
  wire [31:0] _137_;
  wire [31:0] _138_;
  wire [31:0] _139_;
  wire [31:0] _140_;
  wire [31:0] _141_;
  wire [31:0] _142_;
  wire [31:0] _143_;
  wire [31:0] _144_;
  wire [31:0] _145_;
  wire [31:0] _146_;
  wire [31:0] _147_;
  wire [31:0] _148_;
  wire [31:0] _149_;
  wire [31:0] _150_;
  wire [31:0] _151_;
  wire [31:0] _152_;
  wire [31:0] _153_;
  wire [31:0] _154_;
  wire [31:0] _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire [31:0] _174_;
  wire [31:0] _175_;
  wire _176_;
  wire [31:0] _177_;
  wire [31:0] _178_;
  wire [31:0] _179_;
  wire [31:0] _180_;
  wire [31:0] _181_;
  wire [31:0] _182_;
  wire [31:0] _183_;
  wire [31:0] _184_;
  wire [31:0] _185_;
  wire [31:0] _186_;
  wire [31:0] _187_;
  wire [31:0] _188_;
  wire [31:0] _189_;
  wire [31:0] _190_;
  wire [5:0] _191_;
  wire [5:0] _192_;
  wire [1:0] _193_;
  wire [1:0] _194_;
  wire [31:0] _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire [31:0] _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire [31:0] _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire [31:0] _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire [31:0] _263_;
  wire [31:0] _264_;
  wire [31:0] _265_;
  wire [31:0] _266_;
  wire [31:0] _267_;
  wire [31:0] _268_;
  wire [31:0] _269_;
  wire [31:0] _270_;
  wire [31:0] _271_;
  wire [31:0] _272_;
  wire [31:0] _273_;
  wire [31:0] _274_;
  wire [31:0] _275_;
  reg [31:0] H0_q;
  reg [31:0] H1_q;
  reg [31:0] H2_q;
  reg [31:0] H3_q;
  reg [31:0] H4_q;
  reg [31:0] H5_q;
  reg [31:0] H6_q;
  reg [31:0] H7_q;
  reg [31:0] a_q;
  reg [31:0] b_q;
  input [511:0] block_in;
  wire [511:0] block_in;
  output busy;
  wire busy;
  reg [31:0] c_q;
  wire [31:0] \cap_sigma0$func$fabric_p0/rtl/evidence/geo_sha256_core.sv:142$13.x ;
  wire [31:0] \cap_sigma1$func$fabric_p0/rtl/evidence/geo_sha256_core.sv:141$7.x ;
  wire [31:0] \ch$func$fabric_p0/rtl/evidence/geo_sha256_core.sv:141$8.x ;
  wire [31:0] \ch$func$fabric_p0/rtl/evidence/geo_sha256_core.sv:141$8.y ;
  wire [31:0] \ch$func$fabric_p0/rtl/evidence/geo_sha256_core.sv:141$8.z ;
  input clk;
  wire clk;
  wire [31:0] current_w;
  reg [31:0] d_q;
  output [255:0] digest_out;
  wire [255:0] digest_out;
  output done;
  reg done;
  reg [31:0] e_q;
  reg [31:0] f_q;
  reg [31:0] g_q;
  wire [5:0] \get_k$func$fabric_p0/rtl/evidence/geo_sha256_core.sv:141$9.round_idx ;
  reg [31:0] h_q;
  input init_state;
  wire init_state;
  wire [31:0] \maj$func$fabric_p0/rtl/evidence/geo_sha256_core.sv:142$14.x ;
  wire [31:0] \maj$func$fabric_p0/rtl/evidence/geo_sha256_core.sv:142$14.y ;
  wire [31:0] \maj$func$fabric_p0/rtl/evidence/geo_sha256_core.sv:142$14.z ;
  wire [31:0] \rotr$func$fabric_p0/rtl/evidence/geo_sha256_core.sv:81$5.x ;
  wire [31:0] \rotr$func$fabric_p0/rtl/evidence/geo_sha256_core.sv:81$6.x ;
  wire [31:0] \rotr$func$fabric_p0/rtl/evidence/geo_sha256_core.sv:85$3.x ;
  wire [31:0] \rotr$func$fabric_p0/rtl/evidence/geo_sha256_core.sv:85$4.x ;
  wire [31:0] \rotr$func$fabric_p0/rtl/evidence/geo_sha256_core.sv:89$15.x ;
  wire [31:0] \rotr$func$fabric_p0/rtl/evidence/geo_sha256_core.sv:89$16.x ;
  wire [31:0] \rotr$func$fabric_p0/rtl/evidence/geo_sha256_core.sv:89$17.x ;
  wire [31:0] \rotr$func$fabric_p0/rtl/evidence/geo_sha256_core.sv:93$10.x ;
  wire [31:0] \rotr$func$fabric_p0/rtl/evidence/geo_sha256_core.sv:93$11.x ;
  wire [31:0] \rotr$func$fabric_p0/rtl/evidence/geo_sha256_core.sv:93$12.x ;
  reg [5:0] round_q;
  input rst_n;
  wire rst_n;
  wire [31:0] \sigma0$func$fabric_p0/rtl/evidence/geo_sha256_core.sv:133$2.x ;
  wire [31:0] \sigma1$func$fabric_p0/rtl/evidence/geo_sha256_core.sv:131$1.x ;
  input start;
  wire start;
  input [255:0] state_in;
  wire [255:0] state_in;
  reg [1:0] state_q;
  wire [31:0] t1;
  wire [31:0] t2;
  reg [31:0] \w_mem[0] ;
  reg [31:0] \w_mem[10] ;
  reg [31:0] \w_mem[11] ;
  reg [31:0] \w_mem[12] ;
  reg [31:0] \w_mem[13] ;
  reg [31:0] \w_mem[14] ;
  reg [31:0] \w_mem[15] ;
  reg [31:0] \w_mem[1] ;
  reg [31:0] \w_mem[2] ;
  reg [31:0] \w_mem[3] ;
  reg [31:0] \w_mem[4] ;
  reg [31:0] \w_mem[5] ;
  reg [31:0] \w_mem[6] ;
  reg [31:0] \w_mem[7] ;
  reg [31:0] \w_mem[8] ;
  reg [31:0] \w_mem[9] ;
  assign _035_ = _037_ + _271_;
  assign _036_ = _035_ + _033_;
  assign _037_ = _273_ + _031_;
  assign _038_ = h_q + _012_;
  assign _039_ = _038_ + _013_;
  assign _040_ = _039_ + _019_;
  assign t1 = _040_ + current_w;
  assign t2 = _011_ + _021_;
  assign _041_ = d_q + t1;
  assign _042_ = t1 + t2;
  assign _043_ = round_q + 1'h1;
  assign _044_ = H0_q + a_q;
  assign _045_ = H1_q + b_q;
  assign _046_ = H2_q + c_q;
  assign _047_ = H3_q + d_q;
  assign _048_ = H4_q + e_q;
  assign _049_ = H5_q + f_q;
  assign _050_ = H6_q + g_q;
  assign _051_ = H7_q + h_q;
  assign _052_ = a_q & b_q;
  assign _053_ = a_q & c_q;
  assign _054_ = b_q & c_q;
  assign _059_ = e_q & f_q;
  assign _060_ = _151_ & g_q;
  always @(posedge clk)
    if (_067_) \w_mem[15]  <= current_w;
  always @(posedge clk)
    if (_068_) \w_mem[14]  <= current_w;
  always @(posedge clk)
    if (_069_) \w_mem[13]  <= current_w;
  always @(posedge clk)
    if (_070_) \w_mem[12]  <= current_w;
  always @(posedge clk)
    if (_071_) \w_mem[11]  <= current_w;
  always @(posedge clk)
    if (_072_) \w_mem[10]  <= current_w;
  always @(posedge clk)
    if (_073_) \w_mem[9]  <= current_w;
  always @(posedge clk)
    if (_074_) \w_mem[8]  <= current_w;
  always @(posedge clk)
    if (_075_) \w_mem[7]  <= current_w;
  always @(posedge clk)
    if (_076_) \w_mem[6]  <= current_w;
  always @(posedge clk)
    if (_077_) \w_mem[5]  <= current_w;
  always @(posedge clk)
    if (_078_) \w_mem[4]  <= current_w;
  always @(posedge clk)
    if (_079_) \w_mem[3]  <= current_w;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_q <= 2'h0;
    else if (_080_) state_q <= _029_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) round_q <= 6'h00;
    else if (_081_) round_q <= _028_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) a_q <= 32'd0;
    else if (_082_) a_q <= _008_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) b_q <= 32'd0;
    else if (_082_) b_q <= _009_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) c_q <= 32'd0;
    else if (_082_) c_q <= _010_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) d_q <= 32'd0;
    else if (_082_) d_q <= _014_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) e_q <= 32'd0;
    else if (_082_) e_q <= _016_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) f_q <= 32'd0;
    else if (_082_) f_q <= _017_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) g_q <= 32'd0;
    else if (_082_) g_q <= _018_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) h_q <= 32'd0;
    else if (_082_) h_q <= _020_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) H0_q <= 32'd1779033703;
    else if (_083_) H0_q <= _000_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) H1_q <= 32'd3144134277;
    else if (_083_) H1_q <= _001_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) H2_q <= 32'd1013904242;
    else if (_083_) H2_q <= _002_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) H3_q <= 32'd2773480762;
    else if (_083_) H3_q <= _003_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) H4_q <= 32'd1359893119;
    else if (_083_) H4_q <= _004_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) H5_q <= 32'd2600822924;
    else if (_083_) H5_q <= _005_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) H6_q <= 32'd528734635;
    else if (_083_) H6_q <= _006_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) H7_q <= 32'd1541459225;
    else if (_083_) H7_q <= _007_;
  always @(posedge clk)
    if (_084_) \w_mem[0]  <= current_w;
  always @(posedge clk)
    if (_085_) \w_mem[1]  <= current_w;
  always @(posedge clk)
    if (_086_) \w_mem[2]  <= current_w;
  assign _061_ = { _176_, start } != 2'h2;
  assign _062_ = { _156_, _087_ } != 2'h2;
  assign _063_ = | { _176_, _156_, _157_ };
  assign _064_ = { _156_, _087_ } != 2'h3;
  assign _065_ = | { _176_, _156_ };
  assign _066_ = | { _176_, _157_ };
  assign _067_ = & { _158_, _156_, rst_n };
  assign _068_ = & { _159_, _156_, rst_n };
  assign _069_ = & { _160_, _156_, rst_n };
  assign _070_ = & { _161_, _156_, rst_n };
  assign _071_ = & { _162_, _156_, rst_n };
  assign _072_ = & { _163_, _156_, rst_n };
  assign _073_ = & { _164_, _156_, rst_n };
  assign _074_ = & { _165_, _156_, rst_n };
  assign _075_ = & { _166_, _156_, rst_n };
  assign _076_ = & { _167_, _156_, rst_n };
  assign _077_ = & { _168_, _156_, rst_n };
  assign _078_ = & { _169_, _156_, rst_n };
  assign _079_ = & { _170_, _156_, rst_n };
  assign _080_ = & { _063_, _062_, _061_ };
  assign _081_ = & { _065_, _064_, _061_ };
  assign _082_ = & { _065_, _061_ };
  assign _083_ = & { _066_, _061_ };
  assign _084_ = & { _173_, _156_, rst_n };
  assign _085_ = & { _172_, _156_, rst_n };
  assign _086_ = & { _171_, _156_, rst_n };
  assign _087_ = round_q == 6'h3f;
  assign _088_ = round_q < 6'h10;
  assign _019_ = round_q[5] ? _090_ : _089_;
  assign _089_ = round_q[4] ? _092_ : _091_;
  assign _090_ = round_q[4] ? _094_ : _093_;
  assign _091_ = round_q[3] ? _096_ : _095_;
  assign _092_ = round_q[3] ? _098_ : _097_;
  assign _093_ = round_q[3] ? _100_ : _099_;
  assign _094_ = round_q[3] ? _102_ : _101_;
  assign _095_ = round_q[2] ? _104_ : _103_;
  assign _096_ = round_q[2] ? _106_ : _105_;
  assign _097_ = round_q[2] ? _108_ : _107_;
  assign _098_ = round_q[2] ? _110_ : _109_;
  assign _099_ = round_q[2] ? _112_ : _111_;
  assign _100_ = round_q[2] ? _114_ : _113_;
  assign _101_ = round_q[2] ? _116_ : _115_;
  assign _102_ = round_q[2] ? _118_ : _117_;
  assign _103_ = round_q[1] ? _120_ : _119_;
  assign _113_ = round_q[1] ? _122_ : _121_;
  assign _114_ = round_q[1] ? _124_ : _123_;
  assign _115_ = round_q[1] ? _126_ : _125_;
  assign _116_ = round_q[1] ? _128_ : _127_;
  assign _117_ = round_q[1] ? _130_ : _129_;
  assign _118_ = round_q[1] ? _132_ : _131_;
  assign _104_ = round_q[1] ? _134_ : _133_;
  assign _105_ = round_q[1] ? _136_ : _135_;
  assign _106_ = round_q[1] ? _138_ : _137_;
  assign _107_ = round_q[1] ? _140_ : _139_;
  assign _108_ = round_q[1] ? _142_ : _141_;
  assign _109_ = round_q[1] ? _144_ : _143_;
  assign _110_ = round_q[1] ? _146_ : _145_;
  assign _111_ = round_q[1] ? _148_ : _147_;
  assign _112_ = round_q[1] ? _150_ : _149_;
  assign _119_ = round_q[0] ? 32'd1899447441 : 32'd1116352408;
  assign _141_ = round_q[0] ? 32'd1249150122 : 32'd770255983;
  assign _142_ = round_q[0] ? 32'd1996064986 : 32'd1555081692;
  assign _143_ = round_q[0] ? 32'd2821834349 : 32'd2554220882;
  assign _144_ = round_q[0] ? 32'd3210313671 : 32'd2952996808;
  assign _145_ = round_q[0] ? 32'd3584528711 : 32'd3336571891;
  assign _146_ = round_q[0] ? 32'd338241895 : 32'd113926993;
  assign _147_ = round_q[0] ? 32'd773529912 : 32'd666307205;
  assign _148_ = round_q[0] ? 32'd1396182291 : 32'd1294757372;
  assign _149_ = round_q[0] ? 32'd1986661051 : 32'd1695183700;
  assign _150_ = round_q[0] ? 32'd2456956037 : 32'd2177026350;
  assign _120_ = round_q[0] ? 32'd3921009573 : 32'd3049323471;
  assign _121_ = round_q[0] ? 32'd2820302411 : 32'd2730485921;
  assign _122_ = round_q[0] ? 32'd3345764771 : 32'd3259730800;
  assign _123_ = round_q[0] ? 32'd3600352804 : 32'd3516065817;
  assign _124_ = round_q[0] ? 32'd275423344 : 32'd4094571909;
  assign _125_ = round_q[0] ? 32'd506948616 : 32'd430227734;
  assign _126_ = round_q[0] ? 32'd883997877 : 32'd659060556;
  assign _127_ = round_q[0] ? 32'd1322822218 : 32'd958139571;
  assign _128_ = round_q[0] ? 32'd1747873779 : 32'd1537002063;
  assign _129_ = round_q[0] ? 32'd2024104815 : 32'd1955562222;
  assign _130_ = round_q[0] ? 32'd2361852424 : 32'd2227730452;
  assign _133_ = round_q[0] ? 32'd1508970993 : 32'd961987163;
  assign _131_ = round_q[0] ? 32'd2756734187 : 32'd2428436474;
  assign _132_ = round_q[0] ? 32'd3329325298 : 32'd3204031479;
  assign _134_ = round_q[0] ? 32'd2870763221 : 32'd2453635748;
  assign _135_ = round_q[0] ? 32'd310598401 : 32'd3624381080;
  assign _136_ = round_q[0] ? 32'd1426881987 : 32'd607225278;
  assign _137_ = round_q[0] ? 32'd2162078206 : 32'd1925078388;
  assign _138_ = round_q[0] ? 32'd3248222580 : 32'd2614888103;
  assign _139_ = round_q[0] ? 32'd4022224774 : 32'd3835390401;
  assign _140_ = round_q[0] ? 32'd604807628 : 32'd264347078;
  assign busy = | state_q;
  assign _151_ = ~ e_q;
  assign _025_ = { 6'h00, e_q[31:6] } | { e_q[5:0], 26'h0000000 };
  assign _026_ = { 11'h000, e_q[31:11] } | { e_q[10:0], 21'h000000 };
  assign _027_ = { 25'h0000000, e_q[31:25] } | { e_q[24:0], 7'h00 };
  assign _022_ = { 2'h0, a_q[31:2] } | { a_q[1:0], 30'h00000000 };
  assign _023_ = { 13'h0000, a_q[31:13] } | { a_q[12:0], 19'h00000 };
  assign _024_ = { 22'h000000, a_q[31:22] } | { a_q[21:0], 10'h000 };
  assign _152_ = { 17'h00000, _030_[31:17] } | { _030_[16:0], 15'h0000 };
  assign _153_ = { 19'h00000, _030_[31:19] } | { _030_[18:0], 13'h0000 };
  assign _154_ = { 7'h00, _032_[31:7] } | { _032_[6:0], 25'h0000000 };
  assign _155_ = { 18'h00000, _032_[31:18] } | { _032_[17:0], 14'h0000 };
  always @(posedge clk, negedge rst_n)
    if (!rst_n) done <= 1'h0;
    else done <= _015_;
  assign _015_ = _157_ ? 1'h1 : 1'h0;
  assign _158_ = round_q[3:0] == 4'hf;
  assign _159_ = round_q[3:0] == 4'he;
  assign _160_ = round_q[3:0] == 4'hd;
  assign _161_ = round_q[3:0] == 4'hc;
  assign _162_ = round_q[3:0] == 4'hb;
  assign _163_ = round_q[3:0] == 4'ha;
  assign _164_ = round_q[3:0] == 4'h9;
  assign _165_ = round_q[3:0] == 4'h8;
  assign _166_ = round_q[3:0] == 4'h7;
  assign _167_ = round_q[3:0] == 4'h6;
  assign _168_ = round_q[3:0] == 4'h5;
  assign _169_ = round_q[3:0] == 4'h4;
  assign _170_ = round_q[3:0] == 4'h3;
  assign _171_ = round_q[3:0] == 4'h2;
  assign _172_ = round_q[3:0] == 4'h1;
  assign _173_ = ! round_q[3:0];
  function [31:0] _455_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _455_ = b[31:0];
      2'b1?:
        _455_ = b[63:32];
      default:
        _455_ = a;
    endcase
  endfunction
  assign _007_ = _455_(32'hxxxxxxxx, { _175_, _051_ }, { _176_, _157_ });
  assign _175_ = start ? _174_ : 32'hxxxxxxxx;
  function [31:0] _457_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _457_ = b[31:0];
      2'b1?:
        _457_ = b[63:32];
      default:
        _457_ = a;
    endcase
  endfunction
  assign _006_ = _457_(32'hxxxxxxxx, { _178_, _050_ }, { _176_, _157_ });
  assign _178_ = start ? _177_ : 32'hxxxxxxxx;
  function [31:0] _459_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _459_ = b[31:0];
      2'b1?:
        _459_ = b[63:32];
      default:
        _459_ = a;
    endcase
  endfunction
  assign _005_ = _459_(32'hxxxxxxxx, { _180_, _049_ }, { _176_, _157_ });
  assign _180_ = start ? _179_ : 32'hxxxxxxxx;
  function [31:0] _461_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _461_ = b[31:0];
      2'b1?:
        _461_ = b[63:32];
      default:
        _461_ = a;
    endcase
  endfunction
  assign _004_ = _461_(32'hxxxxxxxx, { _182_, _048_ }, { _176_, _157_ });
  assign _182_ = start ? _181_ : 32'hxxxxxxxx;
  function [31:0] _463_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _463_ = b[31:0];
      2'b1?:
        _463_ = b[63:32];
      default:
        _463_ = a;
    endcase
  endfunction
  assign _003_ = _463_(32'hxxxxxxxx, { _184_, _047_ }, { _176_, _157_ });
  assign _184_ = start ? _183_ : 32'hxxxxxxxx;
  function [31:0] _465_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _465_ = b[31:0];
      2'b1?:
        _465_ = b[63:32];
      default:
        _465_ = a;
    endcase
  endfunction
  assign _002_ = _465_(32'hxxxxxxxx, { _186_, _046_ }, { _176_, _157_ });
  assign _186_ = start ? _185_ : 32'hxxxxxxxx;
  function [31:0] _467_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _467_ = b[31:0];
      2'b1?:
        _467_ = b[63:32];
      default:
        _467_ = a;
    endcase
  endfunction
  assign _001_ = _467_(32'hxxxxxxxx, { _188_, _045_ }, { _176_, _157_ });
  assign _188_ = start ? _187_ : 32'hxxxxxxxx;
  function [31:0] _469_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _469_ = b[31:0];
      2'b1?:
        _469_ = b[63:32];
      default:
        _469_ = a;
    endcase
  endfunction
  assign _000_ = _469_(32'hxxxxxxxx, { _190_, _044_ }, { _176_, _157_ });
  assign _190_ = start ? _189_ : 32'hxxxxxxxx;
  function [31:0] _471_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _471_ = b[31:0];
      2'b1?:
        _471_ = b[63:32];
      default:
        _471_ = a;
    endcase
  endfunction
  assign _020_ = _471_(32'hxxxxxxxx, { _175_, g_q }, { _176_, _156_ });
  assign _174_ = init_state ? 32'd1541459225 : state_in[31:0];
  function [31:0] _473_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _473_ = b[31:0];
      2'b1?:
        _473_ = b[63:32];
      default:
        _473_ = a;
    endcase
  endfunction
  assign _018_ = _473_(32'hxxxxxxxx, { _178_, f_q }, { _176_, _156_ });
  assign _177_ = init_state ? 32'd528734635 : state_in[63:32];
  function [31:0] _475_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _475_ = b[31:0];
      2'b1?:
        _475_ = b[63:32];
      default:
        _475_ = a;
    endcase
  endfunction
  assign _017_ = _475_(32'hxxxxxxxx, { _180_, e_q }, { _176_, _156_ });
  assign _179_ = init_state ? 32'd2600822924 : state_in[95:64];
  function [31:0] _477_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _477_ = b[31:0];
      2'b1?:
        _477_ = b[63:32];
      default:
        _477_ = a;
    endcase
  endfunction
  assign _016_ = _477_(32'hxxxxxxxx, { _182_, _041_ }, { _176_, _156_ });
  assign _181_ = init_state ? 32'd1359893119 : state_in[127:96];
  function [31:0] _479_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _479_ = b[31:0];
      2'b1?:
        _479_ = b[63:32];
      default:
        _479_ = a;
    endcase
  endfunction
  assign _014_ = _479_(32'hxxxxxxxx, { _184_, c_q }, { _176_, _156_ });
  assign _183_ = init_state ? 32'd2773480762 : state_in[159:128];
  function [31:0] _481_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _481_ = b[31:0];
      2'b1?:
        _481_ = b[63:32];
      default:
        _481_ = a;
    endcase
  endfunction
  assign _010_ = _481_(32'hxxxxxxxx, { _186_, b_q }, { _176_, _156_ });
  assign _185_ = init_state ? 32'd1013904242 : state_in[191:160];
  function [31:0] _483_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _483_ = b[31:0];
      2'b1?:
        _483_ = b[63:32];
      default:
        _483_ = a;
    endcase
  endfunction
  assign _009_ = _483_(32'hxxxxxxxx, { _188_, a_q }, { _176_, _156_ });
  assign _187_ = init_state ? 32'd3144134277 : state_in[223:192];
  function [31:0] _485_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _485_ = b[31:0];
      2'b1?:
        _485_ = b[63:32];
      default:
        _485_ = a;
    endcase
  endfunction
  assign _008_ = _485_(32'hxxxxxxxx, { _190_, _042_ }, { _176_, _156_ });
  assign _189_ = init_state ? 32'd1779033703 : state_in[255:224];
  assign _191_ = _087_ ? 6'hxx : _043_;
  function [5:0] _488_;
    input [5:0] a;
    input [11:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _488_ = b[5:0];
      2'b1?:
        _488_ = b[11:6];
      default:
        _488_ = a;
    endcase
  endfunction
  assign _028_ = _488_(6'hxx, { _192_, _191_ }, { _176_, _156_ });
  assign _192_ = start ? 6'h00 : 6'hxx;
  function [1:0] _490_;
    input [1:0] a;
    input [5:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        _490_ = b[1:0];
      3'b?1?:
        _490_ = b[3:2];
      3'b1??:
        _490_ = b[5:4];
      default:
        _490_ = a;
    endcase
  endfunction
  assign _029_ = _490_(2'hx, { _194_, _193_, 2'h0 }, { _176_, _156_, _157_ });
  assign _157_ = state_q == 2'h2;
  assign _193_ = _087_ ? 2'h2 : 2'hx;
  assign _156_ = state_q == 2'h1;
  assign _194_ = start ? 2'h1 : 2'hx;
  assign _176_ = ! state_q;
  function [31:0] _496_;
    input [31:0] a;
    input [511:0] b;
    input [15:0] s;
    casez (s) // synopsys parallel_case
      16'b???????????????1:
        _496_ = b[31:0];
      16'b??????????????1?:
        _496_ = b[63:32];
      16'b?????????????1??:
        _496_ = b[95:64];
      16'b????????????1???:
        _496_ = b[127:96];
      16'b???????????1????:
        _496_ = b[159:128];
      16'b??????????1?????:
        _496_ = b[191:160];
      16'b?????????1??????:
        _496_ = b[223:192];
      16'b????????1???????:
        _496_ = b[255:224];
      16'b???????1????????:
        _496_ = b[287:256];
      16'b??????1?????????:
        _496_ = b[319:288];
      16'b?????1??????????:
        _496_ = b[351:320];
      16'b????1???????????:
        _496_ = b[383:352];
      16'b???1????????????:
        _496_ = b[415:384];
      16'b??1?????????????:
        _496_ = b[447:416];
      16'b?1??????????????:
        _496_ = b[479:448];
      16'b1???????????????:
        _496_ = b[511:480];
      default:
        _496_ = a;
    endcase
  endfunction
  assign _195_ = _496_(32'hxxxxxxxx, { \w_mem[0] , \w_mem[1] , \w_mem[2] , \w_mem[3] , \w_mem[4] , \w_mem[5] , \w_mem[6] , \w_mem[7] , \w_mem[8] , \w_mem[9] , \w_mem[10] , \w_mem[11] , \w_mem[12] , \w_mem[13] , \w_mem[14] , \w_mem[15]  }, { _211_, _210_, _209_, _208_, _207_, _206_, _205_, _204_, _203_, _202_, _201_, _200_, _199_, _198_, _197_, _196_ });
  assign _196_ = _058_[3:0] == 4'hf;
  assign _197_ = _058_[3:0] == 4'he;
  assign _198_ = _058_[3:0] == 4'hd;
  assign _199_ = _058_[3:0] == 4'hc;
  assign _200_ = _058_[3:0] == 4'hb;
  assign _201_ = _058_[3:0] == 4'ha;
  assign _202_ = _058_[3:0] == 4'h9;
  assign _203_ = _058_[3:0] == 4'h8;
  assign _204_ = _058_[3:0] == 4'h7;
  assign _205_ = _058_[3:0] == 4'h6;
  assign _206_ = _058_[3:0] == 4'h5;
  assign _207_ = _058_[3:0] == 4'h4;
  assign _208_ = _058_[3:0] == 4'h3;
  assign _209_ = _058_[3:0] == 4'h2;
  assign _210_ = _058_[3:0] == 4'h1;
  assign _211_ = ! _058_[3:0];
  assign _033_ = _088_ ? 32'hxxxxxxxx : _195_;
  function [31:0] _514_;
    input [31:0] a;
    input [511:0] b;
    input [15:0] s;
    casez (s) // synopsys parallel_case
      16'b???????????????1:
        _514_ = b[31:0];
      16'b??????????????1?:
        _514_ = b[63:32];
      16'b?????????????1??:
        _514_ = b[95:64];
      16'b????????????1???:
        _514_ = b[127:96];
      16'b???????????1????:
        _514_ = b[159:128];
      16'b??????????1?????:
        _514_ = b[191:160];
      16'b?????????1??????:
        _514_ = b[223:192];
      16'b????????1???????:
        _514_ = b[255:224];
      16'b???????1????????:
        _514_ = b[287:256];
      16'b??????1?????????:
        _514_ = b[319:288];
      16'b?????1??????????:
        _514_ = b[351:320];
      16'b????1???????????:
        _514_ = b[383:352];
      16'b???1????????????:
        _514_ = b[415:384];
      16'b??1?????????????:
        _514_ = b[447:416];
      16'b?1??????????????:
        _514_ = b[479:448];
      16'b1???????????????:
        _514_ = b[511:480];
      default:
        _514_ = a;
    endcase
  endfunction
  assign _212_ = _514_(32'hxxxxxxxx, { \w_mem[0] , \w_mem[1] , \w_mem[2] , \w_mem[3] , \w_mem[4] , \w_mem[5] , \w_mem[6] , \w_mem[7] , \w_mem[8] , \w_mem[9] , \w_mem[10] , \w_mem[11] , \w_mem[12] , \w_mem[13] , \w_mem[14] , \w_mem[15]  }, { _228_, _227_, _226_, _225_, _224_, _223_, _222_, _221_, _220_, _219_, _218_, _217_, _216_, _215_, _214_, _213_ });
  assign _213_ = _056_[3:0] == 4'hf;
  assign _214_ = _056_[3:0] == 4'he;
  assign _215_ = _056_[3:0] == 4'hd;
  assign _216_ = _056_[3:0] == 4'hc;
  assign _217_ = _056_[3:0] == 4'hb;
  assign _218_ = _056_[3:0] == 4'ha;
  assign _219_ = _056_[3:0] == 4'h9;
  assign _220_ = _056_[3:0] == 4'h8;
  assign _221_ = _056_[3:0] == 4'h7;
  assign _222_ = _056_[3:0] == 4'h6;
  assign _223_ = _056_[3:0] == 4'h5;
  assign _224_ = _056_[3:0] == 4'h4;
  assign _225_ = _056_[3:0] == 4'h3;
  assign _226_ = _056_[3:0] == 4'h2;
  assign _227_ = _056_[3:0] == 4'h1;
  assign _228_ = ! _056_[3:0];
  assign _031_ = _088_ ? 32'hxxxxxxxx : _212_;
  function [31:0] _532_;
    input [31:0] a;
    input [511:0] b;
    input [15:0] s;
    casez (s) // synopsys parallel_case
      16'b???????????????1:
        _532_ = b[31:0];
      16'b??????????????1?:
        _532_ = b[63:32];
      16'b?????????????1??:
        _532_ = b[95:64];
      16'b????????????1???:
        _532_ = b[127:96];
      16'b???????????1????:
        _532_ = b[159:128];
      16'b??????????1?????:
        _532_ = b[191:160];
      16'b?????????1??????:
        _532_ = b[223:192];
      16'b????????1???????:
        _532_ = b[255:224];
      16'b???????1????????:
        _532_ = b[287:256];
      16'b??????1?????????:
        _532_ = b[319:288];
      16'b?????1??????????:
        _532_ = b[351:320];
      16'b????1???????????:
        _532_ = b[383:352];
      16'b???1????????????:
        _532_ = b[415:384];
      16'b??1?????????????:
        _532_ = b[447:416];
      16'b?1??????????????:
        _532_ = b[479:448];
      16'b1???????????????:
        _532_ = b[511:480];
      default:
        _532_ = a;
    endcase
  endfunction
  assign _229_ = _532_(32'hxxxxxxxx, { \w_mem[0] , \w_mem[1] , \w_mem[2] , \w_mem[3] , \w_mem[4] , \w_mem[5] , \w_mem[6] , \w_mem[7] , \w_mem[8] , \w_mem[9] , \w_mem[10] , \w_mem[11] , \w_mem[12] , \w_mem[13] , \w_mem[14] , \w_mem[15]  }, { _245_, _244_, _243_, _242_, _241_, _240_, _239_, _238_, _237_, _236_, _235_, _234_, _233_, _232_, _231_, _230_ });
  assign _230_ = _057_[3:0] == 4'hf;
  assign _231_ = _057_[3:0] == 4'he;
  assign _232_ = _057_[3:0] == 4'hd;
  assign _233_ = _057_[3:0] == 4'hc;
  assign _234_ = _057_[3:0] == 4'hb;
  assign _235_ = _057_[3:0] == 4'ha;
  assign _236_ = _057_[3:0] == 4'h9;
  assign _237_ = _057_[3:0] == 4'h8;
  assign _238_ = _057_[3:0] == 4'h7;
  assign _239_ = _057_[3:0] == 4'h6;
  assign _240_ = _057_[3:0] == 4'h5;
  assign _241_ = _057_[3:0] == 4'h4;
  assign _242_ = _057_[3:0] == 4'h3;
  assign _243_ = _057_[3:0] == 4'h2;
  assign _244_ = _057_[3:0] == 4'h1;
  assign _245_ = ! _057_[3:0];
  assign _032_ = _088_ ? 32'hxxxxxxxx : _229_;
  function [31:0] _550_;
    input [31:0] a;
    input [511:0] b;
    input [15:0] s;
    casez (s) // synopsys parallel_case
      16'b???????????????1:
        _550_ = b[31:0];
      16'b??????????????1?:
        _550_ = b[63:32];
      16'b?????????????1??:
        _550_ = b[95:64];
      16'b????????????1???:
        _550_ = b[127:96];
      16'b???????????1????:
        _550_ = b[159:128];
      16'b??????????1?????:
        _550_ = b[191:160];
      16'b?????????1??????:
        _550_ = b[223:192];
      16'b????????1???????:
        _550_ = b[255:224];
      16'b???????1????????:
        _550_ = b[287:256];
      16'b??????1?????????:
        _550_ = b[319:288];
      16'b?????1??????????:
        _550_ = b[351:320];
      16'b????1???????????:
        _550_ = b[383:352];
      16'b???1????????????:
        _550_ = b[415:384];
      16'b??1?????????????:
        _550_ = b[447:416];
      16'b?1??????????????:
        _550_ = b[479:448];
      16'b1???????????????:
        _550_ = b[511:480];
      default:
        _550_ = a;
    endcase
  endfunction
  assign _246_ = _550_(32'hxxxxxxxx, { \w_mem[0] , \w_mem[1] , \w_mem[2] , \w_mem[3] , \w_mem[4] , \w_mem[5] , \w_mem[6] , \w_mem[7] , \w_mem[8] , \w_mem[9] , \w_mem[10] , \w_mem[11] , \w_mem[12] , \w_mem[13] , \w_mem[14] , \w_mem[15]  }, { _262_, _261_, _260_, _259_, _258_, _257_, _256_, _255_, _254_, _253_, _252_, _251_, _250_, _249_, _248_, _247_ });
  assign _247_ = _055_[3:0] == 4'hf;
  assign _248_ = _055_[3:0] == 4'he;
  assign _249_ = _055_[3:0] == 4'hd;
  assign _250_ = _055_[3:0] == 4'hc;
  assign _251_ = _055_[3:0] == 4'hb;
  assign _252_ = _055_[3:0] == 4'ha;
  assign _253_ = _055_[3:0] == 4'h9;
  assign _254_ = _055_[3:0] == 4'h8;
  assign _255_ = _055_[3:0] == 4'h7;
  assign _256_ = _055_[3:0] == 4'h6;
  assign _257_ = _055_[3:0] == 4'h5;
  assign _258_ = _055_[3:0] == 4'h4;
  assign _259_ = _055_[3:0] == 4'h3;
  assign _260_ = _055_[3:0] == 4'h2;
  assign _261_ = _055_[3:0] == 4'h1;
  assign _262_ = ! _055_[3:0];
  assign _030_ = _088_ ? 32'hxxxxxxxx : _246_;
  assign current_w = _088_ ? _263_ : _036_;
  wire [511:0] _586_ = block_in;
  assign _263_ = _586_[$signed({ _034_[31:5], 5'h00 }) +: 32];
  assign { _264_[31:27], _034_[31:5] } = 32'd15 - round_q;
  assign { _265_[31:4], _055_[3:0] } = round_q - 32'd2;
  assign { _266_[31:4], _056_[3:0] } = round_q - 32'd7;
  assign { _267_[31:4], _057_[3:0] } = round_q - 32'd15;
  assign { _268_[31:4], _058_[3:0] } = round_q - 32'd16;
  assign _269_ = _052_ ^ _053_;
  assign _021_ = _269_ ^ _054_;
  assign _270_ = _154_ ^ _155_;
  assign _271_ = _270_ ^ { 3'h0, _032_[31:3] };
  assign _272_ = _152_ ^ _153_;
  assign _273_ = _272_ ^ { 10'h000, _030_[31:10] };
  assign _274_ = _022_ ^ _023_;
  assign _011_ = _274_ ^ _024_;
  assign _275_ = _025_ ^ _026_;
  assign _012_ = _275_ ^ _027_;
  assign _013_ = _059_ ^ _060_;
  assign _034_[4:0] = 5'h00;
  assign _055_[31:4] = 28'h0000000;
  assign _056_[31:4] = 28'h0000000;
  assign _057_[31:4] = 28'h0000000;
  assign _058_[31:4] = 28'h0000000;
  assign _264_[26:0] = _034_[31:5];
  assign _265_[3:0] = _055_[3:0];
  assign _266_[3:0] = _056_[3:0];
  assign _267_[3:0] = _057_[3:0];
  assign _268_[3:0] = _058_[3:0];
  assign \cap_sigma0$func$fabric_p0/rtl/evidence/geo_sha256_core.sv:142$13.x  = 32'hxxxxxxxx;
  assign \cap_sigma1$func$fabric_p0/rtl/evidence/geo_sha256_core.sv:141$7.x  = 32'hxxxxxxxx;
  assign \ch$func$fabric_p0/rtl/evidence/geo_sha256_core.sv:141$8.x  = 32'hxxxxxxxx;
  assign \ch$func$fabric_p0/rtl/evidence/geo_sha256_core.sv:141$8.y  = 32'hxxxxxxxx;
  assign \ch$func$fabric_p0/rtl/evidence/geo_sha256_core.sv:141$8.z  = 32'hxxxxxxxx;
  assign digest_out = { H0_q, H1_q, H2_q, H3_q, H4_q, H5_q, H6_q, H7_q };
  assign \get_k$func$fabric_p0/rtl/evidence/geo_sha256_core.sv:141$9.round_idx  = 6'hxx;
  assign \maj$func$fabric_p0/rtl/evidence/geo_sha256_core.sv:142$14.x  = 32'hxxxxxxxx;
  assign \maj$func$fabric_p0/rtl/evidence/geo_sha256_core.sv:142$14.y  = 32'hxxxxxxxx;
  assign \maj$func$fabric_p0/rtl/evidence/geo_sha256_core.sv:142$14.z  = 32'hxxxxxxxx;
  assign \rotr$func$fabric_p0/rtl/evidence/geo_sha256_core.sv:81$5.x  = 32'hxxxxxxxx;
  assign \rotr$func$fabric_p0/rtl/evidence/geo_sha256_core.sv:81$6.x  = 32'hxxxxxxxx;
  assign \rotr$func$fabric_p0/rtl/evidence/geo_sha256_core.sv:85$3.x  = 32'hxxxxxxxx;
  assign \rotr$func$fabric_p0/rtl/evidence/geo_sha256_core.sv:85$4.x  = 32'hxxxxxxxx;
  assign \rotr$func$fabric_p0/rtl/evidence/geo_sha256_core.sv:89$15.x  = 32'hxxxxxxxx;
  assign \rotr$func$fabric_p0/rtl/evidence/geo_sha256_core.sv:89$16.x  = 32'hxxxxxxxx;
  assign \rotr$func$fabric_p0/rtl/evidence/geo_sha256_core.sv:89$17.x  = 32'hxxxxxxxx;
  assign \rotr$func$fabric_p0/rtl/evidence/geo_sha256_core.sv:93$10.x  = 32'hxxxxxxxx;
  assign \rotr$func$fabric_p0/rtl/evidence/geo_sha256_core.sv:93$11.x  = 32'hxxxxxxxx;
  assign \rotr$func$fabric_p0/rtl/evidence/geo_sha256_core.sv:93$12.x  = 32'hxxxxxxxx;
  assign \sigma0$func$fabric_p0/rtl/evidence/geo_sha256_core.sv:133$2.x  = 32'hxxxxxxxx;
  assign \sigma1$func$fabric_p0/rtl/evidence/geo_sha256_core.sv:131$1.x  = 32'hxxxxxxxx;
endmodule
