/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module \$paramod$379ecd25f1665ab0d213a7b716ca7b69b1369608\geo_bilinear_ops (a_s, a_e1, a_e2, a_e12, b_s, b_e1, b_e2, b_e12, op_sel, out_s, out_e1, out_e2, out_e12, overflow);
  wire [31:0] _00_;
  wire [31:0] _01_;
  wire [31:0] _02_;
  wire [31:0] _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire [31:0] _17_;
  wire [31:0] _18_;
  wire [31:0] _19_;
  input [31:0] a_e1;
  wire [31:0] a_e1;
  input [31:0] a_e12;
  wire [31:0] a_e12;
  input [31:0] a_e2;
  wire [31:0] a_e2;
  input [31:0] a_s;
  wire [31:0] a_s;
  wire [31:0] ab_e1;
  wire [31:0] ab_e12;
  wire [31:0] ab_e2;
  wire ab_ovf;
  wire [31:0] ab_s;
  wire [31:0] acomm_e1;
  wire [31:0] acomm_e12;
  wire [31:0] acomm_e2;
  wire [31:0] acomm_s;
  input [31:0] b_e1;
  wire [31:0] b_e1;
  input [31:0] b_e12;
  wire [31:0] b_e12;
  input [31:0] b_e2;
  wire [31:0] b_e2;
  input [31:0] b_s;
  wire [31:0] b_s;
  wire [31:0] ba_e1;
  wire [31:0] ba_e12;
  wire [31:0] ba_e2;
  wire ba_ovf;
  wire [31:0] ba_s;
  wire [31:0] comm_e1;
  wire [31:0] comm_e12;
  wire [31:0] comm_e2;
  wire [31:0] comm_s;
  wire [32:0] diff_e1;
  wire [32:0] diff_e12;
  wire [32:0] diff_e2;
  wire [32:0] diff_s;
  wire [32:0] dot_ext;
  wire dot_ovf;
  wire [32:0] norm_ext;
  wire norm_ovf;
  input [2:0] op_sel;
  wire [2:0] op_sel;
  output [31:0] out_e1;
  wire [31:0] out_e1;
  output [31:0] out_e12;
  wire [31:0] out_e12;
  output [31:0] out_e2;
  wire [31:0] out_e2;
  output [31:0] out_s;
  wire [31:0] out_s;
  output overflow;
  wire overflow;
  wire ovf_a1a1;
  wire ovf_a2a2;
  wire ovf_e1e1;
  wire ovf_e1e2;
  wire ovf_e2e1;
  wire ovf_e2e2;
  wire [31:0] p_a1a1;
  wire [31:0] p_a2a2;
  wire [31:0] p_e1e1;
  wire [31:0] p_e1e2;
  wire [31:0] p_e2e1;
  wire [31:0] p_e2e2;
  wire [32:0] sum_e1;
  wire [32:0] sum_e12;
  wire [32:0] sum_e2;
  wire [32:0] sum_s;
  wire [32:0] wedge_ext;
  wire wedge_ovf;
  assign norm_ext = { p_a1a1[31], p_a1a1 } + { p_a2a2[31], p_a2a2 };
  assign sum_s = { ab_s[31], ab_s } + { ba_s[31], ba_s };
  assign sum_e1 = { ab_e1[31], ab_e1 } + { ba_e1[31], ba_e1 };
  assign sum_e2 = { ab_e2[31], ab_e2 } + { ba_e2[31], ba_e2 };
  assign sum_e12 = { ab_e12[31], ab_e12 } + { ba_e12[31], ba_e12 };
  assign dot_ext = { p_e1e1[31], p_e1e1 } + { p_e2e2[31], p_e2e2 };
  assign _04_ = | { _13_, _14_ };
  assign _05_ = ovf_a1a1 || ovf_a2a2;
  assign norm_ovf = _05_ || _09_;
  assign _06_ = ab_ovf || ba_ovf;
  assign _07_ = ovf_e1e1 || ovf_e2e2;
  assign dot_ovf = _07_ || _10_;
  assign _08_ = ovf_e1e2 || ovf_e2e1;
  assign wedge_ovf = _08_ || _11_;
  assign _09_ = norm_ext[32] != norm_ext[31];
  assign _10_ = dot_ext[32] != dot_ext[31];
  assign _11_ = wedge_ext[32] != wedge_ext[31];
  assign out_e12 = overflow ? 32'd0 : _00_;
  assign out_e2 = overflow ? 32'd0 : _02_;
  assign out_e1 = overflow ? 32'd0 : _01_;
  assign out_s = overflow ? 32'd0 : _03_;
  function [0:0] _41_;
    input [0:0] a;
    input [3:0] b;
    input [3:0] s;
    casez (s) // synopsys parallel_case
      4'b???1:
        _41_ = b[0:0];
      4'b??1?:
        _41_ = b[1:1];
      4'b?1??:
        _41_ = b[2:2];
      4'b1???:
        _41_ = b[3:3];
      default:
        _41_ = a;
    endcase
  endfunction
  assign overflow = _41_(1'h1, { dot_ovf, wedge_ovf, _06_, norm_ovf }, { _16_, _15_, _04_, _12_ });
  function [31:0] _42_;
    input [31:0] a;
    input [127:0] b;
    input [3:0] s;
    casez (s) // synopsys parallel_case
      4'b???1:
        _42_ = b[31:0];
      4'b??1?:
        _42_ = b[63:32];
      4'b?1??:
        _42_ = b[95:64];
      4'b1???:
        _42_ = b[127:96];
      default:
        _42_ = a;
    endcase
  endfunction
  assign _03_ = _42_(32'd0, { _17_, diff_s[32:1], sum_s[32:1], _19_ }, { _16_, _14_, _13_, _12_ });
  assign _12_ = op_sel == 3'h4;
  assign _16_ = ! op_sel;
  function [31:0] _45_;
    input [31:0] a;
    input [95:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        _45_ = b[31:0];
      3'b?1?:
        _45_ = b[63:32];
      3'b1??:
        _45_ = b[95:64];
      default:
        _45_ = a;
    endcase
  endfunction
  assign _00_ = _45_(32'd0, { _18_, diff_e12[32:1], sum_e12[32:1] }, { _15_, _14_, _13_ });
  assign _15_ = op_sel == 3'h1;
  function [31:0] _47_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _47_ = b[31:0];
      2'b1?:
        _47_ = b[63:32];
      default:
        _47_ = a;
    endcase
  endfunction
  assign _02_ = _47_(32'd0, { diff_e2[32:1], sum_e2[32:1] }, { _14_, _13_ });
  function [31:0] _48_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _48_ = b[31:0];
      2'b1?:
        _48_ = b[63:32];
      default:
        _48_ = a;
    endcase
  endfunction
  assign _01_ = _48_(32'd0, { diff_e1[32:1], sum_e1[32:1] }, { _14_, _13_ });
  assign _13_ = op_sel == 3'h3;
  assign _14_ = op_sel == 3'h2;
  assign diff_s = { ab_s[31], ab_s } - { ba_s[31], ba_s };
  assign diff_e1 = { ab_e1[31], ab_e1 } - { ba_e1[31], ba_e1 };
  assign diff_e2 = { ab_e2[31], ab_e2 } - { ba_e2[31], ba_e2 };
  assign diff_e12 = { ab_e12[31], ab_e12 } - { ba_e12[31], ba_e12 };
  assign wedge_ext = { p_e1e2[31], p_e1e2 } - { p_e2e1[31], p_e2e1 };
  assign _17_ = dot_ovf ? 32'd0 : dot_ext[31:0];
  assign _18_ = wedge_ovf ? 32'd0 : wedge_ext[31:0];
  assign _19_ = norm_ovf ? 32'd0 : norm_ext[31:0];
  \$paramod$379ecd25f1665ab0d213a7b716ca7b69b1369608\geo_cl20_multivector  u_ab (
    .a_e1(a_e1),
    .a_e12(a_e12),
    .a_e2(a_e2),
    .a_s(a_s),
    .b_e1(b_e1),
    .b_e12(b_e12),
    .b_e2(b_e2),
    .b_s(b_s),
    .overflow(ab_ovf),
    .y_e1(ab_e1),
    .y_e12(ab_e12),
    .y_e2(ab_e2),
    .y_s(ab_s)
  );
  \$paramod$379ecd25f1665ab0d213a7b716ca7b69b1369608\geo_cl20_multivector  u_ba (
    .a_e1(b_e1),
    .a_e12(b_e12),
    .a_e2(b_e2),
    .a_s(b_s),
    .b_e1(a_e1),
    .b_e12(a_e12),
    .b_e2(a_e2),
    .b_s(a_s),
    .overflow(ba_ovf),
    .y_e1(ba_e1),
    .y_e12(ba_e12),
    .y_e2(ba_e2),
    .y_s(ba_s)
  );
  \$paramod$379ecd25f1665ab0d213a7b716ca7b69b1369608\geo_fixed_arith  u_mul1 (
    .a(a_e1),
    .b(b_e1),
    .mul_overflow(ovf_e1e1),
    .prod(p_e1e1)
  );
  \$paramod$379ecd25f1665ab0d213a7b716ca7b69b1369608\geo_fixed_arith  u_mul2 (
    .a(a_e2),
    .b(b_e2),
    .mul_overflow(ovf_e2e2),
    .prod(p_e2e2)
  );
  \$paramod$379ecd25f1665ab0d213a7b716ca7b69b1369608\geo_fixed_arith  u_mul3 (
    .a(a_e1),
    .b(b_e2),
    .mul_overflow(ovf_e1e2),
    .prod(p_e1e2)
  );
  \$paramod$379ecd25f1665ab0d213a7b716ca7b69b1369608\geo_fixed_arith  u_mul4 (
    .a(a_e2),
    .b(b_e1),
    .mul_overflow(ovf_e2e1),
    .prod(p_e2e1)
  );
  \$paramod$379ecd25f1665ab0d213a7b716ca7b69b1369608\geo_fixed_arith  u_mul_norm1 (
    .a(a_e1),
    .b(a_e1),
    .mul_overflow(ovf_a1a1),
    .prod(p_a1a1)
  );
  \$paramod$379ecd25f1665ab0d213a7b716ca7b69b1369608\geo_fixed_arith  u_mul_norm2 (
    .a(a_e2),
    .b(a_e2),
    .mul_overflow(ovf_a2a2),
    .prod(p_a2a2)
  );
  assign acomm_e1 = sum_e1[32:1];
  assign acomm_e12 = sum_e12[32:1];
  assign acomm_e2 = sum_e2[32:1];
  assign acomm_s = sum_s[32:1];
  assign comm_e1 = diff_e1[32:1];
  assign comm_e12 = diff_e12[32:1];
  assign comm_e2 = diff_e2[32:1];
  assign comm_s = diff_s[32:1];
endmodule

module \$paramod$379ecd25f1665ab0d213a7b716ca7b69b1369608\geo_cl20_multivector (a_s, a_e1, a_e2, a_e12, b_s, b_e1, b_e2, b_e12, y_s, y_e1, y_e2, y_e12, overflow);
  wire [63:0] _000_;
  wire _001_;
  wire [63:0] _002_;
  wire [63:0] _003_;
  wire _004_;
  wire [63:0] _005_;
  wire [63:0] _006_;
  wire _007_;
  wire [63:0] _008_;
  wire [63:0] _009_;
  wire _010_;
  wire [63:0] _011_;
  wire [63:0] _012_;
  wire _013_;
  wire [63:0] _014_;
  wire [63:0] _015_;
  wire _016_;
  wire [63:0] _017_;
  wire [63:0] _018_;
  wire _019_;
  wire [63:0] _020_;
  wire [63:0] _021_;
  wire _022_;
  wire [63:0] _023_;
  wire [63:0] _024_;
  wire _025_;
  wire [63:0] _026_;
  wire [63:0] _027_;
  wire _028_;
  wire [63:0] _029_;
  wire [63:0] _030_;
  wire _031_;
  wire [63:0] _032_;
  wire [63:0] _033_;
  wire _034_;
  wire [63:0] _035_;
  wire [63:0] _036_;
  wire _037_;
  wire [63:0] _038_;
  wire [63:0] _039_;
  wire _040_;
  wire [63:0] _041_;
  wire [63:0] _042_;
  wire _043_;
  wire [63:0] _044_;
  wire [63:0] _045_;
  wire _046_;
  wire [63:0] _047_;
  wire [34:0] _048_;
  wire [34:0] _049_;
  wire [34:0] _050_;
  wire [34:0] _051_;
  wire [34:0] _052_;
  wire [34:0] _053_;
  wire [34:0] _054_;
  wire [63:0] _055_;
  wire [63:0] _056_;
  wire [63:0] _057_;
  wire [63:0] _058_;
  wire [63:0] _059_;
  wire [63:0] _060_;
  wire [63:0] _061_;
  wire [63:0] _062_;
  wire [63:0] _063_;
  wire [63:0] _064_;
  wire [63:0] _065_;
  wire [63:0] _066_;
  wire [63:0] _067_;
  wire [63:0] _068_;
  wire [63:0] _069_;
  wire [63:0] _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire [63:0] _103_;
  wire [63:0] _104_;
  wire [63:0] _105_;
  wire [63:0] _106_;
  wire [63:0] _107_;
  wire [63:0] _108_;
  wire [63:0] _109_;
  wire [63:0] _110_;
  wire [63:0] _111_;
  wire [63:0] _112_;
  wire [63:0] _113_;
  wire [63:0] _114_;
  wire [63:0] _115_;
  wire [63:0] _116_;
  wire [63:0] _117_;
  wire [63:0] _118_;
  wire [64:0] _119_;
  wire [64:0] _120_;
  wire [64:0] _121_;
  wire [64:0] _122_;
  wire [64:0] _123_;
  wire [64:0] _124_;
  wire [64:0] _125_;
  wire [64:0] _126_;
  wire [64:0] _127_;
  wire [64:0] _128_;
  wire [64:0] _129_;
  wire [64:0] _130_;
  wire [64:0] _131_;
  wire [64:0] _132_;
  wire [64:0] _133_;
  wire [64:0] _134_;
  wire [34:0] _135_;
  input [31:0] a_e1;
  wire [31:0] a_e1;
  input [31:0] a_e12;
  wire [31:0] a_e12;
  input [31:0] a_e2;
  wire [31:0] a_e2;
  input [31:0] a_s;
  wire [31:0] a_s;
  wire \accumulated_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:194$784.$result ;
  wire [34:0] \accumulated_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:194$820.value ;
  wire \accumulated_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:195$785.$result ;
  wire [34:0] \accumulated_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:195$821.value ;
  wire \accumulated_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:196$786.$result ;
  wire [34:0] \accumulated_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:196$822.value ;
  wire \accumulated_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:197$787.$result ;
  wire [34:0] \accumulated_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:197$823.value ;
  input [31:0] b_e1;
  wire [31:0] b_e1;
  input [31:0] b_e12;
  wire [31:0] b_e12;
  input [31:0] b_e2;
  wire [31:0] b_e2;
  input [31:0] b_s;
  wire [31:0] b_s;
  wire final_overflow;
  wire [31:0] n00;
  wire [31:0] n01;
  wire [31:0] n02;
  wire [31:0] n03;
  wire [31:0] n10;
  wire [31:0] n11;
  wire [31:0] n12;
  wire [31:0] n13;
  wire [31:0] n20;
  wire [31:0] n21;
  wire [31:0] n22;
  wire [31:0] n23;
  wire [31:0] n30;
  wire [31:0] n31;
  wire [31:0] n32;
  wire [31:0] n33;
  output overflow;
  wire overflow;
  wire [63:0] p00;
  wire [63:0] p01;
  wire [63:0] p02;
  wire [63:0] p03;
  wire [63:0] p10;
  wire [63:0] p11;
  wire [63:0] p12;
  wire [63:0] p13;
  wire [63:0] p20;
  wire [63:0] p21;
  wire [63:0] p22;
  wire [63:0] p23;
  wire [63:0] p30;
  wire [63:0] p31;
  wire [63:0] p32;
  wire [63:0] p33;
  wire product_overflow;
  wire [64:0] q00;
  wire [64:0] q01;
  wire [64:0] q02;
  wire [64:0] q03;
  wire [64:0] q10;
  wire [64:0] q11;
  wire [64:0] q12;
  wire [64:0] q13;
  wire [64:0] q20;
  wire [64:0] q21;
  wire [64:0] q22;
  wire [64:0] q23;
  wire [64:0] q30;
  wire [64:0] q31;
  wire [64:0] q32;
  wire [64:0] q33;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:102$788.half ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:102$788.magnitude ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:102$788.mask ;
  wire \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:102$788.negative ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:102$788.product ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:102$788.quotient ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:102$788.remainder ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:103$789.half ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:103$789.magnitude ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:103$789.mask ;
  wire \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:103$789.negative ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:103$789.product ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:103$789.quotient ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:103$789.remainder ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:104$790.half ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:104$790.magnitude ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:104$790.mask ;
  wire \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:104$790.negative ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:104$790.product ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:104$790.quotient ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:104$790.remainder ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:105$791.half ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:105$791.magnitude ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:105$791.mask ;
  wire \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:105$791.negative ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:105$791.product ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:105$791.quotient ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:105$791.remainder ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:107$792.half ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:107$792.magnitude ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:107$792.mask ;
  wire \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:107$792.negative ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:107$792.product ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:107$792.quotient ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:107$792.remainder ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:108$793.half ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:108$793.magnitude ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:108$793.mask ;
  wire \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:108$793.negative ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:108$793.product ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:108$793.quotient ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:108$793.remainder ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:109$794.half ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:109$794.magnitude ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:109$794.mask ;
  wire \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:109$794.negative ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:109$794.product ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:109$794.quotient ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:109$794.remainder ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:110$795.half ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:110$795.magnitude ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:110$795.mask ;
  wire \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:110$795.negative ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:110$795.product ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:110$795.quotient ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:110$795.remainder ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:112$796.half ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:112$796.magnitude ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:112$796.mask ;
  wire \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:112$796.negative ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:112$796.product ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:112$796.quotient ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:112$796.remainder ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:113$797.half ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:113$797.magnitude ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:113$797.mask ;
  wire \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:113$797.negative ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:113$797.product ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:113$797.quotient ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:113$797.remainder ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:114$798.half ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:114$798.magnitude ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:114$798.mask ;
  wire \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:114$798.negative ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:114$798.product ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:114$798.quotient ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:114$798.remainder ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:115$799.half ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:115$799.magnitude ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:115$799.mask ;
  wire \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:115$799.negative ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:115$799.product ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:115$799.quotient ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:115$799.remainder ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:117$800.half ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:117$800.magnitude ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:117$800.mask ;
  wire \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:117$800.negative ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:117$800.product ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:117$800.quotient ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:117$800.remainder ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:118$801.half ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:118$801.magnitude ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:118$801.mask ;
  wire \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:118$801.negative ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:118$801.product ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:118$801.quotient ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:118$801.remainder ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:119$802.half ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:119$802.magnitude ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:119$802.mask ;
  wire \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:119$802.negative ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:119$802.product ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:119$802.quotient ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:119$802.remainder ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:120$803.half ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:120$803.magnitude ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:120$803.mask ;
  wire \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:120$803.negative ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:120$803.product ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:120$803.quotient ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:120$803.remainder ;
  wire \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:177$768.$result ;
  wire \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:177$769.$result ;
  wire \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:177$770.$result ;
  wire \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:177$771.$result ;
  wire [64:0] \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:177$804.value ;
  wire [64:0] \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:177$805.value ;
  wire [64:0] \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:177$806.value ;
  wire [64:0] \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:177$807.value ;
  wire \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:178$772.$result ;
  wire \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:178$773.$result ;
  wire \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:178$774.$result ;
  wire \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:178$775.$result ;
  wire [64:0] \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:178$808.value ;
  wire [64:0] \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:178$809.value ;
  wire [64:0] \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:178$810.value ;
  wire [64:0] \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:178$811.value ;
  wire \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:179$776.$result ;
  wire \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:179$777.$result ;
  wire \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:179$778.$result ;
  wire \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:179$779.$result ;
  wire [64:0] \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:179$812.value ;
  wire [64:0] \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:179$813.value ;
  wire [64:0] \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:179$814.value ;
  wire [64:0] \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:179$815.value ;
  wire \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:180$780.$result ;
  wire \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:180$781.$result ;
  wire \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:180$782.$result ;
  wire \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:180$783.$result ;
  wire [64:0] \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:180$816.value ;
  wire [64:0] \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:180$817.value ;
  wire [64:0] \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:180$818.value ;
  wire [64:0] \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:180$819.value ;
  wire [34:0] sum_e1;
  wire [34:0] sum_e12;
  wire [34:0] sum_e2;
  wire [34:0] sum_s;
  wire [34:0] x00;
  wire [34:0] x01;
  wire [34:0] x02;
  wire [34:0] x03;
  wire [34:0] x10;
  wire [34:0] x11;
  wire [34:0] x12;
  wire [34:0] x13;
  wire [34:0] x20;
  wire [34:0] x21;
  wire [34:0] x22;
  wire [34:0] x23;
  wire [34:0] x30;
  wire [34:0] x31;
  wire [34:0] x32;
  wire [34:0] x33;
  output [31:0] y_e1;
  wire [31:0] y_e1;
  output [31:0] y_e12;
  wire [31:0] y_e12;
  output [31:0] y_e2;
  wire [31:0] y_e2;
  output [31:0] y_s;
  wire [31:0] y_s;
  assign _048_ = $signed({ q00[31], q00[31], q00[31], q00[31:0] }) + $signed({ q11[31], q11[31], q11[31], q11[31:0] });
  assign _049_ = $signed(_048_) + $signed({ q22[31], q22[31], q22[31], q22[31:0] });
  assign _050_ = $signed({ q01[31], q01[31], q01[31], q01[31:0] }) + $signed({ q10[31], q10[31], q10[31], q10[31:0] });
  assign sum_e1 = $signed(_135_) + $signed({ q32[31], q32[31], q32[31], q32[31:0] });
  assign _051_ = $signed({ q02[31], q02[31], q02[31], q02[31:0] }) + $signed({ q20[31], q20[31], q20[31], q20[31:0] });
  assign _052_ = $signed(_051_) + $signed({ q13[31], q13[31], q13[31], q13[31:0] });
  assign _053_ = $signed({ q03[31], q03[31], q03[31], q03[31:0] }) + $signed({ q30[31], q30[31], q30[31], q30[31:0] });
  assign _054_ = $signed(_053_) + $signed({ q12[31], q12[31], q12[31], q12[31:0] });
  assign _055_ = { 16'h0000, _018_[63:16] } + 1'h1;
  assign _056_ = { 16'h0000, _021_[63:16] } + 1'h1;
  assign _057_ = { 16'h0000, _024_[63:16] } + 1'h1;
  assign _058_ = { 16'h0000, _027_[63:16] } + 1'h1;
  assign _059_ = { 16'h0000, _030_[63:16] } + 1'h1;
  assign _060_ = { 16'h0000, _033_[63:16] } + 1'h1;
  assign _061_ = { 16'h0000, _036_[63:16] } + 1'h1;
  assign _062_ = { 16'h0000, _039_[63:16] } + 1'h1;
  assign _063_ = { 16'h0000, _042_[63:16] } + 1'h1;
  assign _064_ = { 16'h0000, _045_[63:16] } + 1'h1;
  assign _065_ = { 16'h0000, _000_[63:16] } + 1'h1;
  assign _066_ = { 16'h0000, _003_[63:16] } + 1'h1;
  assign _067_ = { 16'h0000, _006_[63:16] } + 1'h1;
  assign _068_ = { 16'h0000, _009_[63:16] } + 1'h1;
  assign _069_ = { 16'h0000, _012_[63:16] } + 1'h1;
  assign _070_ = { 16'h0000, _015_[63:16] } + 1'h1;
  assign _071_ = { 48'h000000000000, _018_[15:0] } >= 64'h0000000000008000;
  assign _072_ = { 48'h000000000000, _021_[15:0] } >= 64'h0000000000008000;
  assign _073_ = { 48'h000000000000, _024_[15:0] } >= 64'h0000000000008000;
  assign _074_ = { 48'h000000000000, _027_[15:0] } >= 64'h0000000000008000;
  assign _075_ = { 48'h000000000000, _030_[15:0] } >= 64'h0000000000008000;
  assign _076_ = { 48'h000000000000, _033_[15:0] } >= 64'h0000000000008000;
  assign _077_ = { 48'h000000000000, _036_[15:0] } >= 64'h0000000000008000;
  assign _078_ = { 48'h000000000000, _039_[15:0] } >= 64'h0000000000008000;
  assign _079_ = { 48'h000000000000, _042_[15:0] } >= 64'h0000000000008000;
  assign _080_ = { 48'h000000000000, _045_[15:0] } >= 64'h0000000000008000;
  assign _081_ = { 48'h000000000000, _000_[15:0] } >= 64'h0000000000008000;
  assign _082_ = { 48'h000000000000, _003_[15:0] } >= 64'h0000000000008000;
  assign _083_ = { 48'h000000000000, _006_[15:0] } >= 64'h0000000000008000;
  assign _084_ = { 48'h000000000000, _009_[15:0] } >= 64'h0000000000008000;
  assign _085_ = { 48'h000000000000, _012_[15:0] } >= 64'h0000000000008000;
  assign _086_ = { 48'h000000000000, _015_[15:0] } >= 64'h0000000000008000;
  assign _087_ = \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:177$768.$result  || \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:177$769.$result ;
  assign _088_ = _087_ || \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:177$770.$result ;
  assign _089_ = _088_ || \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:177$771.$result ;
  assign _090_ = _089_ || \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:178$772.$result ;
  assign _091_ = _090_ || \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:178$773.$result ;
  assign _092_ = _091_ || \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:178$774.$result ;
  assign _093_ = _092_ || \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:178$775.$result ;
  assign _094_ = _093_ || \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:179$776.$result ;
  assign _095_ = _094_ || \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:179$777.$result ;
  assign _096_ = _095_ || \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:179$778.$result ;
  assign _097_ = _096_ || \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:179$779.$result ;
  assign _098_ = _097_ || \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:180$780.$result ;
  assign _099_ = _098_ || \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:180$781.$result ;
  assign _100_ = _099_ || \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:180$782.$result ;
  assign product_overflow = _100_ || \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:180$783.$result ;
  assign _101_ = \accumulated_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:194$784.$result  || \accumulated_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:195$785.$result ;
  assign _102_ = _101_ || \accumulated_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:196$786.$result ;
  assign final_overflow = _102_ || \accumulated_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:197$787.$result ;
  assign overflow = product_overflow || final_overflow;
  assign _019_ = $signed(p23) < $signed(32'd0);
  assign _022_ = $signed(p32) < $signed(32'd0);
  assign _025_ = $signed(p02) < $signed(32'd0);
  assign _028_ = $signed(p20) < $signed(32'd0);
  assign _031_ = $signed(p13) < $signed(32'd0);
  assign _034_ = $signed(p31) < $signed(32'd0);
  assign _037_ = $signed(p03) < $signed(32'd0);
  assign _040_ = $signed(p30) < $signed(32'd0);
  assign _043_ = $signed(p12) < $signed(32'd0);
  assign _046_ = $signed(p21) < $signed(32'd0);
  assign _001_ = $signed(p00) < $signed(32'd0);
  assign _004_ = $signed(p11) < $signed(32'd0);
  assign _007_ = $signed(p22) < $signed(32'd0);
  assign _010_ = $signed(p33) < $signed(32'd0);
  assign _013_ = $signed(p01) < $signed(32'd0);
  assign _016_ = $signed(p10) < $signed(32'd0);
  assign p00 = $signed(a_s) * $signed(b_s);
  assign p11 = $signed(a_e1) * $signed(b_e1);
  assign p22 = $signed(a_e2) * $signed(b_e2);
  assign p33 = $signed(a_e12) * $signed(b_e12);
  assign p01 = $signed(a_s) * $signed(b_e1);
  assign p10 = $signed(a_e1) * $signed(b_s);
  assign p23 = $signed(a_e2) * $signed(b_e12);
  assign p32 = $signed(a_e12) * $signed(b_e2);
  assign p02 = $signed(a_s) * $signed(b_e2);
  assign p20 = $signed(a_e2) * $signed(b_s);
  assign p13 = $signed(a_e1) * $signed(b_e12);
  assign p31 = $signed(a_e12) * $signed(b_e1);
  assign p03 = $signed(a_s) * $signed(b_e12);
  assign p30 = $signed(a_e12) * $signed(b_s);
  assign p12 = $signed(a_e1) * $signed(b_e2);
  assign p21 = $signed(a_e2) * $signed(b_e1);
  assign \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:177$768.$result  = q00[64:32] != { q00[31], q00[31], q00[31], q00[31], q00[31], q00[31], q00[31], q00[31], q00[31], q00[31], q00[31], q00[31], q00[31], q00[31], q00[31], q00[31], q00[31], q00[31], q00[31], q00[31], q00[31], q00[31], q00[31], q00[31], q00[31], q00[31], q00[31], q00[31], q00[31], q00[31], q00[31], q00[31], q00[31] };
  assign \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:177$769.$result  = q11[64:32] != { q11[31], q11[31], q11[31], q11[31], q11[31], q11[31], q11[31], q11[31], q11[31], q11[31], q11[31], q11[31], q11[31], q11[31], q11[31], q11[31], q11[31], q11[31], q11[31], q11[31], q11[31], q11[31], q11[31], q11[31], q11[31], q11[31], q11[31], q11[31], q11[31], q11[31], q11[31], q11[31], q11[31] };
  assign \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:177$770.$result  = q22[64:32] != { q22[31], q22[31], q22[31], q22[31], q22[31], q22[31], q22[31], q22[31], q22[31], q22[31], q22[31], q22[31], q22[31], q22[31], q22[31], q22[31], q22[31], q22[31], q22[31], q22[31], q22[31], q22[31], q22[31], q22[31], q22[31], q22[31], q22[31], q22[31], q22[31], q22[31], q22[31], q22[31], q22[31] };
  assign \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:177$771.$result  = q33[64:32] != { q33[31], q33[31], q33[31], q33[31], q33[31], q33[31], q33[31], q33[31], q33[31], q33[31], q33[31], q33[31], q33[31], q33[31], q33[31], q33[31], q33[31], q33[31], q33[31], q33[31], q33[31], q33[31], q33[31], q33[31], q33[31], q33[31], q33[31], q33[31], q33[31], q33[31], q33[31], q33[31], q33[31] };
  assign \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:178$772.$result  = q01[64:32] != { q01[31], q01[31], q01[31], q01[31], q01[31], q01[31], q01[31], q01[31], q01[31], q01[31], q01[31], q01[31], q01[31], q01[31], q01[31], q01[31], q01[31], q01[31], q01[31], q01[31], q01[31], q01[31], q01[31], q01[31], q01[31], q01[31], q01[31], q01[31], q01[31], q01[31], q01[31], q01[31], q01[31] };
  assign \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:178$773.$result  = q10[64:32] != { q10[31], q10[31], q10[31], q10[31], q10[31], q10[31], q10[31], q10[31], q10[31], q10[31], q10[31], q10[31], q10[31], q10[31], q10[31], q10[31], q10[31], q10[31], q10[31], q10[31], q10[31], q10[31], q10[31], q10[31], q10[31], q10[31], q10[31], q10[31], q10[31], q10[31], q10[31], q10[31], q10[31] };
  assign \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:178$774.$result  = q23[64:32] != { q23[31], q23[31], q23[31], q23[31], q23[31], q23[31], q23[31], q23[31], q23[31], q23[31], q23[31], q23[31], q23[31], q23[31], q23[31], q23[31], q23[31], q23[31], q23[31], q23[31], q23[31], q23[31], q23[31], q23[31], q23[31], q23[31], q23[31], q23[31], q23[31], q23[31], q23[31], q23[31], q23[31] };
  assign \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:178$775.$result  = q32[64:32] != { q32[31], q32[31], q32[31], q32[31], q32[31], q32[31], q32[31], q32[31], q32[31], q32[31], q32[31], q32[31], q32[31], q32[31], q32[31], q32[31], q32[31], q32[31], q32[31], q32[31], q32[31], q32[31], q32[31], q32[31], q32[31], q32[31], q32[31], q32[31], q32[31], q32[31], q32[31], q32[31], q32[31] };
  assign \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:179$776.$result  = q02[64:32] != { q02[31], q02[31], q02[31], q02[31], q02[31], q02[31], q02[31], q02[31], q02[31], q02[31], q02[31], q02[31], q02[31], q02[31], q02[31], q02[31], q02[31], q02[31], q02[31], q02[31], q02[31], q02[31], q02[31], q02[31], q02[31], q02[31], q02[31], q02[31], q02[31], q02[31], q02[31], q02[31], q02[31] };
  assign \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:179$777.$result  = q20[64:32] != { q20[31], q20[31], q20[31], q20[31], q20[31], q20[31], q20[31], q20[31], q20[31], q20[31], q20[31], q20[31], q20[31], q20[31], q20[31], q20[31], q20[31], q20[31], q20[31], q20[31], q20[31], q20[31], q20[31], q20[31], q20[31], q20[31], q20[31], q20[31], q20[31], q20[31], q20[31], q20[31], q20[31] };
  assign \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:179$778.$result  = q13[64:32] != { q13[31], q13[31], q13[31], q13[31], q13[31], q13[31], q13[31], q13[31], q13[31], q13[31], q13[31], q13[31], q13[31], q13[31], q13[31], q13[31], q13[31], q13[31], q13[31], q13[31], q13[31], q13[31], q13[31], q13[31], q13[31], q13[31], q13[31], q13[31], q13[31], q13[31], q13[31], q13[31], q13[31] };
  assign \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:179$779.$result  = q31[64:32] != { q31[31], q31[31], q31[31], q31[31], q31[31], q31[31], q31[31], q31[31], q31[31], q31[31], q31[31], q31[31], q31[31], q31[31], q31[31], q31[31], q31[31], q31[31], q31[31], q31[31], q31[31], q31[31], q31[31], q31[31], q31[31], q31[31], q31[31], q31[31], q31[31], q31[31], q31[31], q31[31], q31[31] };
  assign \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:180$780.$result  = q03[64:32] != { q03[31], q03[31], q03[31], q03[31], q03[31], q03[31], q03[31], q03[31], q03[31], q03[31], q03[31], q03[31], q03[31], q03[31], q03[31], q03[31], q03[31], q03[31], q03[31], q03[31], q03[31], q03[31], q03[31], q03[31], q03[31], q03[31], q03[31], q03[31], q03[31], q03[31], q03[31], q03[31], q03[31] };
  assign \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:180$781.$result  = q30[64:32] != { q30[31], q30[31], q30[31], q30[31], q30[31], q30[31], q30[31], q30[31], q30[31], q30[31], q30[31], q30[31], q30[31], q30[31], q30[31], q30[31], q30[31], q30[31], q30[31], q30[31], q30[31], q30[31], q30[31], q30[31], q30[31], q30[31], q30[31], q30[31], q30[31], q30[31], q30[31], q30[31], q30[31] };
  assign \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:180$782.$result  = q12[64:32] != { q12[31], q12[31], q12[31], q12[31], q12[31], q12[31], q12[31], q12[31], q12[31], q12[31], q12[31], q12[31], q12[31], q12[31], q12[31], q12[31], q12[31], q12[31], q12[31], q12[31], q12[31], q12[31], q12[31], q12[31], q12[31], q12[31], q12[31], q12[31], q12[31], q12[31], q12[31], q12[31], q12[31] };
  assign \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:180$783.$result  = q21[64:32] != { q21[31], q21[31], q21[31], q21[31], q21[31], q21[31], q21[31], q21[31], q21[31], q21[31], q21[31], q21[31], q21[31], q21[31], q21[31], q21[31], q21[31], q21[31], q21[31], q21[31], q21[31], q21[31], q21[31], q21[31], q21[31], q21[31], q21[31], q21[31], q21[31], q21[31], q21[31], q21[31], q21[31] };
  assign \accumulated_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:194$784.$result  = sum_s[34:32] != { sum_s[31], sum_s[31], sum_s[31] };
  assign \accumulated_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:195$785.$result  = sum_e1[34:32] != { sum_e1[31], sum_e1[31], sum_e1[31] };
  assign \accumulated_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:196$786.$result  = sum_e2[34:32] != { sum_e2[31], sum_e2[31], sum_e2[31] };
  assign \accumulated_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:197$787.$result  = sum_e12[34:32] != { sum_e12[31], sum_e12[31], sum_e12[31] };
  assign _103_ = - p23;
  assign _104_ = - p32;
  assign _105_ = - p02;
  assign _106_ = - p20;
  assign _107_ = - p13;
  assign _108_ = - p31;
  assign _109_ = - p03;
  assign _110_ = - p30;
  assign _111_ = - p12;
  assign _112_ = - p21;
  assign _113_ = - p00;
  assign _114_ = - p11;
  assign _115_ = - p22;
  assign _116_ = - p33;
  assign _117_ = - p01;
  assign _118_ = - p10;
  assign _119_ = - $signed({ 1'h0, _020_ });
  assign _120_ = - $signed({ 1'h0, _023_ });
  assign _121_ = - $signed({ 1'h0, _026_ });
  assign _122_ = - $signed({ 1'h0, _029_ });
  assign _123_ = - $signed({ 1'h0, _032_ });
  assign _124_ = - $signed({ 1'h0, _035_ });
  assign _125_ = - $signed({ 1'h0, _038_ });
  assign _126_ = - $signed({ 1'h0, _041_ });
  assign _127_ = - $signed({ 1'h0, _044_ });
  assign _128_ = - $signed({ 1'h0, _047_ });
  assign _129_ = - $signed({ 1'h0, _002_ });
  assign _130_ = - $signed({ 1'h0, _005_ });
  assign _131_ = - $signed({ 1'h0, _008_ });
  assign _132_ = - $signed({ 1'h0, _011_ });
  assign _133_ = - $signed({ 1'h0, _014_ });
  assign _134_ = - $signed({ 1'h0, _017_ });
  assign _047_ = _080_ ? _064_ : { 16'h0000, _045_[63:16] };
  assign _044_ = _079_ ? _063_ : { 16'h0000, _042_[63:16] };
  assign _041_ = _078_ ? _062_ : { 16'h0000, _039_[63:16] };
  assign _038_ = _077_ ? _061_ : { 16'h0000, _036_[63:16] };
  assign _035_ = _076_ ? _060_ : { 16'h0000, _033_[63:16] };
  assign _032_ = _075_ ? _059_ : { 16'h0000, _030_[63:16] };
  assign _029_ = _074_ ? _058_ : { 16'h0000, _027_[63:16] };
  assign _026_ = _073_ ? _057_ : { 16'h0000, _024_[63:16] };
  assign _023_ = _072_ ? _056_ : { 16'h0000, _021_[63:16] };
  assign _020_ = _071_ ? _055_ : { 16'h0000, _018_[63:16] };
  assign _017_ = _086_ ? _070_ : { 16'h0000, _015_[63:16] };
  assign _014_ = _085_ ? _069_ : { 16'h0000, _012_[63:16] };
  assign _011_ = _084_ ? _068_ : { 16'h0000, _009_[63:16] };
  assign _008_ = _083_ ? _067_ : { 16'h0000, _006_[63:16] };
  assign _005_ = _082_ ? _066_ : { 16'h0000, _003_[63:16] };
  assign _002_ = _081_ ? _065_ : { 16'h0000, _000_[63:16] };
  assign sum_s = $signed(_049_) - $signed({ q33[31], q33[31], q33[31], q33[31:0] });
  assign _135_ = $signed(_050_) - $signed({ q23[31], q23[31], q23[31], q23[31:0] });
  assign sum_e2 = $signed(_052_) - $signed({ q31[31], q31[31], q31[31], q31[31:0] });
  assign sum_e12 = $signed(_054_) - $signed({ q21[31], q21[31], q21[31], q21[31:0] });
  assign y_s = overflow ? 32'd0 : sum_s[31:0];
  assign y_e1 = overflow ? 32'd0 : sum_e1[31:0];
  assign y_e2 = overflow ? 32'd0 : sum_e2[31:0];
  assign y_e12 = overflow ? 32'd0 : sum_e12[31:0];
  assign _018_ = _019_ ? _103_ : p23;
  assign _021_ = _022_ ? _104_ : p32;
  assign _024_ = _025_ ? _105_ : p02;
  assign _027_ = _028_ ? _106_ : p20;
  assign _030_ = _031_ ? _107_ : p13;
  assign _033_ = _034_ ? _108_ : p31;
  assign _036_ = _037_ ? _109_ : p03;
  assign _039_ = _040_ ? _110_ : p30;
  assign _042_ = _043_ ? _111_ : p12;
  assign _045_ = _046_ ? _112_ : p21;
  assign _000_ = _001_ ? _113_ : p00;
  assign _003_ = _004_ ? _114_ : p11;
  assign _006_ = _007_ ? _115_ : p22;
  assign _009_ = _010_ ? _116_ : p33;
  assign _012_ = _013_ ? _117_ : p01;
  assign _015_ = _016_ ? _118_ : p10;
  assign q23 = _019_ ? _119_ : { 1'h0, _020_ };
  assign q32 = _022_ ? _120_ : { 1'h0, _023_ };
  assign q02 = _025_ ? _121_ : { 1'h0, _026_ };
  assign q20 = _028_ ? _122_ : { 1'h0, _029_ };
  assign q13 = _031_ ? _123_ : { 1'h0, _032_ };
  assign q31 = _034_ ? _124_ : { 1'h0, _035_ };
  assign q03 = _037_ ? _125_ : { 1'h0, _038_ };
  assign q30 = _040_ ? _126_ : { 1'h0, _041_ };
  assign q12 = _043_ ? _127_ : { 1'h0, _044_ };
  assign q21 = _046_ ? _128_ : { 1'h0, _047_ };
  assign q00 = _001_ ? _129_ : { 1'h0, _002_ };
  assign q11 = _004_ ? _130_ : { 1'h0, _005_ };
  assign q22 = _007_ ? _131_ : { 1'h0, _008_ };
  assign q33 = _010_ ? _132_ : { 1'h0, _011_ };
  assign q01 = _013_ ? _133_ : { 1'h0, _014_ };
  assign q10 = _016_ ? _134_ : { 1'h0, _017_ };
  assign \accumulated_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:194$820.value  = 35'hxxxxxxxxx;
  assign \accumulated_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:195$821.value  = 35'hxxxxxxxxx;
  assign \accumulated_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:196$822.value  = 35'hxxxxxxxxx;
  assign \accumulated_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:197$823.value  = 35'hxxxxxxxxx;
  assign n00 = q00[31:0];
  assign n01 = q01[31:0];
  assign n02 = q02[31:0];
  assign n03 = q03[31:0];
  assign n10 = q10[31:0];
  assign n11 = q11[31:0];
  assign n12 = q12[31:0];
  assign n13 = q13[31:0];
  assign n20 = q20[31:0];
  assign n21 = q21[31:0];
  assign n22 = q22[31:0];
  assign n23 = q23[31:0];
  assign n30 = q30[31:0];
  assign n31 = q31[31:0];
  assign n32 = q32[31:0];
  assign n33 = q33[31:0];
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:102$788.half  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:102$788.magnitude  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:102$788.mask  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:102$788.negative  = 1'hx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:102$788.product  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:102$788.quotient  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:102$788.remainder  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:103$789.half  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:103$789.magnitude  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:103$789.mask  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:103$789.negative  = 1'hx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:103$789.product  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:103$789.quotient  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:103$789.remainder  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:104$790.half  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:104$790.magnitude  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:104$790.mask  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:104$790.negative  = 1'hx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:104$790.product  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:104$790.quotient  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:104$790.remainder  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:105$791.half  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:105$791.magnitude  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:105$791.mask  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:105$791.negative  = 1'hx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:105$791.product  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:105$791.quotient  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:105$791.remainder  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:107$792.half  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:107$792.magnitude  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:107$792.mask  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:107$792.negative  = 1'hx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:107$792.product  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:107$792.quotient  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:107$792.remainder  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:108$793.half  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:108$793.magnitude  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:108$793.mask  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:108$793.negative  = 1'hx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:108$793.product  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:108$793.quotient  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:108$793.remainder  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:109$794.half  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:109$794.magnitude  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:109$794.mask  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:109$794.negative  = 1'hx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:109$794.product  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:109$794.quotient  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:109$794.remainder  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:110$795.half  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:110$795.magnitude  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:110$795.mask  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:110$795.negative  = 1'hx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:110$795.product  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:110$795.quotient  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:110$795.remainder  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:112$796.half  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:112$796.magnitude  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:112$796.mask  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:112$796.negative  = 1'hx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:112$796.product  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:112$796.quotient  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:112$796.remainder  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:113$797.half  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:113$797.magnitude  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:113$797.mask  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:113$797.negative  = 1'hx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:113$797.product  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:113$797.quotient  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:113$797.remainder  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:114$798.half  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:114$798.magnitude  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:114$798.mask  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:114$798.negative  = 1'hx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:114$798.product  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:114$798.quotient  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:114$798.remainder  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:115$799.half  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:115$799.magnitude  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:115$799.mask  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:115$799.negative  = 1'hx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:115$799.product  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:115$799.quotient  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:115$799.remainder  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:117$800.half  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:117$800.magnitude  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:117$800.mask  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:117$800.negative  = 1'hx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:117$800.product  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:117$800.quotient  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:117$800.remainder  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:118$801.half  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:118$801.magnitude  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:118$801.mask  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:118$801.negative  = 1'hx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:118$801.product  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:118$801.quotient  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:118$801.remainder  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:119$802.half  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:119$802.magnitude  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:119$802.mask  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:119$802.negative  = 1'hx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:119$802.product  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:119$802.quotient  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:119$802.remainder  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:120$803.half  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:120$803.magnitude  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:120$803.mask  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:120$803.negative  = 1'hx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:120$803.product  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:120$803.quotient  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:120$803.remainder  = 64'hxxxxxxxxxxxxxxxx;
  assign \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:177$804.value  = 65'hxxxxxxxxxxxxxxxxx;
  assign \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:177$805.value  = 65'hxxxxxxxxxxxxxxxxx;
  assign \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:177$806.value  = 65'hxxxxxxxxxxxxxxxxx;
  assign \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:177$807.value  = 65'hxxxxxxxxxxxxxxxxx;
  assign \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:178$808.value  = 65'hxxxxxxxxxxxxxxxxx;
  assign \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:178$809.value  = 65'hxxxxxxxxxxxxxxxxx;
  assign \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:178$810.value  = 65'hxxxxxxxxxxxxxxxxx;
  assign \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:178$811.value  = 65'hxxxxxxxxxxxxxxxxx;
  assign \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:179$812.value  = 65'hxxxxxxxxxxxxxxxxx;
  assign \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:179$813.value  = 65'hxxxxxxxxxxxxxxxxx;
  assign \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:179$814.value  = 65'hxxxxxxxxxxxxxxxxx;
  assign \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:179$815.value  = 65'hxxxxxxxxxxxxxxxxx;
  assign \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:180$816.value  = 65'hxxxxxxxxxxxxxxxxx;
  assign \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:180$817.value  = 65'hxxxxxxxxxxxxxxxxx;
  assign \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:180$818.value  = 65'hxxxxxxxxxxxxxxxxx;
  assign \rounded_overflow$func$fabric_p0/rtl/operators/geo_cl20_multivector.sv:180$819.value  = 65'hxxxxxxxxxxxxxxxxx;
  assign x00 = { q00[31], q00[31], q00[31], q00[31:0] };
  assign x01 = { q01[31], q01[31], q01[31], q01[31:0] };
  assign x02 = { q02[31], q02[31], q02[31], q02[31:0] };
  assign x03 = { q03[31], q03[31], q03[31], q03[31:0] };
  assign x10 = { q10[31], q10[31], q10[31], q10[31:0] };
  assign x11 = { q11[31], q11[31], q11[31], q11[31:0] };
  assign x12 = { q12[31], q12[31], q12[31], q12[31:0] };
  assign x13 = { q13[31], q13[31], q13[31], q13[31:0] };
  assign x20 = { q20[31], q20[31], q20[31], q20[31:0] };
  assign x21 = { q21[31], q21[31], q21[31], q21[31:0] };
  assign x22 = { q22[31], q22[31], q22[31], q22[31:0] };
  assign x23 = { q23[31], q23[31], q23[31], q23[31:0] };
  assign x30 = { q30[31], q30[31], q30[31], q30[31:0] };
  assign x31 = { q31[31], q31[31], q31[31], q31[31:0] };
  assign x32 = { q32[31], q32[31], q32[31], q32[31:0] };
  assign x33 = { q33[31], q33[31], q33[31], q33[31:0] };
endmodule

module \$paramod$379ecd25f1665ab0d213a7b716ca7b69b1369608\geo_fixed_arith (a, b, sum, add_overflow, diff, sub_overflow, prod, mul_overflow, eq, lt, gt);
  wire [63:0] _00_;
  wire _01_;
  wire [63:0] _02_;
  wire [63:0] _03_;
  wire _04_;
  wire [63:0] _05_;
  wire [64:0] _06_;
  input [31:0] a;
  wire [31:0] a;
  output add_overflow;
  wire add_overflow;
  input [31:0] b;
  wire [31:0] b;
  output [31:0] diff;
  wire [31:0] diff;
  output eq;
  wire eq;
  wire [32:0] ext_diff;
  wire [32:0] ext_sum;
  wire [63:0] full_prod;
  output gt;
  wire gt;
  output lt;
  wire lt;
  output mul_overflow;
  wire mul_overflow;
  output [31:0] prod;
  wire [31:0] prod;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_fixed_arith.sv:72$719.half ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_fixed_arith.sv:72$719.magnitude ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_fixed_arith.sv:72$719.mask ;
  wire \round_product$func$fabric_p0/rtl/operators/geo_fixed_arith.sv:72$719.negative ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_fixed_arith.sv:72$719.p ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_fixed_arith.sv:72$719.quotient ;
  wire [63:0] \round_product$func$fabric_p0/rtl/operators/geo_fixed_arith.sv:72$719.remainder ;
  wire [64:0] rounded_prod;
  output sub_overflow;
  wire sub_overflow;
  output [31:0] sum;
  wire [31:0] sum;
  assign ext_sum = { a[31], a } + { b[31], b };
  assign _03_ = { 16'h0000, _00_[63:16] } + 1'h1;
  assign eq = $signed(a) == $signed(b);
  assign _04_ = { 48'h000000000000, _00_[15:0] } >= 64'h0000000000008000;
  assign gt = $signed(a) > $signed(b);
  assign _01_ = $signed(full_prod) < $signed(32'd0);
  assign lt = $signed(a) < $signed(b);
  assign full_prod = $signed(a) * $signed(b);
  assign add_overflow = ext_sum[32] != ext_sum[31];
  assign sub_overflow = ext_diff[32] != ext_diff[31];
  assign mul_overflow = rounded_prod[64:32] != { rounded_prod[31], rounded_prod[31], rounded_prod[31], rounded_prod[31], rounded_prod[31], rounded_prod[31], rounded_prod[31], rounded_prod[31], rounded_prod[31], rounded_prod[31], rounded_prod[31], rounded_prod[31], rounded_prod[31], rounded_prod[31], rounded_prod[31], rounded_prod[31], rounded_prod[31], rounded_prod[31], rounded_prod[31], rounded_prod[31], rounded_prod[31], rounded_prod[31], rounded_prod[31], rounded_prod[31], rounded_prod[31], rounded_prod[31], rounded_prod[31], rounded_prod[31], rounded_prod[31], rounded_prod[31], rounded_prod[31], rounded_prod[31], rounded_prod[31] };
  assign _05_ = - full_prod;
  assign _06_ = - $signed({ 1'h0, _02_ });
  assign _02_ = _04_ ? _03_ : { 16'h0000, _00_[63:16] };
  assign ext_diff = { a[31], a } - { b[31], b };
  assign sum = add_overflow ? 32'd0 : ext_sum[31:0];
  assign diff = sub_overflow ? 32'd0 : ext_diff[31:0];
  assign _00_ = _01_ ? _05_ : full_prod;
  assign rounded_prod = _01_ ? _06_ : { 1'h0, _02_ };
  assign prod = mul_overflow ? 32'd0 : rounded_prod[31:0];
  assign \round_product$func$fabric_p0/rtl/operators/geo_fixed_arith.sv:72$719.half  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_fixed_arith.sv:72$719.magnitude  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_fixed_arith.sv:72$719.mask  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_fixed_arith.sv:72$719.negative  = 1'hx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_fixed_arith.sv:72$719.p  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_fixed_arith.sv:72$719.quotient  = 64'hxxxxxxxxxxxxxxxx;
  assign \round_product$func$fabric_p0/rtl/operators/geo_fixed_arith.sv:72$719.remainder  = 64'hxxxxxxxxxxxxxxxx;
endmodule

module \$paramod\geo_matrix_bridge\WIDTH=s32'00000000000000000000000000100000 (mat_a, mat_b, mat_c, mat_d, mv_s, mv_e1, mv_e2, mv_e12, direction, out_mat_a, out_mat_b, out_mat_c, out_mat_d, out_mv_s, out_mv_e1, out_mv_e2, out_mv_e12, overflow);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire [31:0] _06_;
  wire [31:0] _07_;
  wire [31:0] _08_;
  wire [31:0] _09_;
  input direction;
  wire direction;
  wire [32:0] ext_inv_a;
  wire [32:0] ext_inv_b;
  wire [32:0] ext_inv_c;
  wire [32:0] ext_inv_d;
  wire [32:0] ext_s;
  wire [32:0] ext_x;
  wire [32:0] ext_y;
  wire [32:0] ext_z;
  wire [31:0] fwd_s;
  wire [31:0] fwd_x;
  wire [31:0] fwd_y;
  wire [31:0] fwd_z;
  wire [31:0] inv_a_trunc;
  wire [31:0] inv_b_trunc;
  wire [31:0] inv_c_trunc;
  wire [31:0] inv_d_trunc;
  wire inv_ovf;
  input [31:0] mat_a;
  wire [31:0] mat_a;
  input [31:0] mat_b;
  wire [31:0] mat_b;
  input [31:0] mat_c;
  wire [31:0] mat_c;
  input [31:0] mat_d;
  wire [31:0] mat_d;
  input [31:0] mv_e1;
  wire [31:0] mv_e1;
  input [31:0] mv_e12;
  wire [31:0] mv_e12;
  input [31:0] mv_e2;
  wire [31:0] mv_e2;
  input [31:0] mv_s;
  wire [31:0] mv_s;
  output [31:0] out_mat_a;
  wire [31:0] out_mat_a;
  output [31:0] out_mat_b;
  wire [31:0] out_mat_b;
  output [31:0] out_mat_c;
  wire [31:0] out_mat_c;
  output [31:0] out_mat_d;
  wire [31:0] out_mat_d;
  output [31:0] out_mv_e1;
  wire [31:0] out_mv_e1;
  output [31:0] out_mv_e12;
  wire [31:0] out_mv_e12;
  output [31:0] out_mv_e2;
  wire [31:0] out_mv_e2;
  output [31:0] out_mv_s;
  wire [31:0] out_mv_s;
  output overflow;
  wire overflow;
  assign ext_s = { mat_a[31], mat_a } + { mat_d[31], mat_d };
  assign ext_y = { mat_b[31], mat_b } + { mat_c[31], mat_c };
  assign ext_inv_a = { mv_s[31], mv_s } + { mv_e1[31], mv_e1 };
  assign ext_inv_b = { mv_e2[31], mv_e2 } + { mv_e12[31], mv_e12 };
  assign _00_ = _02_ || _03_;
  assign _01_ = _00_ || _04_;
  assign inv_ovf = _01_ || _05_;
  assign _02_ = ext_inv_a[32] != ext_inv_a[31];
  assign _03_ = ext_inv_b[32] != ext_inv_b[31];
  assign _04_ = ext_inv_c[32] != ext_inv_c[31];
  assign _05_ = ext_inv_d[32] != ext_inv_d[31];
  assign overflow = direction ? inv_ovf : 1'h0;
  assign out_mv_e12 = direction ? 32'd0 : ext_z[32:1];
  assign out_mv_e2 = direction ? 32'd0 : ext_y[32:1];
  assign out_mv_e1 = direction ? 32'd0 : ext_x[32:1];
  assign out_mv_s = direction ? 32'd0 : ext_s[32:1];
  assign out_mat_d = direction ? _09_ : 32'd0;
  assign out_mat_c = direction ? _08_ : 32'd0;
  assign out_mat_b = direction ? _07_ : 32'd0;
  assign out_mat_a = direction ? _06_ : 32'd0;
  assign ext_x = { mat_a[31], mat_a } - { mat_d[31], mat_d };
  assign ext_z = { mat_b[31], mat_b } - { mat_c[31], mat_c };
  assign ext_inv_c = { mv_e2[31], mv_e2 } - { mv_e12[31], mv_e12 };
  assign ext_inv_d = { mv_s[31], mv_s } - { mv_e1[31], mv_e1 };
  assign _06_ = inv_ovf ? 32'd0 : ext_inv_a[31:0];
  assign _07_ = inv_ovf ? 32'd0 : ext_inv_b[31:0];
  assign _08_ = inv_ovf ? 32'd0 : ext_inv_c[31:0];
  assign _09_ = inv_ovf ? 32'd0 : ext_inv_d[31:0];
  assign fwd_s = ext_s[32:1];
  assign fwd_x = ext_x[32:1];
  assign fwd_y = ext_y[32:1];
  assign fwd_z = ext_z[32:1];
  assign inv_a_trunc = ext_inv_a[31:0];
  assign inv_b_trunc = ext_inv_b[31:0];
  assign inv_c_trunc = ext_inv_c[31:0];
  assign inv_d_trunc = ext_inv_d[31:0];
endmodule

module \$paramod\geo_unary_ops\WIDTH=s32'00000000000000000000000000100000 (in_s, in_e1, in_e2, in_e12, op_sel, out_s, out_e1, out_e2, out_e12, overflow);
  wire [31:0] _00_;
  wire [31:0] _01_;
  wire [31:0] _02_;
  wire [31:0] _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire [31:0] _12_;
  wire [31:0] _13_;
  wire [31:0] _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  input [31:0] in_e1;
  wire [31:0] in_e1;
  input [31:0] in_e12;
  wire [31:0] in_e12;
  input [31:0] in_e2;
  wire [31:0] in_e2;
  input [31:0] in_s;
  wire [31:0] in_s;
  wire [31:0] neg_e1;
  wire [31:0] neg_e12;
  wire neg_e12_ovf;
  wire neg_e1_ovf;
  wire [31:0] neg_e2;
  wire neg_e2_ovf;
  input [2:0] op_sel;
  wire [2:0] op_sel;
  output [31:0] out_e1;
  wire [31:0] out_e1;
  output [31:0] out_e12;
  wire [31:0] out_e12;
  output [31:0] out_e2;
  wire [31:0] out_e2;
  output [31:0] out_s;
  wire [31:0] out_s;
  output overflow;
  wire overflow;
  assign _04_ = | { _15_, _19_ };
  assign _05_ = | { _18_, _20_ };
  assign _06_ = | { _17_, _18_, _19_, _20_ };
  assign _09_ = | { _15_, _16_, _17_ };
  assign _07_ = | { _16_, _20_ };
  assign _08_ = | { _18_, _19_ };
  assign neg_e1_ovf = $signed(in_e1) == $signed(32'd2147483648);
  assign neg_e2_ovf = $signed(in_e2) == $signed(32'd2147483648);
  assign neg_e12_ovf = $signed(in_e12) == $signed(32'd2147483648);
  assign _10_ = neg_e1_ovf || neg_e2_ovf;
  assign _11_ = _10_ || neg_e12_ovf;
  assign _12_ = - in_e1;
  assign _13_ = - in_e2;
  assign _14_ = - in_e12;
  assign out_e12 = overflow ? 32'd0 : _00_;
  assign out_e2 = overflow ? 32'd0 : _02_;
  assign out_e1 = overflow ? 32'd0 : _01_;
  assign out_s = overflow ? 32'd0 : _03_;
  function [0:0] _39_;
    input [0:0] a;
    input [3:0] b;
    input [3:0] s;
    casez (s) // synopsys parallel_case
      4'b???1:
        _39_ = b[0:0];
      4'b??1?:
        _39_ = b[1:1];
      4'b?1??:
        _39_ = b[2:2];
      4'b1???:
        _39_ = b[3:3];
      default:
        _39_ = a;
    endcase
  endfunction
  assign overflow = _39_(1'h1, { neg_e12_ovf, _10_, _11_, 1'h0 }, { _20_, _19_, _18_, _09_ });
  function [31:0] _40_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _40_ = b[31:0];
      2'b1?:
        _40_ = b[63:32];
      default:
        _40_ = a;
    endcase
  endfunction
  assign _00_ = _40_(32'd0, { neg_e12, in_e12 }, { _05_, _04_ });
  assign _15_ = op_sel == 3'h5;
  function [31:0] _42_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _42_ = b[31:0];
      2'b1?:
        _42_ = b[63:32];
      default:
        _42_ = a;
    endcase
  endfunction
  assign _02_ = _42_(32'd0, { neg_e2, in_e2 }, { _08_, _07_ });
  function [31:0] _43_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _43_ = b[31:0];
      2'b1?:
        _43_ = b[63:32];
      default:
        _43_ = a;
    endcase
  endfunction
  assign _01_ = _43_(32'd0, { neg_e1, in_e1 }, { _08_, _07_ });
  assign _16_ = op_sel == 3'h4;
  assign _03_ = _06_ ? in_s : 32'd0;
  assign _17_ = op_sel == 3'h3;
  assign _18_ = op_sel == 3'h2;
  assign _19_ = op_sel == 3'h1;
  assign _20_ = ! op_sel;
  assign neg_e1 = neg_e1_ovf ? 32'd0 : _12_;
  assign neg_e2 = neg_e2_ovf ? 32'd0 : _13_;
  assign neg_e12 = neg_e12_ovf ? 32'd0 : _14_;
endmodule

module geo_operator_unit(clk, reset_n, start, opcode, done, overflow, comparison_result, operand_a, operand_b, result);
  wire _00_;
  wire [127:0] _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire [4:0] _17_;
  wire _18_;
  wire [5:0] _19_;
  wire _20_;
  wire [1:0] _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire [31:0] _27_;
  wire add_ovf;
  wire [31:0] arith_diff;
  wire [31:0] arith_prod;
  wire [31:0] arith_sum;
  wire bilinear_ovf;
  wire [127:0] bilinear_res;
  wire [2:0] bilinear_sel;
  wire bridge_dir;
  wire [127:0] bridge_mat_out;
  wire [127:0] bridge_mv_out;
  wire bridge_ovf;
  wire cl20_ovf;
  wire [127:0] cl20_prod;
  input clk;
  wire clk;
  wire cmp_eq;
  wire cmp_gt;
  wire cmp_lt;
  wire comb_comparison;
  wire comb_overflow;
  wire [127:0] comb_result;
  output comparison_result;
  reg comparison_result;
  output done;
  reg done;
  wire [32:0] ext_mv_sub_e1;
  wire [32:0] ext_mv_sub_e12;
  wire [32:0] ext_mv_sub_e2;
  wire [32:0] ext_mv_sub_s;
  wire [32:0] ext_mv_sum_e1;
  wire [32:0] ext_mv_sum_e12;
  wire [32:0] ext_mv_sum_e2;
  wire [32:0] ext_mv_sum_s;
  wire mul_ovf;
  wire mv_add_ovf;
  wire mv_sub_ovf;
  input [5:0] opcode;
  wire [5:0] opcode;
  input [127:0] operand_a;
  wire [127:0] operand_a;
  input [127:0] operand_b;
  wire [127:0] operand_b;
  output overflow;
  reg overflow;
  input reset_n;
  wire reset_n;
  output [127:0] result;
  reg [127:0] result;
  input start;
  wire start;
  wire [31:0] sub_e12_trunc;
  wire [31:0] sub_e1_trunc;
  wire [31:0] sub_e2_trunc;
  wire sub_ovf;
  wire [31:0] sub_s_trunc;
  wire [31:0] sum_e12_trunc;
  wire [31:0] sum_e1_trunc;
  wire [31:0] sum_e2_trunc;
  wire [31:0] sum_s_trunc;
  wire unary_ovf;
  wire [127:0] unary_res;
  wire [2:0] unary_sel;
  assign ext_mv_sum_s = { operand_a[127], operand_a[127:96] } + { operand_b[127], operand_b[127:96] };
  assign ext_mv_sum_e1 = { operand_a[95], operand_a[95:64] } + { operand_b[95], operand_b[95:64] };
  assign ext_mv_sum_e2 = { operand_a[63], operand_a[63:32] } + { operand_b[63], operand_b[63:32] };
  assign ext_mv_sum_e12 = { operand_a[31], operand_a[31:0] } + { operand_b[31], operand_b[31:0] };
  always @(posedge clk, negedge reset_n)
    if (!reset_n) overflow <= 1'h0;
    else if (start) overflow <= comb_overflow;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) result <= 128'h00000000000000000000000000000000;
    else if (start) result <= comb_result;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) comparison_result <= 1'h0;
    else if (start) comparison_result <= comb_comparison;
  assign _02_ = | { bridge_dir, _16_ };
  assign _03_ = operand_a == operand_b;
  assign _04_ = _08_ || _09_;
  assign _05_ = _04_ || _10_;
  assign mv_add_ovf = _05_ || _11_;
  assign _06_ = _12_ || _13_;
  assign _07_ = _06_ || _14_;
  assign mv_sub_ovf = _07_ || _15_;
  assign _08_ = ext_mv_sum_s[32] != ext_mv_sum_s[31];
  assign _09_ = ext_mv_sum_e1[32] != ext_mv_sum_e1[31];
  assign _10_ = ext_mv_sum_e2[32] != ext_mv_sum_e2[31];
  assign _11_ = ext_mv_sum_e12[32] != ext_mv_sum_e12[31];
  assign _12_ = ext_mv_sub_s[32] != ext_mv_sub_s[31];
  assign _13_ = ext_mv_sub_e1[32] != ext_mv_sub_e1[31];
  assign _14_ = ext_mv_sub_e2[32] != ext_mv_sub_e2[31];
  assign _15_ = ext_mv_sub_e12[32] != ext_mv_sub_e12[31];
  always @(posedge clk, negedge reset_n)
    if (!reset_n) done <= 1'h0;
    else done <= _00_;
  assign _00_ = start ? 1'h1 : 1'h0;
  assign comb_result[127:96] = comb_overflow ? 32'd0 : _01_[127:96];
  assign comb_result[31:0] = comb_overflow ? 32'd0 : _01_[31:0];
  assign comb_result[63:32] = comb_overflow ? 32'd0 : _01_[63:32];
  assign comb_result[95:64] = comb_overflow ? 32'd0 : _01_[95:64];
  function [31:0] _57_;
    input [31:0] a;
    input [287:0] b;
    input [8:0] s;
    casez (s) // synopsys parallel_case
      9'b????????1:
        _57_ = b[31:0];
      9'b???????1?:
        _57_ = b[63:32];
      9'b??????1??:
        _57_ = b[95:64];
      9'b?????1???:
        _57_ = b[127:96];
      9'b????1????:
        _57_ = b[159:128];
      9'b???1?????:
        _57_ = b[191:160];
      9'b??1??????:
        _57_ = b[223:192];
      9'b?1???????:
        _57_ = b[255:224];
      9'b1????????:
        _57_ = b[287:256];
      default:
        _57_ = a;
    endcase
  endfunction
  assign _01_[127:96] = _57_(32'd0, { ext_mv_sum_s[31:0], ext_mv_sub_s[31:0], arith_prod, _27_, cl20_prod[127:96], unary_res[127:96], bilinear_res[127:96], bridge_mv_out[127:96], bridge_mat_out[127:96] }, { _26_, _25_, _24_, _23_, _22_, _20_, _18_, _16_, bridge_dir });
  function [0:0] _58_;
    input [0:0] a;
    input [6:0] b;
    input [6:0] s;
    casez (s) // synopsys parallel_case
      7'b??????1:
        _58_ = b[0:0];
      7'b?????1?:
        _58_ = b[1:1];
      7'b????1??:
        _58_ = b[2:2];
      7'b???1???:
        _58_ = b[3:3];
      7'b??1????:
        _58_ = b[4:4];
      7'b?1?????:
        _58_ = b[5:5];
      7'b1??????:
        _58_ = b[6:6];
      default:
        _58_ = a;
    endcase
  endfunction
  assign comb_overflow = _58_(1'h0, { mv_add_ovf, mv_sub_ovf, mul_ovf, cl20_ovf, unary_ovf, bilinear_ovf, bridge_ovf }, { _26_, _25_, _24_, _22_, _20_, _18_, _02_ });
  assign _22_ = | _21_;
  assign _24_ = opcode == 6'h03;
  function [31:0] _61_;
    input [31:0] a;
    input [223:0] b;
    input [6:0] s;
    casez (s) // synopsys parallel_case
      7'b??????1:
        _61_ = b[31:0];
      7'b?????1?:
        _61_ = b[63:32];
      7'b????1??:
        _61_ = b[95:64];
      7'b???1???:
        _61_ = b[127:96];
      7'b??1????:
        _61_ = b[159:128];
      7'b?1?????:
        _61_ = b[191:160];
      7'b1??????:
        _61_ = b[223:192];
      default:
        _61_ = a;
    endcase
  endfunction
  assign _01_[31:0] = _61_(32'd0, { ext_mv_sum_e12[31:0], ext_mv_sub_e12[31:0], cl20_prod[31:0], unary_res[31:0], bilinear_res[31:0], bridge_mv_out[31:0], bridge_mat_out[31:0] }, { _26_, _25_, _22_, _20_, _18_, _16_, bridge_dir });
  function [31:0] _62_;
    input [31:0] a;
    input [223:0] b;
    input [6:0] s;
    casez (s) // synopsys parallel_case
      7'b??????1:
        _62_ = b[31:0];
      7'b?????1?:
        _62_ = b[63:32];
      7'b????1??:
        _62_ = b[95:64];
      7'b???1???:
        _62_ = b[127:96];
      7'b??1????:
        _62_ = b[159:128];
      7'b?1?????:
        _62_ = b[191:160];
      7'b1??????:
        _62_ = b[223:192];
      default:
        _62_ = a;
    endcase
  endfunction
  assign _01_[63:32] = _62_(32'd0, { ext_mv_sum_e2[31:0], ext_mv_sub_e2[31:0], cl20_prod[63:32], unary_res[63:32], bilinear_res[63:32], bridge_mv_out[63:32], bridge_mat_out[63:32] }, { _26_, _25_, _22_, _20_, _18_, _16_, bridge_dir });
  assign _18_ = | _17_;
  assign _20_ = | _19_;
  function [31:0] _65_;
    input [31:0] a;
    input [223:0] b;
    input [6:0] s;
    casez (s) // synopsys parallel_case
      7'b??????1:
        _65_ = b[31:0];
      7'b?????1?:
        _65_ = b[63:32];
      7'b????1??:
        _65_ = b[95:64];
      7'b???1???:
        _65_ = b[127:96];
      7'b??1????:
        _65_ = b[159:128];
      7'b?1?????:
        _65_ = b[191:160];
      7'b1??????:
        _65_ = b[223:192];
      default:
        _65_ = a;
    endcase
  endfunction
  assign _01_[95:64] = _65_(32'd0, { ext_mv_sum_e1[31:0], ext_mv_sub_e1[31:0], cl20_prod[95:64], unary_res[95:64], bilinear_res[95:64], bridge_mv_out[95:64], bridge_mat_out[95:64] }, { _26_, _25_, _22_, _20_, _18_, _16_, bridge_dir });
  assign bridge_dir = opcode == 6'h13;
  assign _16_ = opcode == 6'h12;
  assign _17_[0] = opcode == 6'h09;
  assign _19_[0] = opcode == 6'h06;
  assign _21_[0] = opcode == 6'h05;
  assign _21_[1] = opcode == 6'h11;
  assign _25_ = opcode == 6'h02;
  assign _26_ = opcode == 6'h01;
  assign comb_comparison = _23_ ? _03_ : 1'h0;
  assign _23_ = opcode == 6'h04;
  function [2:0] _76_;
    input [2:0] a;
    input [11:0] b;
    input [3:0] s;
    casez (s) // synopsys parallel_case
      4'b???1:
        _76_ = b[2:0];
      4'b??1?:
        _76_ = b[5:3];
      4'b?1??:
        _76_ = b[8:6];
      4'b1???:
        _76_ = b[11:9];
      default:
        _76_ = a;
    endcase
  endfunction
  assign bilinear_sel = _76_(3'h0, 12'h29c, { _17_[1], _17_[2], _17_[3], _17_[4] });
  assign _17_[4] = opcode == 6'h10;
  assign _17_[3] = opcode == 6'h0c;
  assign _17_[2] = opcode == 6'h0b;
  assign _17_[1] = opcode == 6'h0a;
  function [2:0] _81_;
    input [2:0] a;
    input [14:0] b;
    input [4:0] s;
    casez (s) // synopsys parallel_case
      5'b????1:
        _81_ = b[2:0];
      5'b???1?:
        _81_ = b[5:3];
      5'b??1??:
        _81_ = b[8:6];
      5'b?1???:
        _81_ = b[11:9];
      5'b1????:
        _81_ = b[14:12];
      default:
        _81_ = a;
    endcase
  endfunction
  assign unary_sel = _81_(3'h0, 15'h14e5, { _19_[1], _19_[2], _19_[3], _19_[4], _19_[5] });
  assign _19_[5] = opcode == 6'h0f;
  assign _19_[4] = opcode == 6'h0e;
  assign _19_[3] = opcode == 6'h0d;
  assign _19_[2] = opcode == 6'h08;
  assign _19_[1] = opcode == 6'h07;
  assign ext_mv_sub_s = { operand_a[127], operand_a[127:96] } - { operand_b[127], operand_b[127:96] };
  assign ext_mv_sub_e1 = { operand_a[95], operand_a[95:64] } - { operand_b[95], operand_b[95:64] };
  assign ext_mv_sub_e2 = { operand_a[63], operand_a[63:32] } - { operand_b[63], operand_b[63:32] };
  assign ext_mv_sub_e12 = { operand_a[31], operand_a[31:0] } - { operand_b[31], operand_b[31:0] };
  assign _27_ = _03_ ? 32'd65536 : 32'd0;
  \$paramod$379ecd25f1665ab0d213a7b716ca7b69b1369608\geo_fixed_arith  u_arith (
    .a(operand_a[127:96]),
    .add_overflow(add_ovf),
    .b(operand_b[127:96]),
    .diff(arith_diff),
    .eq(cmp_eq),
    .gt(cmp_gt),
    .lt(cmp_lt),
    .mul_overflow(mul_ovf),
    .prod(arith_prod),
    .sub_overflow(sub_ovf),
    .sum(arith_sum)
  );
  \$paramod$379ecd25f1665ab0d213a7b716ca7b69b1369608\geo_bilinear_ops  u_bilinear (
    .a_e1(operand_a[95:64]),
    .a_e12(operand_a[31:0]),
    .a_e2(operand_a[63:32]),
    .a_s(operand_a[127:96]),
    .b_e1(operand_b[95:64]),
    .b_e12(operand_b[31:0]),
    .b_e2(operand_b[63:32]),
    .b_s(operand_b[127:96]),
    .op_sel(bilinear_sel),
    .out_e1(bilinear_res[95:64]),
    .out_e12(bilinear_res[31:0]),
    .out_e2(bilinear_res[63:32]),
    .out_s(bilinear_res[127:96]),
    .overflow(bilinear_ovf)
  );
  \$paramod\geo_matrix_bridge\WIDTH=s32'00000000000000000000000000100000  u_bridge (
    .direction(bridge_dir),
    .mat_a(operand_a[127:96]),
    .mat_b(operand_a[95:64]),
    .mat_c(operand_a[63:32]),
    .mat_d(operand_a[31:0]),
    .mv_e1(operand_a[95:64]),
    .mv_e12(operand_a[31:0]),
    .mv_e2(operand_a[63:32]),
    .mv_s(operand_a[127:96]),
    .out_mat_a(bridge_mat_out[127:96]),
    .out_mat_b(bridge_mat_out[95:64]),
    .out_mat_c(bridge_mat_out[63:32]),
    .out_mat_d(bridge_mat_out[31:0]),
    .out_mv_e1(bridge_mv_out[95:64]),
    .out_mv_e12(bridge_mv_out[31:0]),
    .out_mv_e2(bridge_mv_out[63:32]),
    .out_mv_s(bridge_mv_out[127:96]),
    .overflow(bridge_ovf)
  );
  \$paramod$379ecd25f1665ab0d213a7b716ca7b69b1369608\geo_cl20_multivector  u_cl20 (
    .a_e1(operand_a[95:64]),
    .a_e12(operand_a[31:0]),
    .a_e2(operand_a[63:32]),
    .a_s(operand_a[127:96]),
    .b_e1(operand_b[95:64]),
    .b_e12(operand_b[31:0]),
    .b_e2(operand_b[63:32]),
    .b_s(operand_b[127:96]),
    .overflow(cl20_ovf),
    .y_e1(cl20_prod[95:64]),
    .y_e12(cl20_prod[31:0]),
    .y_e2(cl20_prod[63:32]),
    .y_s(cl20_prod[127:96])
  );
  \$paramod\geo_unary_ops\WIDTH=s32'00000000000000000000000000100000  u_unary (
    .in_e1(operand_a[95:64]),
    .in_e12(operand_a[31:0]),
    .in_e2(operand_a[63:32]),
    .in_s(operand_a[127:96]),
    .op_sel(unary_sel),
    .out_e1(unary_res[95:64]),
    .out_e12(unary_res[31:0]),
    .out_e2(unary_res[63:32]),
    .out_s(unary_res[127:96]),
    .overflow(unary_ovf)
  );
  assign sub_e12_trunc = ext_mv_sub_e12[31:0];
  assign sub_e1_trunc = ext_mv_sub_e1[31:0];
  assign sub_e2_trunc = ext_mv_sub_e2[31:0];
  assign sub_s_trunc = ext_mv_sub_s[31:0];
  assign sum_e12_trunc = ext_mv_sum_e12[31:0];
  assign sum_e1_trunc = ext_mv_sum_e1[31:0];
  assign sum_e2_trunc = ext_mv_sum_e2[31:0];
  assign sum_s_trunc = ext_mv_sum_s[31:0];
endmodule
