#!/usr/bin/env python3
"""MAPEOGEO Foundation Backfill: Source Ingestion Module.

Extracts curated primitive and elementary mathematical declarations across 8 foundational layers:
  1. Logic & Proofs
  2. Set Theory
  3. Relations & Functions
  4. Number Systems
  5. Elementary Arithmetic & Algebra
  6. Order, Metrics & Sequences
  7. Euclidean Geometry & Trigonometry
  8. Elementary Calculus

Source attribution: Standard open foundational mathematical texts and definitions
  (Halmos 'Naive Set Theory', Enderton 'Elements of Set Theory', Birkhoff & MacLane
   'A Survey of Modern Algebra', Apostol 'Calculus Vol 1', Euclid/Hilbert 'Foundations of Geometry',
   Gallier 'Discrete Mathematics and Foundations').

Zero-prose persistence policy:
- Mathematical text is parsed strictly in memory.
- Output dictionaries store ONLY metadata: node_id, source_id, label, decl_type, chapter_section,
  statement_sha256, char_count, structural_refs, representation_profile.
- No copyrighted prose is persisted to disk in graph artifacts.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

SOURCE_ID = "FOUNDATION_MATHEMATICS_BASE"
STAGE = "foundation"

FORBIDDEN_PERSISTED_KEYS = {"statement_text", "proof_text", "source_prose", "page_image"}

# Detector Bank Keywords for Foundation candidates
FOUNDATION_EO_KEYWORDS = {
    "boolean_logic_evaluator": re.compile(r"\btruth table\b|\bboolean\b|\bmodus ponens\b|\bconjunction\b|\bdisjunction\b|\bnegation\b", re.IGNORECASE),
    "set_indicator_operator": re.compile(r"\bunion\b|\bintersection\b|\bcomplement\b|\bset difference\b|\bcartesian product\b|\bpower set\b", re.IGNORECASE),
    "relation_quotient_operator": re.compile(r"\bequivalence relation\b|\bequivalence class\b|\bquotient set\b|\bpartition\b|\bpartial order\b", re.IGNORECASE),
    "function_composition_operator": re.compile(r"\bfunction composition\b|\binjective\b|\bsurjective\b|\bbijective\b|\binverse function\b", re.IGNORECASE),
    "peano_arithmetic_operator": re.compile(r"\bpeano\b|\binduction\b|\bdivisibility\b|\beuclidean division\b|\bprime\b", re.IGNORECASE),
    "field_algebra_evaluator": re.compile(r"\bfield axioms\b|\bgroup axioms\b|\bring\b|\bdistributive\b|\bassociative\b|\bcommutative\b|\bpolynomial\b|\bbinomial\b", re.IGNORECASE),
    "sequence_convergence_bound": re.compile(r"\bsequence limit\b|\bepsilon-N\b|\bcauchy sequence\b|\bmonotone convergence\b|\bseries sum\b|\bgeometric series\b", re.IGNORECASE),
    "euclidean_metric_evaluator": re.compile(r"\bdot product\b|\bdistance formula\b|\binner product\b|\bpythagorean\b|\bcauchy-schwarz\b", re.IGNORECASE),
    "trigonometric_evaluator": re.compile(r"\bsine\b|\bcosine\b|\btangent\b|\btrigonometric identity\b|\bunit circle\b|\bangle sum\b", re.IGNORECASE),
    "differential_calculus_operator": re.compile(r"\bdifference quotient\b|\bderivative\b|\bpower rule\b|\bproduct rule\b|\bchain rule\b|\bintermediate value\b|\bmean value\b", re.IGNORECASE),
    "integral_calculus_operator": re.compile(r"\briemann sum\b|\bdefinite integral\b|\bfundamental theorem of calculus\b|\bintegration by parts\b", re.IGNORECASE),
}

FOUNDATION_GEO_KEYWORDS = {
    "logical_truth_geometry": re.compile(r"\bvenn diagram\b|\btruth value\b|\btruth table\b|\bvaluation\b|\bpropositional lattice\b|\bboolean algebra\b|\bboolean\b", re.IGNORECASE),
    "set_universe_topology": re.compile(r"\bopen set\b|\bneighborhood\b|\bsubset lattice\b|\bpower set\b|\bcoordinate plane\b|\buniversal set\b", re.IGNORECASE),
    "fiber_quotient_geometry": re.compile(r"\bfiber\b|\bpreimage\b|\bprojection\b|\bquotient space\b|\bquotient set\b|\bfoliation\b", re.IGNORECASE),
    "number_line_geometry": re.compile(r"\breal line\b|\bdedekind cut\b|\bcomplex plane\b|\bnumber axis\b|\binterval\b|\bpolar\b", re.IGNORECASE),
    "algebraic_variety_geometry": re.compile(r"\bpolynomial zero\b|\broot\b|\bparabola\b|\bcurve\b|\balgebraic set\b", re.IGNORECASE),
    "metric_ball_geometry": re.compile(r"\bopen ball\b|\bmetric neighborhood\b|\binterval \([a-z0-9, -]+\)\b|\bbounded set\b", re.IGNORECASE),
    "euclidean_space_geometry": re.compile(r"\beuclidean space\b|\br\^2\b|\br\^n\b|\bplane\b|\bvector\b|\bangle\b|\btriangle\b|\bcircle\b", re.IGNORECASE),
    "tangent_slope_area_geometry": re.compile(r"\btangent line\b|\bslope\b|\barea under curve\b|\bsecant line\b|\bextrema\b|\bconcavity\b", re.IGNORECASE),
}

REPRESENTATION_KINDS = {
    "abstract": re.compile(r"\baxiom\b|\bdefinition\b|\bproposition\b|\btheorem\b|\bset\b|\brelation\b|\bfield\b|\bgroup\b|\bspace\b", re.IGNORECASE),
    "algebraic": re.compile(r"\boperation\b|\bequation\b|\bassociative\b|\bdistributive\b|\bpolynomial\b|\bbinomial\b|\baddition\b|\bmultiplication\b|\bgroup\b", re.IGNORECASE),
    "geometric": re.compile(r"\bcircle\b|\bplane\b|\bline\b|\bangle\b|\btriangle\b|\barea\b|\bdistance\b|\bvector\b|\bslope\b|\binterval\b|\bball\b", re.IGNORECASE),
    "computational": re.compile(r"\balgorithm\b|\bcalculation\b|\bevaluation\b|\bformula\b|\bsum\b|\bquotient\b|\bapproximation\b|\bderivative\b|\bintegral\b", re.IGNORECASE),
    "applied": re.compile(r"\brate of change\b|\bmotion\b|\bphysics\b|\boptimization\b|\bcoordinates\b|\bmeasurement\b", re.IGNORECASE),
    "formal": re.compile(r"\bproof\b|\binduction\b|\bcontradiction\b|\bpeano\b|\bdedekind\b|\blean\b|\bformal\b", re.IGNORECASE),
}


@dataclass
class FoundationDeclaration:
    node_id: str
    source_id: str
    label: str
    decl_type: str
    chapter_section: str
    statement_sha256: str
    char_count: int
    layer: str
    structural_refs: list[str] = field(default_factory=list)
    representation_profile: dict[str, Any] = field(default_factory=dict)
    node_type: str = "SOURCE_DECLARATION"

    def to_dict(self) -> dict[str, Any]:
        d = asdict(self)
        for forbidden in FORBIDDEN_PERSISTED_KEYS:
            d.pop(forbidden, None)
        return d


def compute_sha256(text: str) -> str:
    return hashlib.sha256(text.strip().encode("utf-8")).hexdigest()


def detect_foundation_representation_profile(text: str, title: str) -> dict[str, Any]:
    full_text = f"{title}\n{text}"
    eo_tags = [tag for tag, pat in FOUNDATION_EO_KEYWORDS.items() if pat.search(full_text)]
    geo_tags = [tag for tag, pat in FOUNDATION_GEO_KEYWORDS.items() if pat.search(full_text)]

    if eo_tags and geo_tags:
        direct_status = "DUAL_DIRECT"
    elif eo_tags:
        direct_status = "EO_ONLY_DIRECT"
    elif geo_tags:
        direct_status = "GEO_ONLY_DIRECT"
    else:
        direct_status = "THEORETIC_DIRECT"

    rep_kinds = [k for k, pat in REPRESENTATION_KINDS.items() if pat.search(full_text)]
    if not rep_kinds:
        rep_kinds = ["abstract"]

    return {
        "direct_status": direct_status,
        "eo_tags": eo_tags,
        "geo_tags": geo_tags,
        "representation_kinds": rep_kinds,
        "diversity_count": len(rep_kinds),
    }


def generate_foundation_declarations() -> list[FoundationDeclaration]:
    """Generate curated, source-attributed foundational declarations across 8 layers.

    All mathematical statements are parsed strictly in memory and hashed with SHA-256.
    Zero prose text is persisted.
    """
    raw_declarations: list[dict[str, Any]] = [
        # =========================================================================
        # LAYER 1: LOGIC & PROOFS (20 Declarations)
        # =========================================================================
        {
            "node_id": "srcdecl:foundation:logic:proposition",
            "label": "Definition of Proposition / Statement",
            "decl_type": "DEFINITION",
            "layer": "logic",
            "chapter_section": "Logic §1.1",
            "structural_refs": [],
            "text": "A proposition is a declarative statement that is either strictly true or strictly false, but not both.",
        },
        {
            "node_id": "srcdecl:foundation:logic:negation",
            "label": "Definition of Logical Negation (NOT)",
            "decl_type": "DEFINITION",
            "layer": "logic",
            "chapter_section": "Logic §1.2",
            "structural_refs": ["srcdecl:foundation:logic:proposition"],
            "text": "Given proposition P, its negation not-P (¬P) is true if and only if P is false.",
        },
        {
            "node_id": "srcdecl:foundation:logic:conjunction",
            "label": "Definition of Logical Conjunction (AND)",
            "decl_type": "DEFINITION",
            "layer": "logic",
            "chapter_section": "Logic §1.2",
            "structural_refs": ["srcdecl:foundation:logic:proposition"],
            "text": "Given propositions P and Q, the conjunction P and Q (P ∧ Q) is true if and only if both P and Q are true.",
        },
        {
            "node_id": "srcdecl:foundation:logic:disjunction",
            "label": "Definition of Logical Disjunction (OR)",
            "decl_type": "DEFINITION",
            "layer": "logic",
            "chapter_section": "Logic §1.2",
            "structural_refs": ["srcdecl:foundation:logic:proposition"],
            "text": "Given propositions P and Q, the disjunction P or Q (P ∨ Q) is true if at least one of P or Q is true, and false only when both are false.",
        },
        {
            "node_id": "srcdecl:foundation:logic:implication",
            "label": "Definition of Material Implication (Conditional)",
            "decl_type": "DEFINITION",
            "layer": "logic",
            "chapter_section": "Logic §1.3",
            "structural_refs": ["srcdecl:foundation:logic:proposition", "srcdecl:foundation:logic:negation", "srcdecl:foundation:logic:disjunction"],
            "text": "The conditional statement P implies Q (P => Q) is false if and only if P is true and Q is false. Logically equivalent to (¬P ∨ Q).",
        },
        {
            "node_id": "srcdecl:foundation:logic:biconditional",
            "label": "Definition of Logical Equivalence (Biconditional)",
            "decl_type": "DEFINITION",
            "layer": "logic",
            "chapter_section": "Logic §1.3",
            "structural_refs": ["srcdecl:foundation:logic:implication", "srcdecl:foundation:logic:conjunction"],
            "text": "The biconditional statement P if and only if Q (P <=> Q) is true when P and Q have identical truth values; equivalent to (P => Q) ∧ (Q => P).",
        },
        {
            "node_id": "srcdecl:foundation:logic:truth_table",
            "label": "Truth Table Functional Semantics",
            "decl_type": "DEFINITION",
            "layer": "logic",
            "chapter_section": "Logic §1.4",
            "structural_refs": ["srcdecl:foundation:logic:conjunction", "srcdecl:foundation:logic:disjunction", "srcdecl:foundation:logic:negation"],
            "text": "A truth table specifies the output truth value of a compound boolean proposition for all possible truth value assignments to its constituent atomic propositions.",
        },
        {
            "node_id": "srcdecl:foundation:logic:tautology",
            "label": "Definition of Tautology and Contradiction",
            "decl_type": "DEFINITION",
            "layer": "logic",
            "chapter_section": "Logic §1.4",
            "structural_refs": ["srcdecl:foundation:logic:truth_table"],
            "text": "A compound proposition is a tautology if it evaluates to true under all truth assignments, and a contradiction if it evaluates to false under all truth assignments.",
        },
        {
            "node_id": "srcdecl:foundation:logic:de_morgan_logic",
            "label": "De Morgan's Laws for Propositional Logic",
            "decl_type": "THEOREM",
            "layer": "logic",
            "chapter_section": "Logic §1.5",
            "structural_refs": ["srcdecl:foundation:logic:negation", "srcdecl:foundation:logic:conjunction", "srcdecl:foundation:logic:disjunction"],
            "text": "For propositions P and Q: ¬(P ∧ Q) <=> (¬P ∨ ¬Q), and ¬(P ∨ Q) <=> (¬P ∧ ¬Q).",
        },
        {
            "node_id": "srcdecl:foundation:logic:modus_ponens",
            "label": "Rule of Inference: Modus Ponens",
            "decl_type": "THEOREM",
            "layer": "logic",
            "chapter_section": "Logic §1.6",
            "structural_refs": ["srcdecl:foundation:logic:implication"],
            "text": "From premise P and conditional premise (P => Q), one validly infers conclusion Q. That is, (P ∧ (P => Q)) => Q is a tautology.",
        },
        {
            "node_id": "srcdecl:foundation:logic:modus_tollens",
            "label": "Rule of Inference: Modus Tollens",
            "decl_type": "THEOREM",
            "layer": "logic",
            "chapter_section": "Logic §1.6",
            "structural_refs": ["srcdecl:foundation:logic:implication", "srcdecl:foundation:logic:negation"],
            "text": "From premise ¬Q and conditional premise (P => Q), one validly infers conclusion ¬P. That is, (¬Q ∧ (P => Q)) => ¬P is a tautology.",
        },
        {
            "node_id": "srcdecl:foundation:logic:direct_proof",
            "label": "Direct Proof Method",
            "decl_type": "DEFINITION",
            "layer": "logic",
            "chapter_section": "Logic §1.7",
            "structural_refs": ["srcdecl:foundation:logic:implication", "srcdecl:foundation:logic:modus_ponens"],
            "text": "A direct proof of P => Q assumes premise P is true and constructs a sequence of deductive steps leading to conclusion Q.",
        },
        {
            "node_id": "srcdecl:foundation:logic:contrapositive_proof",
            "label": "Contrapositive Equivalence and Proof Method",
            "decl_type": "THEOREM",
            "layer": "logic",
            "chapter_section": "Logic §1.7",
            "structural_refs": ["srcdecl:foundation:logic:implication", "srcdecl:foundation:logic:negation"],
            "text": "The conditional (P => Q) is logically equivalent to its contrapositive (¬Q => ¬P). Proof by contraposition proves P => Q by establishing ¬Q => ¬P.",
        },
        {
            "node_id": "srcdecl:foundation:logic:proof_by_contradiction",
            "label": "Proof by Contradiction (Reductio ad Absurdum)",
            "decl_type": "THEOREM",
            "layer": "logic",
            "chapter_section": "Logic §1.8",
            "structural_refs": ["srcdecl:foundation:logic:negation", "srcdecl:foundation:logic:tautology"],
            "text": "To prove proposition P, assume ¬P and deduce a contradiction (R ∧ ¬R); conclude P must be true. Equivalently, (¬P => False) => P.",
        },
        {
            "node_id": "srcdecl:foundation:logic:universal_quantifier",
            "label": "Definition of Universal Quantifier (FOR ALL)",
            "decl_type": "DEFINITION",
            "layer": "logic",
            "chapter_section": "Logic §1.9",
            "structural_refs": ["srcdecl:foundation:logic:proposition"],
            "text": "The universal quantification ∀x P(x) asserts predicate P(x) is true for all elements x in universe of discourse U.",
        },
        {
            "node_id": "srcdecl:foundation:logic:existential_quantifier",
            "label": "Definition of Existential Quantifier (THERE EXISTS)",
            "decl_type": "DEFINITION",
            "layer": "logic",
            "chapter_section": "Logic §1.9",
            "structural_refs": ["srcdecl:foundation:logic:proposition"],
            "text": "The existential quantification ∃x P(x) asserts there exists at least one element x in universe U such that P(x) is true.",
        },
        {
            "node_id": "srcdecl:foundation:logic:quantifier_negation",
            "label": "Quantifier Negation Dualities",
            "decl_type": "THEOREM",
            "layer": "logic",
            "chapter_section": "Logic §1.9",
            "structural_refs": ["srcdecl:foundation:logic:universal_quantifier", "srcdecl:foundation:logic:existential_quantifier", "srcdecl:foundation:logic:negation"],
            "text": "For predicate P(x): ¬(∀x P(x)) <=> ∃x ¬P(x), and ¬(∃x P(x)) <=> ∀x ¬P(x).",
        },
        {
            "node_id": "srcdecl:foundation:logic:distributive_logic",
            "label": "Distributive Laws of Propositional Logic",
            "decl_type": "THEOREM",
            "layer": "logic",
            "chapter_section": "Logic §1.5",
            "structural_refs": ["srcdecl:foundation:logic:conjunction", "srcdecl:foundation:logic:disjunction"],
            "text": "P ∧ (Q ∨ R) <=> (P ∧ Q) ∨ (P ∧ R), and P ∨ (Q ∧ R) <=> (P ∨ Q) ∧ (P ∨ R).",
        },
        {
            "node_id": "srcdecl:foundation:logic:law_of_excluded_middle",
            "label": "Law of Excluded Middle and Non-Contradiction",
            "decl_type": "AXIOM",
            "layer": "logic",
            "chapter_section": "Logic §1.1",
            "structural_refs": ["srcdecl:foundation:logic:negation", "srcdecl:foundation:logic:disjunction", "srcdecl:foundation:logic:conjunction"],
            "text": "For any proposition P, (P ∨ ¬P) is a tautology (Law of Excluded Middle), and ¬(P ∧ ¬P) is a tautology (Principle of Non-Contradiction).",
        },
        {
            "node_id": "srcdecl:foundation:logic:hypothetical_syllogism",
            "label": "Rule of Hypothetical Syllogism (Transitivity of Implication)",
            "decl_type": "THEOREM",
            "layer": "logic",
            "chapter_section": "Logic §1.6",
            "structural_refs": ["srcdecl:foundation:logic:implication"],
            "text": "((P => Q) ∧ (Q => R)) => (P => R) is a valid deductive inference rule and tautology.",
        },

        # =========================================================================
        # LAYER 2: SET THEORY (22 Declarations)
        # =========================================================================
        {
            "node_id": "srcdecl:foundation:set:element_membership",
            "label": "Set Membership and Extensionality",
            "decl_type": "DEFINITION",
            "layer": "sets",
            "chapter_section": "Sets §2.1",
            "structural_refs": [],
            "text": "A set is a collection of distinct mathematical objects; x in A denotes membership. Two sets A and B are equal (A = B) iff ∀x (x in A <=> x in B).",
        },
        {
            "node_id": "srcdecl:foundation:set:empty_set",
            "label": "Definition of the Empty Set",
            "decl_type": "DEFINITION",
            "layer": "sets",
            "chapter_section": "Sets §2.1",
            "structural_refs": ["srcdecl:foundation:set:element_membership"],
            "text": "The empty set ∅ is the unique set containing no elements: ∀x (x not-in ∅).",
        },
        {
            "node_id": "srcdecl:foundation:set:subset_definition",
            "label": "Definition of Subset and Superset",
            "decl_type": "DEFINITION",
            "layer": "sets",
            "chapter_section": "Sets §2.2",
            "structural_refs": ["srcdecl:foundation:set:element_membership"],
            "text": "A is a subset of B (A ⊆ B) iff every element of A belongs to B: ∀x (x in A => x in B).",
        },
        {
            "node_id": "srcdecl:foundation:set:proper_subset",
            "label": "Definition of Proper Subset",
            "decl_type": "DEFINITION",
            "layer": "sets",
            "chapter_section": "Sets §2.2",
            "structural_refs": ["srcdecl:foundation:set:subset_definition"],
            "text": "A is a proper subset of B (A ⊂ B) iff A ⊆ B and A ≠ B.",
        },
        {
            "node_id": "srcdecl:foundation:set:union",
            "label": "Definition of Set Union",
            "decl_type": "DEFINITION",
            "layer": "sets",
            "chapter_section": "Sets §2.3",
            "structural_refs": ["srcdecl:foundation:set:element_membership"],
            "text": "The union A ∪ B is the set of all elements in A or in B: A ∪ B = {x | x in A ∨ x in B}.",
        },
        {
            "node_id": "srcdecl:foundation:set:intersection",
            "label": "Definition of Set Intersection",
            "decl_type": "DEFINITION",
            "layer": "sets",
            "chapter_section": "Sets §2.3",
            "structural_refs": ["srcdecl:foundation:set:element_membership"],
            "text": "The intersection A ∩ B is the set of all elements belonging to both A and B: A ∩ B = {x | x in A ∧ x in B}.",
        },
        {
            "node_id": "srcdecl:foundation:set:set_difference",
            "label": "Definition of Set Difference (Relative Complement)",
            "decl_type": "DEFINITION",
            "layer": "sets",
            "chapter_section": "Sets §2.3",
            "structural_refs": ["srcdecl:foundation:set:element_membership"],
            "text": "The set difference A \\ B (or A - B) is the set of elements in A that are not in B: A \\ B = {x | x in A ∧ x not-in B}.",
        },
        {
            "node_id": "srcdecl:foundation:set:complement",
            "label": "Definition of Absolute Complement",
            "decl_type": "DEFINITION",
            "layer": "sets",
            "chapter_section": "Sets §2.3",
            "structural_refs": ["srcdecl:foundation:set:set_difference"],
            "text": "With respect to universal set U, the complement A^c (or U \\ A) is the set of all elements in U not in A: A^c = {x in U | x not-in A}.",
        },
        {
            "node_id": "srcdecl:foundation:set:power_set",
            "label": "Definition of Power Set",
            "decl_type": "DEFINITION",
            "layer": "sets",
            "chapter_section": "Sets §2.4",
            "structural_refs": ["srcdecl:foundation:set:subset_definition"],
            "text": "The power set P(X) of a set X is the set of all subsets of X: P(X) = {S | S ⊆ X}. If |X| = n, then |P(X)| = 2^n.",
        },
        {
            "node_id": "srcdecl:foundation:set:ordered_pair",
            "label": "Definition of Kuratowski Ordered Pair",
            "decl_type": "DEFINITION",
            "layer": "sets",
            "chapter_section": "Sets §2.5",
            "structural_refs": ["srcdecl:foundation:set:element_membership"],
            "text": "The ordered pair (a, b) is defined set-theoretically as {{a}, {a, b}}. Property: (a, b) = (c, d) iff a = c and b = d.",
        },
        {
            "node_id": "srcdecl:foundation:set:cartesian_product",
            "label": "Definition of Cartesian Product",
            "decl_type": "DEFINITION",
            "layer": "sets",
            "chapter_section": "Sets §2.5",
            "structural_refs": ["srcdecl:foundation:set:ordered_pair"],
            "text": "The Cartesian product A × B is the set of all ordered pairs (a, b) with a in A and b in B: A × B = {(a, b) | a in A, b in B}.",
        },
        {
            "node_id": "srcdecl:foundation:set:disjoint_sets",
            "label": "Definition of Disjoint Sets",
            "decl_type": "DEFINITION",
            "layer": "sets",
            "chapter_section": "Sets §2.3",
            "structural_refs": ["srcdecl:foundation:set:intersection", "srcdecl:foundation:set:empty_set"],
            "text": "Two sets A and B are disjoint iff their intersection is empty: A ∩ B = ∅. A family is pairwise disjoint if A_i ∩ A_j = ∅ for all i ≠ j.",
        },
        {
            "node_id": "srcdecl:foundation:set:set_partition",
            "label": "Definition of Set Partition",
            "decl_type": "DEFINITION",
            "layer": "sets",
            "chapter_section": "Sets §2.6",
            "structural_refs": ["srcdecl:foundation:set:disjoint_sets", "srcdecl:foundation:set:union"],
            "text": "A partition of set X is a collection P of non-empty pairwise disjoint subsets of X whose union is X: ∪_{S in P} S = X.",
        },
        {
            "node_id": "srcdecl:foundation:set:de_morgan_sets",
            "label": "De Morgan's Laws for Sets",
            "decl_type": "THEOREM",
            "layer": "sets",
            "chapter_section": "Sets §2.3",
            "structural_refs": ["srcdecl:foundation:set:complement", "srcdecl:foundation:set:union", "srcdecl:foundation:set:intersection"],
            "text": "For subsets A, B of U: (A ∪ B)^c = A^c ∩ B^c, and (A ∩ B)^c = A^c ∪ B^c.",
        },
        {
            "node_id": "srcdecl:foundation:set:distributive_laws_sets",
            "label": "Distributive Laws of Set Operations",
            "decl_type": "THEOREM",
            "layer": "sets",
            "chapter_section": "Sets §2.3",
            "structural_refs": ["srcdecl:foundation:set:union", "srcdecl:foundation:set:intersection"],
            "text": "A ∩ (B ∪ C) = (A ∩ B) ∪ (A ∩ C), and A ∪ (B ∩ C) = (A ∪ B) ∩ (A ∪ C).",
        },
        {
            "node_id": "srcdecl:foundation:set:inclusion_exclusion_finite",
            "label": "Principle of Inclusion-Exclusion (Finite Sets)",
            "decl_type": "THEOREM",
            "layer": "sets",
            "chapter_section": "Sets §2.7",
            "structural_refs": ["srcdecl:foundation:set:union", "srcdecl:foundation:set:intersection"],
            "text": "For finite sets A and B: |A ∪ B| = |A| + |B| - |A ∩ B|.",
        },
        {
            "node_id": "srcdecl:foundation:set:arbitrary_union_intersection",
            "label": "Arbitrary (Indexed) Union and Intersection",
            "decl_type": "DEFINITION",
            "layer": "sets",
            "chapter_section": "Sets §2.8",
            "structural_refs": ["srcdecl:foundation:set:union", "srcdecl:foundation:set:intersection"],
            "text": "For an indexed family of sets {A_i}_{i in I}: ∪_{i in I} A_i = {x | ∃i in I (x in A_i)} and ∩_{i in I} A_i = {x | ∀i in I (x in A_i)}.",
        },
        {
            "node_id": "srcdecl:foundation:set:axiom_of_specification",
            "label": "Axiom Schema of Specification (Separation)",
            "decl_type": "AXIOM",
            "layer": "sets",
            "chapter_section": "Sets §2.1",
            "structural_refs": ["srcdecl:foundation:set:element_membership"],
            "text": "Given a set X and predicate P(x), there exists a set Y = {x in X | P(x)} consisting of precisely those elements of X satisfying P.",
        },
        {
            "node_id": "srcdecl:foundation:set:indicator_function",
            "label": "Definition of Characteristic / Indicator Function",
            "decl_type": "DEFINITION",
            "layer": "sets",
            "chapter_section": "Sets §2.9",
            "structural_refs": ["srcdecl:foundation:set:subset_definition"],
            "text": "The indicator function 1_A: X -> {0, 1} of subset A ⊆ X is defined by 1_A(x) = 1 if x in A, and 0 if x not-in A.",
        },
        {
            "node_id": "srcdecl:foundation:set:indicator_algebra",
            "label": "Algebra of Indicator Functions",
            "decl_type": "THEOREM",
            "layer": "sets",
            "chapter_section": "Sets §2.9",
            "structural_refs": ["srcdecl:foundation:set:indicator_function", "srcdecl:foundation:set:intersection", "srcdecl:foundation:set:union", "srcdecl:foundation:set:complement"],
            "text": "1_{A ∩ B} = 1_A · 1_B, 1_{A^c} = 1 - 1_A, and 1_{A ∪ B} = 1_A + 1_B - 1_A · 1_B.",
        },
        {
            "node_id": "srcdecl:foundation:set:axiom_of_extensionality",
            "label": "Axiom of Extensionality",
            "decl_type": "AXIOM",
            "layer": "sets",
            "chapter_section": "Sets §2.1",
            "structural_refs": ["srcdecl:foundation:set:element_membership"],
            "text": "If two sets have exactly the same elements, then they are equal: (∀x (x in A <=> x in B)) => A = B.",
        },
        {
            "node_id": "srcdecl:foundation:set:axiom_of_choice_primitive",
            "label": "Axiom of Choice (Elementary Formulation)",
            "decl_type": "AXIOM",
            "layer": "sets",
            "chapter_section": "Sets §2.10",
            "structural_refs": ["srcdecl:foundation:set:cartesian_product", "srcdecl:foundation:set:empty_set"],
            "text": "For any non-empty collection of pairwise disjoint non-empty sets, there exists a choice set containing exactly one element from each set in the collection.",
        },

        # =========================================================================
        # LAYER 3: RELATIONS & FUNCTIONS (22 Declarations)
        # =========================================================================
        {
            "node_id": "srcdecl:foundation:rel:binary_relation",
            "label": "Definition of Binary Relation",
            "decl_type": "DEFINITION",
            "layer": "relations_functions",
            "chapter_section": "Relations §3.1",
            "structural_refs": ["srcdecl:foundation:set:cartesian_product"],
            "text": "A binary relation R from set X to set Y is a subset R ⊆ X × Y. We write x R y iff (x, y) in R.",
        },
        {
            "node_id": "srcdecl:foundation:rel:reflexive_relation",
            "label": "Definition of Reflexive Relation",
            "decl_type": "DEFINITION",
            "layer": "relations_functions",
            "chapter_section": "Relations §3.2",
            "structural_refs": ["srcdecl:foundation:rel:binary_relation"],
            "text": "A relation R on X is reflexive iff ∀x in X (x R x).",
        },
        {
            "node_id": "srcdecl:foundation:rel:symmetric_relation",
            "label": "Definition of Symmetric Relation",
            "decl_type": "DEFINITION",
            "layer": "relations_functions",
            "chapter_section": "Relations §3.2",
            "structural_refs": ["srcdecl:foundation:rel:binary_relation"],
            "text": "A relation R on X is symmetric iff ∀x, y in X (x R y => y R x).",
        },
        {
            "node_id": "srcdecl:foundation:rel:transitive_relation",
            "label": "Definition of Transitive Relation",
            "decl_type": "DEFINITION",
            "layer": "relations_functions",
            "chapter_section": "Relations §3.2",
            "structural_refs": ["srcdecl:foundation:rel:binary_relation"],
            "text": "A relation R on X is transitive iff ∀x, y, z in X ((x R y ∧ y R z) => x R z).",
        },
        {
            "node_id": "srcdecl:foundation:rel:antisymmetric_relation",
            "label": "Definition of Antisymmetric Relation",
            "decl_type": "DEFINITION",
            "layer": "relations_functions",
            "chapter_section": "Relations §3.2",
            "structural_refs": ["srcdecl:foundation:rel:binary_relation"],
            "text": "A relation R on X is antisymmetric iff ∀x, y in X ((x R y ∧ y R x) => x = y).",
        },
        {
            "node_id": "srcdecl:foundation:rel:equivalence_relation",
            "label": "Definition of Equivalence Relation",
            "decl_type": "DEFINITION",
            "layer": "relations_functions",
            "chapter_section": "Relations §3.3",
            "structural_refs": ["srcdecl:foundation:rel:reflexive_relation", "srcdecl:foundation:rel:symmetric_relation", "srcdecl:foundation:rel:transitive_relation"],
            "text": "A relation ~ on X is an equivalence relation iff it is reflexive, symmetric, and transitive.",
        },
        {
            "node_id": "srcdecl:foundation:rel:equivalence_class",
            "label": "Definition of Equivalence Class",
            "decl_type": "DEFINITION",
            "layer": "relations_functions",
            "chapter_section": "Relations §3.3",
            "structural_refs": ["srcdecl:foundation:rel:equivalence_relation"],
            "text": "Given equivalence relation ~ on X and x in X, the equivalence class of x is [x] = {y in X | y ~ x}.",
        },
        {
            "node_id": "srcdecl:foundation:rel:quotient_set",
            "label": "Definition of Quotient Set",
            "decl_type": "DEFINITION",
            "layer": "relations_functions",
            "chapter_section": "Relations §3.3",
            "structural_refs": ["srcdecl:foundation:rel:equivalence_class"],
            "text": "The quotient set X/~ is the set of all equivalence classes of elements of X: X/~ = {[x] | x in X}.",
        },
        {
            "node_id": "srcdecl:foundation:rel:fundamental_theorem_equivalence",
            "label": "Fundamental Theorem of Equivalence Relations",
            "decl_type": "THEOREM",
            "layer": "relations_functions",
            "chapter_section": "Relations §3.4",
            "structural_refs": ["srcdecl:foundation:rel:quotient_set", "srcdecl:foundation:set:set_partition"],
            "text": "Every equivalence relation on X induces a partition X/~ of X, and conversely every partition of X defines an equivalence relation.",
        },
        {
            "node_id": "srcdecl:foundation:rel:partial_order",
            "label": "Definition of Partial Order (Poset)",
            "decl_type": "DEFINITION",
            "layer": "relations_functions",
            "chapter_section": "Relations §3.5",
            "structural_refs": ["srcdecl:foundation:rel:reflexive_relation", "srcdecl:foundation:rel:antisymmetric_relation", "srcdecl:foundation:rel:transitive_relation"],
            "text": "A relation <= on X is a partial order iff it is reflexive, antisymmetric, and transitive. A set equipped with a partial order is a poset.",
        },
        {
            "node_id": "srcdecl:foundation:rel:total_order",
            "label": "Definition of Total Order",
            "decl_type": "DEFINITION",
            "layer": "relations_functions",
            "chapter_section": "Relations §3.5",
            "structural_refs": ["srcdecl:foundation:rel:partial_order"],
            "text": "A partial order <= on X is a total (or linear) order iff for all x, y in X, either x <= y or y <= x (totality/comparability).",
        },
        {
            "node_id": "srcdecl:foundation:rel:function_definition",
            "label": "Definition of Function / Mapping",
            "decl_type": "DEFINITION",
            "layer": "relations_functions",
            "chapter_section": "Functions §3.6",
            "structural_refs": ["srcdecl:foundation:rel:binary_relation"],
            "text": "A function f: X -> Y is a relation f ⊆ X × Y such that for every x in X there exists a unique y in Y with (x, y) in f; we write f(x) = y.",
        },
        {
            "node_id": "srcdecl:foundation:rel:domain_codomain_image",
            "label": "Domain, Codomain, and Range / Image",
            "decl_type": "DEFINITION",
            "layer": "relations_functions",
            "chapter_section": "Functions §3.6",
            "structural_refs": ["srcdecl:foundation:rel:function_definition"],
            "text": "For f: X -> Y, X is domain, Y is codomain, and image im(f) = f(X) = {f(x) | x in X} ⊆ Y.",
        },
        {
            "node_id": "srcdecl:foundation:rel:preimage_fiber",
            "label": "Preimage (Inverse Image) and Fiber",
            "decl_type": "DEFINITION",
            "layer": "relations_functions",
            "chapter_section": "Functions §3.6",
            "structural_refs": ["srcdecl:foundation:rel:function_definition"],
            "text": "For f: X -> Y and B ⊆ Y, the preimage f^{-1}(B) is {x in X | f(x) in B}. For y in Y, fiber over y is f^{-1}({y}).",
        },
        {
            "node_id": "srcdecl:foundation:rel:injective_function",
            "label": "Definition of Injective (One-to-One) Function",
            "decl_type": "DEFINITION",
            "layer": "relations_functions",
            "chapter_section": "Functions §3.7",
            "structural_refs": ["srcdecl:foundation:rel:function_definition"],
            "text": "f: X -> Y is injective iff ∀x_1, x_2 in X (f(x_1) = f(x_2) => x_1 = x_2).",
        },
        {
            "node_id": "srcdecl:foundation:rel:surjective_function",
            "label": "Definition of Surjective (Onto) Function",
            "decl_type": "DEFINITION",
            "layer": "relations_functions",
            "chapter_section": "Functions §3.7",
            "structural_refs": ["srcdecl:foundation:rel:function_definition", "srcdecl:foundation:rel:domain_codomain_image"],
            "text": "f: X -> Y is surjective iff im(f) = Y, i.e., ∀y in Y ∃x in X (f(x) = y).",
        },
        {
            "node_id": "srcdecl:foundation:rel:bijective_function",
            "label": "Definition of Bijective (One-to-One and Onto) Function",
            "decl_type": "DEFINITION",
            "layer": "relations_functions",
            "chapter_section": "Functions §3.7",
            "structural_refs": ["srcdecl:foundation:rel:injective_function", "srcdecl:foundation:rel:surjective_function"],
            "text": "f: X -> Y is bijective iff f is both injective and surjective.",
        },
        {
            "node_id": "srcdecl:foundation:rel:function_composition",
            "label": "Definition of Function Composition",
            "decl_type": "DEFINITION",
            "layer": "relations_functions",
            "chapter_section": "Functions §3.8",
            "structural_refs": ["srcdecl:foundation:rel:function_definition"],
            "text": "For f: X -> Y and g: Y -> Z, composite function g ∘ f: X -> Z is defined by (g ∘ f)(x) = g(f(x)).",
        },
        {
            "node_id": "srcdecl:foundation:rel:associativity_composition",
            "label": "Associativity of Function Composition",
            "decl_type": "THEOREM",
            "layer": "relations_functions",
            "chapter_section": "Functions §3.8",
            "structural_refs": ["srcdecl:foundation:rel:function_composition"],
            "text": "For f: X -> Y, g: Y -> Z, h: Z -> W, h ∘ (g ∘ f) = (h ∘ g) ∘ f.",
        },
        {
            "node_id": "srcdecl:foundation:rel:identity_function",
            "label": "Definition of Identity Function",
            "decl_type": "DEFINITION",
            "layer": "relations_functions",
            "chapter_section": "Functions §3.8",
            "structural_refs": ["srcdecl:foundation:rel:function_definition"],
            "text": "The identity function on set X is id_X: X -> X defined by id_X(x) = x for all x in X.",
        },
        {
            "node_id": "srcdecl:foundation:rel:inverse_function",
            "label": "Definition of Inverse Function",
            "decl_type": "DEFINITION",
            "layer": "relations_functions",
            "chapter_section": "Functions §3.9",
            "structural_refs": ["srcdecl:foundation:rel:function_composition", "srcdecl:foundation:rel:identity_function"],
            "text": "f: X -> Y has inverse g: Y -> X iff g ∘ f = id_X and f ∘ g = id_Y. We write g = f^{-1}.",
        },
        {
            "node_id": "srcdecl:foundation:rel:invertibility_criterion",
            "label": "Bijectivity and Invertibility Equivalence",
            "decl_type": "THEOREM",
            "layer": "relations_functions",
            "chapter_section": "Functions §3.9",
            "structural_refs": ["srcdecl:foundation:rel:bijective_function", "srcdecl:foundation:rel:inverse_function"],
            "text": "A function f: X -> Y has a two-sided inverse f^{-1}: Y -> X if and only if f is bijective.",
        },

        # =========================================================================
        # LAYER 4: NUMBER SYSTEMS (20 Declarations)
        # =========================================================================
        {
            "node_id": "srcdecl:foundation:num:peano_axioms_naturals",
            "label": "Peano Axioms for Natural Numbers",
            "decl_type": "AXIOM",
            "layer": "number_systems",
            "chapter_section": "Numbers §4.1",
            "structural_refs": [],
            "text": "The natural numbers N are defined by Peano axioms: 0 in N; successor function S: N -> N is injective; 0 is not in im(S); and induction axiom holds.",
        },
        {
            "node_id": "srcdecl:foundation:num:principle_induction",
            "label": "Principle of Mathematical Induction",
            "decl_type": "THEOREM",
            "layer": "number_systems",
            "chapter_section": "Numbers §4.1",
            "structural_refs": ["srcdecl:foundation:num:peano_axioms_naturals"],
            "text": "If P(0) is true, and ∀k in N (P(k) => P(k+1)), then P(n) is true for all n in N.",
        },
        {
            "node_id": "srcdecl:foundation:num:well_ordering_principle",
            "label": "Well-Ordering Principle of Natural Numbers",
            "decl_type": "THEOREM",
            "layer": "number_systems",
            "chapter_section": "Numbers §4.1",
            "structural_refs": ["srcdecl:foundation:num:principle_induction"],
            "text": "Every non-empty subset S ⊆ N contains a least element: ∃m in S ∀x in S (m <= x). Equivalent to induction.",
        },
        {
            "node_id": "srcdecl:foundation:num:integers_construction",
            "label": "Construction of Integers as Quotient of N × N",
            "decl_type": "DEFINITION",
            "layer": "number_systems",
            "chapter_section": "Numbers §4.2",
            "structural_refs": ["srcdecl:foundation:rel:quotient_set", "srcdecl:foundation:num:peano_axioms_naturals"],
            "text": "The ring of integers Z is constructed as quotient of N × N under equivalence relation (a, b) ~ (c, d) <=> a + d = b + c.",
        },
        {
            "node_id": "srcdecl:foundation:num:integer_divisibility",
            "label": "Definition of Divisibility in Integers",
            "decl_type": "DEFINITION",
            "layer": "number_systems",
            "chapter_section": "Numbers §4.2",
            "structural_refs": ["srcdecl:foundation:num:integers_construction"],
            "text": "For a, b in Z with a ≠ 0, a divides b (a | b) iff ∃k in Z such that b = a · k.",
        },
        {
            "node_id": "srcdecl:foundation:num:euclidean_division_algorithm",
            "label": "Euclidean Division Algorithm for Integers",
            "decl_type": "THEOREM",
            "layer": "number_systems",
            "chapter_section": "Numbers §4.2",
            "structural_refs": ["srcdecl:foundation:num:well_ordering_principle"],
            "text": "For integers a and b > 0, there exist unique integers q (quotient) and r (remainder) such that a = b · q + r with 0 <= r < b.",
        },
        {
            "node_id": "srcdecl:foundation:num:rational_numbers_construction",
            "label": "Construction of Rational Numbers as Field of Fractions",
            "decl_type": "DEFINITION",
            "layer": "number_systems",
            "chapter_section": "Numbers §4.3",
            "structural_refs": ["srcdecl:foundation:rel:quotient_set", "srcdecl:foundation:num:integers_construction"],
            "text": "The field of rational numbers Q is the quotient of Z × (Z \\ {0}) under (a, b) ~ (c, d) <=> a · d = b · c.",
        },
        {
            "node_id": "srcdecl:foundation:num:rational_density",
            "label": "Density of Rational Numbers in Real Line",
            "decl_type": "THEOREM",
            "layer": "number_systems",
            "chapter_section": "Numbers §4.3",
            "structural_refs": ["srcdecl:foundation:num:rational_numbers_construction"],
            "text": "Between any two distinct real numbers x < y, there exists a rational number q in Q such that x < q < y.",
        },
        {
            "node_id": "srcdecl:foundation:num:irrationality_sqrt_2",
            "label": "Existence of Irrationals: Irrationality of sqrt(2)",
            "decl_type": "THEOREM",
            "layer": "number_systems",
            "chapter_section": "Numbers §4.3",
            "structural_refs": ["srcdecl:foundation:num:rational_numbers_construction", "srcdecl:foundation:logic:proof_by_contradiction"],
            "text": "There is no rational number q in Q such that q^2 = 2. Thus sqrt(2) is irrational.",
        },
        {
            "node_id": "srcdecl:foundation:num:real_numbers_axioms",
            "label": "Axiomatic Definition of Real Numbers (Complete Ordered Field)",
            "decl_type": "AXIOM",
            "layer": "number_systems",
            "chapter_section": "Numbers §4.4",
            "structural_refs": ["srcdecl:foundation:num:rational_numbers_construction"],
            "text": "The real numbers R is the unique (up to isomorphism) complete ordered field containing Q as a subfield.",
        },
        {
            "node_id": "srcdecl:foundation:num:completeness_supremum",
            "label": "Completeness Property: Least Upper Bound Axiom",
            "decl_type": "AXIOM",
            "layer": "number_systems",
            "chapter_section": "Numbers §4.4",
            "structural_refs": ["srcdecl:foundation:num:real_numbers_axioms"],
            "text": "Every non-empty subset S ⊆ R that is bounded above has a least upper bound (supremum) in R: sup(S) in R.",
        },
        {
            "node_id": "srcdecl:foundation:num:dedekind_cut_construction",
            "label": "Dedekind Cut Construction of Real Numbers",
            "decl_type": "DEFINITION",
            "layer": "number_systems",
            "chapter_section": "Numbers §4.4",
            "structural_refs": ["srcdecl:foundation:num:rational_numbers_construction"],
            "text": "A Dedekind cut is a partition (A, B) of Q where A is non-empty, A ≠ Q, A is downward closed, and A has no maximum. R is the set of all cuts.",
        },
        {
            "node_id": "srcdecl:foundation:num:cauchy_sequence_reals",
            "label": "Cauchy Sequence Metric Completion Construction of R",
            "decl_type": "DEFINITION",
            "layer": "number_systems",
            "chapter_section": "Numbers §4.4",
            "structural_refs": ["srcdecl:foundation:rel:quotient_set", "srcdecl:foundation:num:rational_numbers_construction"],
            "text": "R is constructed as quotient of the ring of Cauchy sequences of rationals under null sequences (x_n - y_n -> 0).",
        },
        {
            "node_id": "srcdecl:foundation:num:archimedean_property",
            "label": "Archimedean Property of Real Numbers",
            "decl_type": "THEOREM",
            "layer": "number_systems",
            "chapter_section": "Numbers §4.4",
            "structural_refs": ["srcdecl:foundation:num:completeness_supremum"],
            "text": "For any positive real numbers x > 0 and y in R, there exists a natural number n in N such that n · x > y.",
        },
        {
            "node_id": "srcdecl:foundation:num:density_irrationals",
            "label": "Density of Irrational Numbers",
            "decl_type": "THEOREM",
            "layer": "number_systems",
            "chapter_section": "Numbers §4.4",
            "structural_refs": ["srcdecl:foundation:num:rational_density", "srcdecl:foundation:num:irrationality_sqrt_2"],
            "text": "Between any two distinct real numbers x < y, there exists an irrational number r in (R \\ Q) such that x < r < y.",
        },
        {
            "node_id": "srcdecl:foundation:num:complex_numbers_definition",
            "label": "Definition of Complex Numbers C",
            "decl_type": "DEFINITION",
            "layer": "number_systems",
            "chapter_section": "Numbers §4.5",
            "structural_refs": ["srcdecl:foundation:num:real_numbers_axioms", "srcdecl:foundation:set:cartesian_product"],
            "text": "The field of complex numbers C is R × R equipped with addition (a,b)+(c,d) = (a+c, b+d) and multiplication (a,b)·(c,d) = (ac-bd, ad+bc).",
        },
        {
            "node_id": "srcdecl:foundation:num:imaginary_unit",
            "label": "Definition of Imaginary Unit i",
            "decl_type": "DEFINITION",
            "layer": "number_systems",
            "chapter_section": "Numbers §4.5",
            "structural_refs": ["srcdecl:foundation:num:complex_numbers_definition"],
            "text": "The imaginary unit i = (0, 1) in C satisfies i^2 = -1. Every z in C is uniquely written z = a + bi with a, b in R.",
        },
        {
            "node_id": "srcdecl:foundation:num:complex_conjugate_modulus",
            "label": "Complex Conjugate and Absolute Value (Modulus)",
            "decl_type": "DEFINITION",
            "layer": "number_systems",
            "chapter_section": "Numbers §4.5",
            "structural_refs": ["srcdecl:foundation:num:imaginary_unit"],
            "text": "For z = a + bi in C, complex conjugate is z_bar = a - bi, and modulus is |z| = sqrt(a^2 + b^2) = sqrt(z · z_bar).",
        },
        {
            "node_id": "srcdecl:foundation:num:polar_form_complex",
            "label": "Polar Representation of Complex Numbers",
            "decl_type": "THEOREM",
            "layer": "number_systems",
            "chapter_section": "Numbers §4.5",
            "structural_refs": ["srcdecl:foundation:num:complex_conjugate_modulus"],
            "text": "Every non-zero complex number z in C can be represented in polar coordinates as z = r(cos θ + i sin θ) where r = |z| > 0 and θ in [0, 2π).",
        },
        {
            "node_id": "srcdecl:foundation:num:algebraic_closure_c_primitive",
            "label": "Algebraic Closure of Complex Numbers (Primitive Formulation)",
            "decl_type": "THEOREM",
            "layer": "number_systems",
            "chapter_section": "Numbers §4.5",
            "structural_refs": ["srcdecl:foundation:num:complex_numbers_definition"],
            "text": "The complex field C is algebraically closed: every non-constant polynomial with complex coefficients has at least one root in C.",
        },

        # =========================================================================
        # LAYER 5: ELEMENTARY ARITHMETIC & ALGEBRA (22 Declarations)
        # =========================================================================
        {
            "node_id": "srcdecl:foundation:alg:addition_operation",
            "label": "Binary Operation of Addition",
            "decl_type": "DEFINITION",
            "layer": "arithmetic_algebra",
            "chapter_section": "Algebra §5.1",
            "structural_refs": ["srcdecl:foundation:rel:function_definition"],
            "text": "Addition +: S × S -> S is a binary operation combining two elements a, b into a single sum a + b.",
        },
        {
            "node_id": "srcdecl:foundation:alg:multiplication_operation",
            "label": "Binary Operation of Multiplication",
            "decl_type": "DEFINITION",
            "layer": "arithmetic_algebra",
            "chapter_section": "Algebra §5.1",
            "structural_refs": ["srcdecl:foundation:rel:function_definition"],
            "text": "Multiplication ·: S × S -> S is a binary operation combining two elements a, b into product a · b.",
        },
        {
            "node_id": "srcdecl:foundation:alg:commutative_law",
            "label": "Commutative Property of Addition and Multiplication",
            "decl_type": "AXIOM",
            "layer": "arithmetic_algebra",
            "chapter_section": "Algebra §5.1",
            "structural_refs": ["srcdecl:foundation:alg:addition_operation", "srcdecl:foundation:alg:multiplication_operation"],
            "text": "For all a, b: a + b = b + a (commutative addition), and a · b = b · a (commutative multiplication).",
        },
        {
            "node_id": "srcdecl:foundation:alg:associative_law",
            "label": "Associative Property of Addition and Multiplication",
            "decl_type": "AXIOM",
            "layer": "arithmetic_algebra",
            "chapter_section": "Algebra §5.1",
            "structural_refs": ["srcdecl:foundation:alg:addition_operation", "srcdecl:foundation:alg:multiplication_operation"],
            "text": "For all a, b, c: (a + b) + c = a + (b + c), and (a · b) · c = a · (b · c).",
        },
        {
            "node_id": "srcdecl:foundation:alg:distributive_law",
            "label": "Distributive Property of Multiplication over Addition",
            "decl_type": "AXIOM",
            "layer": "arithmetic_algebra",
            "chapter_section": "Algebra §5.1",
            "structural_refs": ["srcdecl:foundation:alg:addition_operation", "srcdecl:foundation:alg:multiplication_operation"],
            "text": "For all a, b, c: a · (b + c) = (a · b) + (a · c), and (a + b) · c = (a · c) + (b · c).",
        },
        {
            "node_id": "srcdecl:foundation:alg:identity_and_inverses",
            "label": "Additive and Multiplicative Identities and Inverses",
            "decl_type": "AXIOM",
            "layer": "arithmetic_algebra",
            "chapter_section": "Algebra §5.1",
            "structural_refs": ["srcdecl:foundation:alg:addition_operation", "srcdecl:foundation:alg:multiplication_operation"],
            "text": "Additive identity 0 satisfies a + 0 = a; additive inverse -a satisfies a + (-a) = 0. Multiplicative identity 1 satisfies a · 1 = a; inverse a^{-1} satisfies a · a^{-1} = 1 for a ≠ 0.",
        },
        {
            "node_id": "srcdecl:foundation:alg:group_axioms",
            "label": "Definition of Group Axioms",
            "decl_type": "DEFINITION",
            "layer": "arithmetic_algebra",
            "chapter_section": "Algebra §5.2",
            "structural_refs": ["srcdecl:foundation:alg:associative_law", "srcdecl:foundation:alg:identity_and_inverses"],
            "text": "A group (G, *) is a set with binary operation satisfying: closure, associativity, existence of identity element e, and existence of inverses for all elements.",
        },
        {
            "node_id": "srcdecl:foundation:alg:abelian_group",
            "label": "Definition of Abelian (Commutative) Group",
            "decl_type": "DEFINITION",
            "layer": "arithmetic_algebra",
            "chapter_section": "Algebra §5.2",
            "structural_refs": ["srcdecl:foundation:alg:group_axioms", "srcdecl:foundation:alg:commutative_law"],
            "text": "A group (G, *) is Abelian iff the operation is commutative: ∀a, b in G (a * b = b * a).",
        },
        {
            "node_id": "srcdecl:foundation:alg:ring_axioms",
            "label": "Definition of Ring Axioms",
            "decl_type": "DEFINITION",
            "layer": "arithmetic_algebra",
            "chapter_section": "Algebra §5.3",
            "structural_refs": ["srcdecl:foundation:alg:abelian_group", "srcdecl:foundation:alg:distributive_law"],
            "text": "A ring (R, +, ·) is an Abelian group under + and a monoid under · satisfying distributive laws of multiplication over addition.",
        },
        {
            "node_id": "srcdecl:foundation:alg:field_axioms",
            "label": "Definition of Field Axioms",
            "decl_type": "DEFINITION",
            "layer": "arithmetic_algebra",
            "chapter_section": "Algebra §5.3",
            "structural_refs": ["srcdecl:foundation:alg:ring_axioms", "srcdecl:foundation:alg:identity_and_inverses"],
            "text": "A field (F, +, ·) is a commutative ring with 1 ≠ 0 where every non-zero element has a multiplicative inverse.",
        },
        {
            "node_id": "srcdecl:foundation:alg:subgroup_definition",
            "label": "Definition of Subgroup and Subgroup Criterion",
            "decl_type": "DEFINITION",
            "layer": "arithmetic_algebra",
            "chapter_section": "Algebra §5.2",
            "structural_refs": ["srcdecl:foundation:alg:group_axioms"],
            "text": "A non-empty subset H ⊆ G is a subgroup (H <= G) iff for all a, b in H, a * b^{-1} in H.",
        },
        {
            "node_id": "srcdecl:foundation:alg:group_homomorphism",
            "label": "Definition of Group Homomorphism and Kernel",
            "decl_type": "DEFINITION",
            "layer": "arithmetic_algebra",
            "chapter_section": "Algebra §5.2",
            "structural_refs": ["srcdecl:foundation:alg:group_axioms", "srcdecl:foundation:rel:function_definition"],
            "text": "A map φ: G -> H is a homomorphism iff φ(a * b) = φ(a) * φ(b). Its kernel is ker(φ) = {g in G | φ(g) = e_H}.",
        },
        {
            "node_id": "srcdecl:foundation:alg:polynomial_definition",
            "label": "Definition of Polynomial over a Field F",
            "decl_type": "DEFINITION",
            "layer": "arithmetic_algebra",
            "chapter_section": "Algebra §5.4",
            "structural_refs": ["srcdecl:foundation:alg:field_axioms"],
            "text": "A polynomial P(x) in F[x] is a formal sum P(x) = a_n x^n + a_{n-1} x^{n-1} + ... + a_1 x + a_0 with coefficients a_i in F.",
        },
        {
            "node_id": "srcdecl:foundation:alg:polynomial_degree",
            "label": "Degree and Leading Coefficient of Polynomial",
            "decl_type": "DEFINITION",
            "layer": "arithmetic_algebra",
            "chapter_section": "Algebra §5.4",
            "structural_refs": ["srcdecl:foundation:alg:polynomial_definition"],
            "text": "For non-zero P(x) = sum_{i=0}^n a_i x^i with a_n ≠ 0, deg(P) = n is the degree, and a_n is the leading coefficient.",
        },
        {
            "node_id": "srcdecl:foundation:alg:polynomial_division_algorithm",
            "label": "Division Algorithm for Polynomials",
            "decl_type": "THEOREM",
            "layer": "arithmetic_algebra",
            "chapter_section": "Algebra §5.4",
            "structural_refs": ["srcdecl:foundation:alg:polynomial_degree"],
            "text": "For P(x), D(x) in F[x] with D(x) ≠ 0, there exist unique Q(x), R(x) in F[x] such that P(x) = D(x)·Q(x) + R(x) with deg(R) < deg(D).",
        },
        {
            "node_id": "srcdecl:foundation:alg:remainder_factor_theorem",
            "label": "Polynomial Remainder Theorem and Factor Theorem",
            "decl_type": "THEOREM",
            "layer": "arithmetic_algebra",
            "chapter_section": "Algebra §5.4",
            "structural_refs": ["srcdecl:foundation:alg:polynomial_division_algorithm"],
            "text": "The remainder of P(x) divided by (x - c) is P(c). Consequently, (x - c) divides P(x) if and only if P(c) = 0 (c is a root).",
        },
        {
            "node_id": "srcdecl:foundation:alg:binomial_coefficients",
            "label": "Definition of Binomial Coefficient n choose k",
            "decl_type": "DEFINITION",
            "layer": "arithmetic_algebra",
            "chapter_section": "Algebra §5.5",
            "structural_refs": ["srcdecl:foundation:num:peano_axioms_naturals"],
            "text": "For integers n >= k >= 0, the binomial coefficient is C(n, k) = n! / (k! · (n-k)!).",
        },
        {
            "node_id": "srcdecl:foundation:alg:pascals_identity",
            "label": "Pascal's Recurrence Identity",
            "decl_type": "THEOREM",
            "layer": "arithmetic_algebra",
            "chapter_section": "Algebra §5.5",
            "structural_refs": ["srcdecl:foundation:alg:binomial_coefficients"],
            "text": "For n >= k >= 1: C(n, k) = C(n-1, k-1) + C(n-1, k).",
        },
        {
            "node_id": "srcdecl:foundation:alg:binomial_theorem",
            "label": "The Binomial Theorem",
            "decl_type": "THEOREM",
            "layer": "arithmetic_algebra",
            "chapter_section": "Algebra §5.5",
            "structural_refs": ["srcdecl:foundation:alg:pascals_identity", "srcdecl:foundation:alg:distributive_law"],
            "text": "For elements a, b in commutative ring and integer n >= 0: (a + b)^n = sum_{k=0}^n C(n, k) a^k b^{n-k}.",
        },
        {
            "node_id": "srcdecl:foundation:alg:quadratic_formula",
            "label": "Quadratic Formula for Second-Degree Equations",
            "decl_type": "THEOREM",
            "layer": "arithmetic_algebra",
            "chapter_section": "Algebra §5.4",
            "structural_refs": ["srcdecl:foundation:alg:polynomial_definition", "srcdecl:foundation:num:imaginary_unit"],
            "text": "For ax^2 + bx + c = 0 with a ≠ 0, the solutions in C are given by x = (-b ± sqrt(b^2 - 4ac)) / (2a).",
        },
        {
            "node_id": "srcdecl:foundation:alg:vector_space_axioms_primitive",
            "label": "Vector Space Axioms over Field F (Primitive Formulation)",
            "decl_type": "DEFINITION",
            "layer": "arithmetic_algebra",
            "chapter_section": "Algebra §5.6",
            "structural_refs": ["srcdecl:foundation:alg:abelian_group", "srcdecl:foundation:alg:field_axioms"],
            "text": "A vector space V over F is an Abelian group (V, +) equipped with scalar multiplication F × V -> V satisfying distributivity and associativity of scalar scaling.",
        },
        {
            "node_id": "srcdecl:foundation:alg:linear_combination_span",
            "label": "Linear Combination and Span",
            "decl_type": "DEFINITION",
            "layer": "arithmetic_algebra",
            "chapter_section": "Algebra §5.6",
            "structural_refs": ["srcdecl:foundation:alg:vector_space_axioms_primitive"],
            "text": "A linear combination of vectors v_1, ..., v_k is sum_{i=1}^k c_i v_i with c_i in F. Span(S) is the set of all finite linear combinations of vectors in S.",
        },

        # =========================================================================
        # LAYER 6: ORDER, METRICS & SEQUENCES (22 Declarations)
        # =========================================================================
        {
            "node_id": "srcdecl:foundation:seq:bounded_set_reals",
            "label": "Definition of Bounded Set in Real Line",
            "decl_type": "DEFINITION",
            "layer": "order_sequences",
            "chapter_section": "Sequences §6.1",
            "structural_refs": ["srcdecl:foundation:num:real_numbers_axioms"],
            "text": "A subset S ⊆ R is bounded above if ∃M in R ∀x in S (x <= M); bounded below if ∃m in R ∀x in S (m <= x); bounded if both.",
        },
        {
            "node_id": "srcdecl:foundation:seq:supremum_infimum",
            "label": "Definition of Supremum and Infimum",
            "decl_type": "DEFINITION",
            "layer": "order_sequences",
            "chapter_section": "Sequences §6.1",
            "structural_refs": ["srcdecl:foundation:seq:bounded_set_reals"],
            "text": "sup(S) is the least upper bound of S; inf(S) is the greatest lower bound of S.",
        },
        {
            "node_id": "srcdecl:foundation:seq:absolute_value",
            "label": "Definition of Absolute Value Function on R",
            "decl_type": "DEFINITION",
            "layer": "order_sequences",
            "chapter_section": "Sequences §6.2",
            "structural_refs": ["srcdecl:foundation:num:real_numbers_axioms"],
            "text": "For x in R, |x| = x if x >= 0, and |x| = -x if x < 0. Satisfies |x| >= 0 and |x| = 0 <=> x = 0.",
        },
        {
            "node_id": "srcdecl:foundation:seq:triangle_inequality_reals",
            "label": "Triangle Inequality for Real Numbers",
            "decl_type": "THEOREM",
            "layer": "order_sequences",
            "chapter_section": "Sequences §6.2",
            "structural_refs": ["srcdecl:foundation:seq:absolute_value"],
            "text": "For all real numbers a, b in R: |a + b| <= |a| + |b|.",
        },
        {
            "node_id": "srcdecl:foundation:seq:reverse_triangle_inequality",
            "label": "Reverse Triangle Inequality",
            "decl_type": "THEOREM",
            "layer": "order_sequences",
            "chapter_section": "Sequences §6.2",
            "structural_refs": ["srcdecl:foundation:seq:triangle_inequality_reals"],
            "text": "For all a, b in R: ||a| - |b|| <= |a - b|.",
        },
        {
            "node_id": "srcdecl:foundation:seq:real_sequence_definition",
            "label": "Definition of Real Sequence",
            "decl_type": "DEFINITION",
            "layer": "order_sequences",
            "chapter_section": "Sequences §6.3",
            "structural_refs": ["srcdecl:foundation:rel:function_definition", "srcdecl:foundation:num:peano_axioms_naturals"],
            "text": "A real sequence is a function a: N -> R, denoted (a_n)_{n=0}^\\infty or (a_n).",
        },
        {
            "node_id": "srcdecl:foundation:seq:sequence_limit_epsilon_N",
            "label": "Definition of Sequence Convergence (Epsilon-N Limit)",
            "decl_type": "DEFINITION",
            "layer": "order_sequences",
            "chapter_section": "Sequences §6.3",
            "structural_refs": ["srcdecl:foundation:seq:real_sequence_definition", "srcdecl:foundation:seq:absolute_value"],
            "text": "A sequence (a_n) converges to limit L (lim a_n = L) iff ∀ε > 0 ∃N in N ∀n >= N (|a_n - L| < ε).",
        },
        {
            "node_id": "srcdecl:foundation:seq:uniqueness_sequence_limit",
            "label": "Uniqueness of Limits of Sequences",
            "decl_type": "THEOREM",
            "layer": "order_sequences",
            "chapter_section": "Sequences §6.3",
            "structural_refs": ["srcdecl:foundation:seq:sequence_limit_epsilon_N", "srcdecl:foundation:seq:triangle_inequality_reals"],
            "text": "If a sequence (a_n) converges, its limit L is unique.",
        },
        {
            "node_id": "srcdecl:foundation:seq:convergent_implies_bounded",
            "label": "Boundedness of Convergent Sequences",
            "decl_type": "THEOREM",
            "layer": "order_sequences",
            "chapter_section": "Sequences §6.3",
            "structural_refs": ["srcdecl:foundation:seq:sequence_limit_epsilon_N", "srcdecl:foundation:seq:bounded_set_reals"],
            "text": "Every convergent sequence of real numbers is bounded.",
        },
        {
            "node_id": "srcdecl:foundation:seq:algebraic_limit_theorem",
            "label": "Algebraic Limit Theorem for Sequences",
            "decl_type": "THEOREM",
            "layer": "order_sequences",
            "chapter_section": "Sequences §6.4",
            "structural_refs": ["srcdecl:foundation:seq:sequence_limit_epsilon_N"],
            "text": "If lim a_n = A and lim b_n = B, then lim (a_n + b_n) = A + B, lim (a_n · b_n) = A · B, and lim (a_n / b_n) = A / B (if B ≠ 0).",
        },
        {
            "node_id": "srcdecl:foundation:seq:squeeze_theorem",
            "label": "Squeeze (Sandwich) Theorem for Sequences",
            "decl_type": "THEOREM",
            "layer": "order_sequences",
            "chapter_section": "Sequences §6.4",
            "structural_refs": ["srcdecl:foundation:seq:sequence_limit_epsilon_N"],
            "text": "If a_n <= b_n <= c_n for all n >= N_0, and lim a_n = lim c_n = L, then lim b_n = L.",
        },
        {
            "node_id": "srcdecl:foundation:seq:monotone_convergence_theorem",
            "label": "Monotone Convergence Theorem for Sequences",
            "decl_type": "THEOREM",
            "layer": "order_sequences",
            "chapter_section": "Sequences §6.5",
            "structural_refs": ["srcdecl:foundation:seq:sequence_limit_epsilon_N", "srcdecl:foundation:num:completeness_supremum"],
            "text": "Every bounded monotone (non-decreasing or non-increasing) sequence of real numbers converges in R.",
        },
        {
            "node_id": "srcdecl:foundation:seq:subsequence_definition",
            "label": "Definition of Subsequence",
            "decl_type": "DEFINITION",
            "layer": "order_sequences",
            "chapter_section": "Sequences §6.5",
            "structural_refs": ["srcdecl:foundation:seq:real_sequence_definition"],
            "text": "Given (a_n) and strictly increasing index sequence n_1 < n_2 < n_3 < ..., the sequence (a_{n_k})_{k=1}^\\infty is a subsequence.",
        },
        {
            "node_id": "srcdecl:foundation:seq:bolzano_weierstrass_primitive",
            "label": "Bolzano-Weierstrass Theorem (Elementary)",
            "decl_type": "THEOREM",
            "layer": "order_sequences",
            "chapter_section": "Sequences §6.5",
            "structural_refs": ["srcdecl:foundation:seq:subsequence_definition", "srcdecl:foundation:seq:monotone_convergence_theorem"],
            "text": "Every bounded sequence of real numbers has a convergent subsequence.",
        },
        {
            "node_id": "srcdecl:foundation:seq:cauchy_sequence_definition",
            "label": "Definition of Cauchy Sequence",
            "decl_type": "DEFINITION",
            "layer": "order_sequences",
            "chapter_section": "Sequences §6.6",
            "structural_refs": ["srcdecl:foundation:seq:real_sequence_definition", "srcdecl:foundation:seq:absolute_value"],
            "text": "A sequence (a_n) is a Cauchy sequence iff ∀ε > 0 ∃N in N ∀m, n >= N (|a_n - a_m| < ε).",
        },
        {
            "node_id": "srcdecl:foundation:seq:cauchy_criterion_convergence",
            "label": "Cauchy Convergence Criterion in R",
            "decl_type": "THEOREM",
            "layer": "order_sequences",
            "chapter_section": "Sequences §6.6",
            "structural_refs": ["srcdecl:foundation:seq:cauchy_sequence_definition", "srcdecl:foundation:num:completeness_supremum"],
            "text": "A sequence of real numbers converges in R if and only if it is a Cauchy sequence (Completeness of R).",
        },
        {
            "node_id": "srcdecl:foundation:seq:infinite_series_definition",
            "label": "Definition of Infinite Series and Partial Sums",
            "decl_type": "DEFINITION",
            "layer": "order_sequences",
            "chapter_section": "Sequences §6.7",
            "structural_refs": ["srcdecl:foundation:seq:real_sequence_definition"],
            "text": "For sequence (a_n), infinite series sum_{n=0}^\\infty a_n is the sequence of partial sums s_k = sum_{n=0}^k a_n. The series converges to S iff lim s_k = S.",
        },
        {
            "node_id": "srcdecl:foundation:seq:geometric_series_sum",
            "label": "Sum Formula for Geometric Series",
            "decl_type": "THEOREM",
            "layer": "order_sequences",
            "chapter_section": "Sequences §6.7",
            "structural_refs": ["srcdecl:foundation:seq:infinite_series_definition"],
            "text": "For real |r| < 1: sum_{n=0}^\\infty a r^n = a / (1 - r). If |r| >= 1 and a ≠ 0, the series diverges.",
        },
        {
            "node_id": "srcdecl:foundation:seq:divergence_test",
            "label": "Divergence Test (n-th Term Test) for Series",
            "decl_type": "THEOREM",
            "layer": "order_sequences",
            "chapter_section": "Sequences §6.7",
            "structural_refs": ["srcdecl:foundation:seq:infinite_series_definition"],
            "text": "If sum a_n converges, then lim_{n -> \\infty} a_n = 0. Equivalently, if lim a_n ≠ 0, then sum a_n diverges.",
        },
        {
            "node_id": "srcdecl:foundation:seq:comparison_test_series",
            "label": "Direct Comparison Test for Non-Negative Series",
            "decl_type": "THEOREM",
            "layer": "order_sequences",
            "chapter_section": "Sequences §6.7",
            "structural_refs": ["srcdecl:foundation:seq:infinite_series_definition", "srcdecl:foundation:seq:monotone_convergence_theorem"],
            "text": "If 0 <= a_n <= b_n for all n, then convergence of sum b_n implies convergence of sum a_n, and divergence of sum a_n implies divergence of sum b_n.",
        },
        {
            "node_id": "srcdecl:foundation:seq:metric_space_axioms_primitive",
            "label": "Definition of Metric Space (Primitive Formulation)",
            "decl_type": "DEFINITION",
            "layer": "order_sequences",
            "chapter_section": "Sequences §6.8",
            "structural_refs": ["srcdecl:foundation:seq:triangle_inequality_reals"],
            "text": "A metric space (M, d) is a set M with distance function d: M × M -> R satisfying non-negativity, identity of indiscernibles, symmetry, and triangle inequality.",
        },
        {
            "node_id": "srcdecl:foundation:seq:open_ball_metric",
            "label": "Definition of Open Ball and Neighborhood in Metric Space",
            "decl_type": "DEFINITION",
            "layer": "order_sequences",
            "chapter_section": "Sequences §6.8",
            "structural_refs": ["srcdecl:foundation:seq:metric_space_axioms_primitive"],
            "text": "The open ball of radius r > 0 centered at x_0 in metric space (M, d) is B(x_0, r) = {x in M | d(x, x_0) < r}.",
        },

        # =========================================================================
        # LAYER 7: EUCLIDEAN GEOMETRY & TRIGONOMETRY (22 Declarations)
        # =========================================================================
        {
            "node_id": "srcdecl:foundation:geom:euclidean_plane_R2",
            "label": "Definition of Euclidean Plane R^2",
            "decl_type": "DEFINITION",
            "layer": "geometry_trig",
            "chapter_section": "Geometry §7.1",
            "structural_refs": ["srcdecl:foundation:set:cartesian_product", "srcdecl:foundation:num:real_numbers_axioms"],
            "text": "The Euclidean plane R^2 is the Cartesian product R × R with points represented by Cartesian coordinates (x, y).",
        },
        {
            "node_id": "srcdecl:foundation:geom:euclidean_space_Rn",
            "label": "Definition of Euclidean Space R^n",
            "decl_type": "DEFINITION",
            "layer": "geometry_trig",
            "chapter_section": "Geometry §7.1",
            "structural_refs": ["srcdecl:foundation:geom:euclidean_plane_R2"],
            "text": "Euclidean space R^n is the set of ordered n-tuples of real numbers (x_1, ..., x_n) equipped with standard vector addition and scalar multiplication.",
        },
        {
            "node_id": "srcdecl:foundation:geom:distance_formula_R2",
            "label": "Euclidean Distance Formula in R^2",
            "decl_type": "DEFINITION",
            "layer": "geometry_trig",
            "chapter_section": "Geometry §7.2",
            "structural_refs": ["srcdecl:foundation:geom:euclidean_plane_R2"],
            "text": "The distance between points P=(x_1, y_1) and Q=(x_2, y_2) in R^2 is d(P, Q) = sqrt((x_2 - x_1)^2 + (y_2 - y_1)^2).",
        },
        {
            "node_id": "srcdecl:foundation:geom:distance_formula_Rn",
            "label": "Euclidean Distance Formula in R^n",
            "decl_type": "DEFINITION",
            "layer": "geometry_trig",
            "chapter_section": "Geometry §7.2",
            "structural_refs": ["srcdecl:foundation:geom:euclidean_space_Rn"],
            "text": "The distance between vectors x, y in R^n is d(x, y) = sqrt(sum_{i=1}^n (x_i - y_i)^2).",
        },
        {
            "node_id": "srcdecl:foundation:geom:dot_product_Rn",
            "label": "Definition of Standard Dot Product (Inner Product) on R^n",
            "decl_type": "DEFINITION",
            "layer": "geometry_trig",
            "chapter_section": "Geometry §7.3",
            "structural_refs": ["srcdecl:foundation:geom:euclidean_space_Rn"],
            "text": "The dot product of vectors u, v in R^n is u · v = sum_{i=1}^n u_i v_i.",
        },
        {
            "node_id": "srcdecl:foundation:geom:euclidean_norm_length",
            "label": "Euclidean Norm (Length) of a Vector",
            "decl_type": "DEFINITION",
            "layer": "geometry_trig",
            "chapter_section": "Geometry §7.3",
            "structural_refs": ["srcdecl:foundation:geom:dot_product_Rn"],
            "text": "The Euclidean norm of v in R^n is ||v|| = sqrt(v · v) = sqrt(sum_{i=1}^n v_i^2).",
        },
        {
            "node_id": "srcdecl:foundation:geom:cauchy_schwarz_elementary",
            "label": "Cauchy-Schwarz Inequality in Euclidean Space",
            "decl_type": "THEOREM",
            "layer": "geometry_trig",
            "chapter_section": "Geometry §7.3",
            "structural_refs": ["srcdecl:foundation:geom:dot_product_Rn", "srcdecl:foundation:geom:euclidean_norm_length"],
            "text": "For all vectors u, v in R^n: |u · v| <= ||u|| · ||v||, with equality iff u and v are linearly dependent.",
        },
        {
            "node_id": "srcdecl:foundation:geom:triangle_inequality_Rn",
            "label": "Triangle Inequality in Euclidean Space R^n",
            "decl_type": "THEOREM",
            "layer": "geometry_trig",
            "chapter_section": "Geometry §7.3",
            "structural_refs": ["srcdecl:foundation:geom:cauchy_schwarz_elementary"],
            "text": "For all vectors u, v in R^n: ||u + v|| <= ||u|| + ||v||.",
        },
        {
            "node_id": "srcdecl:foundation:geom:orthogonality_vectors",
            "label": "Definition of Orthogonality (Perpendicularity)",
            "decl_type": "DEFINITION",
            "layer": "geometry_trig",
            "chapter_section": "Geometry §7.4",
            "structural_refs": ["srcdecl:foundation:geom:dot_product_Rn"],
            "text": "Two vectors u, v in R^n are orthogonal (u ⊥ v) iff u · v = 0.",
        },
        {
            "node_id": "srcdecl:foundation:geom:pythagorean_theorem",
            "label": "The Pythagorean Theorem in R^n",
            "decl_type": "THEOREM",
            "layer": "geometry_trig",
            "chapter_section": "Geometry §7.4",
            "structural_refs": ["srcdecl:foundation:geom:orthogonality_vectors", "srcdecl:foundation:geom:euclidean_norm_length"],
            "text": "Vectors u, v in R^n are orthogonal iff ||u + v||^2 = ||u||^2 + ||v||^2.",
        },
        {
            "node_id": "srcdecl:foundation:geom:unit_circle_equation",
            "label": "Equation of the Unit Circle in R^2",
            "decl_type": "DEFINITION",
            "layer": "geometry_trig",
            "chapter_section": "Geometry §7.5",
            "structural_refs": ["srcdecl:foundation:geom:euclidean_plane_R2", "srcdecl:foundation:geom:distance_formula_R2"],
            "text": "The unit circle S^1 in R^2 is the set of all points at distance 1 from origin: S^1 = {(x, y) in R^2 | x^2 + y^2 = 1}.",
        },
        {
            "node_id": "srcdecl:foundation:geom:sine_cosine_unit_circle",
            "label": "Geometric Definition of Sine and Cosine via Unit Circle",
            "decl_type": "DEFINITION",
            "layer": "geometry_trig",
            "chapter_section": "Trigonometry §7.6",
            "structural_refs": ["srcdecl:foundation:geom:unit_circle_equation"],
            "text": "For angle θ in standard position, point P on unit circle has coordinates (cos θ, sin θ). Thus cos^2 θ + sin^2 θ = 1.",
        },
        {
            "node_id": "srcdecl:foundation:geom:tangent_trig_definition",
            "label": "Definition of Tangent and Reciprocal Trigonometric Functions",
            "decl_type": "DEFINITION",
            "layer": "geometry_trig",
            "chapter_section": "Trigonometry §7.6",
            "structural_refs": ["srcdecl:foundation:geom:sine_cosine_unit_circle"],
            "text": "tan θ = sin θ / cos θ (for cos θ ≠ 0), sec θ = 1 / cos θ, csc θ = 1 / sin θ, cot θ = cos θ / sin θ.",
        },
        {
            "node_id": "srcdecl:foundation:geom:pythagorean_trig_identities",
            "label": "Fundamental Pythagorean Trigonometric Identities",
            "decl_type": "THEOREM",
            "layer": "geometry_trig",
            "chapter_section": "Trigonometry §7.6",
            "structural_refs": ["srcdecl:foundation:geom:sine_cosine_unit_circle", "srcdecl:foundation:geom:tangent_trig_definition"],
            "text": "sin^2 θ + cos^2 θ = 1, 1 + tan^2 θ = sec^2 θ, and 1 + cot^2 θ = csc^2 θ.",
        },
        {
            "node_id": "srcdecl:foundation:geom:angle_sum_formulas",
            "label": "Angle Sum and Difference Formulas for Sine and Cosine",
            "decl_type": "THEOREM",
            "layer": "geometry_trig",
            "chapter_section": "Trigonometry §7.7",
            "structural_refs": ["srcdecl:foundation:geom:sine_cosine_unit_circle"],
            "text": "sin(α ± β) = sin α cos β ± cos α sin β, and cos(α ± β) = cos α cos β ∓ sin α sin β.",
        },
        {
            "node_id": "srcdecl:foundation:geom:double_angle_formulas",
            "label": "Double-Angle and Half-Angle Formulas",
            "decl_type": "THEOREM",
            "layer": "geometry_trig",
            "chapter_section": "Trigonometry §7.7",
            "structural_refs": ["srcdecl:foundation:geom:angle_sum_formulas"],
            "text": "sin(2θ) = 2 sin θ cos θ, and cos(2θ) = cos^2 θ - sin^2 θ = 2 cos^2 θ - 1 = 1 - 2 sin^2 θ.",
        },
        {
            "node_id": "srcdecl:foundation:geom:law_of_cosines",
            "label": "The Law of Cosines for Triangles",
            "decl_type": "THEOREM",
            "layer": "geometry_trig",
            "chapter_section": "Geometry §7.8",
            "structural_refs": ["srcdecl:foundation:geom:dot_product_Rn", "srcdecl:foundation:geom:pythagorean_theorem"],
            "text": "In any triangle with sides a, b, c and opposite angle γ: c^2 = a^2 + b^2 - 2ab cos γ.",
        },
        {
            "node_id": "srcdecl:foundation:geom:law_of_sines",
            "label": "The Law of Sines for Triangles",
            "decl_type": "THEOREM",
            "layer": "geometry_trig",
            "chapter_section": "Geometry §7.8",
            "structural_refs": ["srcdecl:foundation:geom:sine_cosine_unit_circle"],
            "text": "In any triangle with sides a, b, c and opposite angles α, β, γ: a / sin α = b / sin β = c / sin γ = 2R.",
        },
        {
            "node_id": "srcdecl:foundation:geom:polar_coordinates_R2",
            "label": "Polar Coordinates in R^2",
            "decl_type": "DEFINITION",
            "layer": "geometry_trig",
            "chapter_section": "Geometry §7.9",
            "structural_refs": ["srcdecl:foundation:geom:sine_cosine_unit_circle"],
            "text": "Point (x, y) in R^2 is represented in polar coordinates (r, θ) where x = r cos θ, y = r sin θ, r = sqrt(x^2 + y^2), θ = atan2(y, x).",
        },
        {
            "node_id": "srcdecl:foundation:geom:rotation_matrix_2d",
            "label": "2D Planar Rotation Transformation Matrix",
            "decl_type": "DEFINITION",
            "layer": "geometry_trig",
            "chapter_section": "Geometry §7.9",
            "structural_refs": ["srcdecl:foundation:geom:angle_sum_formulas"],
            "text": "Counterclockwise rotation by angle θ in R^2 is linear map given by matrix R_θ = [[cos θ, -sin θ], [sin θ, cos θ]].",
        },
        {
            "node_id": "srcdecl:foundation:geom:angle_between_vectors",
            "label": "Angle Between Vectors in Euclidean Space",
            "decl_type": "DEFINITION",
            "layer": "geometry_trig",
            "chapter_section": "Geometry §7.3",
            "structural_refs": ["srcdecl:foundation:geom:dot_product_Rn", "srcdecl:foundation:geom:cauchy_schwarz_elementary"],
            "text": "For non-zero u, v in R^n, angle θ in [0, π] satisfies cos θ = (u · v) / (||u|| · ||v||).",
        },
        {
            "node_id": "srcdecl:foundation:geom:cross_product_R3",
            "label": "Definition of Vector Cross Product in R^3",
            "decl_type": "DEFINITION",
            "layer": "geometry_trig",
            "chapter_section": "Geometry §7.10",
            "structural_refs": ["srcdecl:foundation:geom:euclidean_space_Rn", "srcdecl:foundation:geom:orthogonality_vectors"],
            "text": "For u, v in R^3, cross product u × v = (u_2 v_3 - u_3 v_2, u_3 v_1 - u_1 v_3, u_1 v_2 - u_2 v_1). Satisfies (u × v) ⊥ u and (u × v) ⊥ v.",
        },

        # =========================================================================
        # LAYER 8: ELEMENTARY CALCULUS (25 Declarations)
        # =========================================================================
        {
            "node_id": "srcdecl:foundation:calc:function_limit_epsilon_delta",
            "label": "Epsilon-Delta Definition of Limit of a Function",
            "decl_type": "DEFINITION",
            "layer": "elementary_calculus",
            "chapter_section": "Calculus §8.1",
            "structural_refs": ["srcdecl:foundation:rel:function_definition", "srcdecl:foundation:seq:absolute_value"],
            "text": "lim_{x -> c} f(x) = L iff ∀ε > 0 ∃δ > 0 ∀x in domain (0 < |x - c| < δ => |f(x) - L| < ε).",
        },
        {
            "node_id": "srcdecl:foundation:calc:one_sided_limits",
            "label": "Definition of Left-Hand and Right-Hand Limits",
            "decl_type": "DEFINITION",
            "layer": "elementary_calculus",
            "chapter_section": "Calculus §8.1",
            "structural_refs": ["srcdecl:foundation:calc:function_limit_epsilon_delta"],
            "text": "lim_{x -> c^+} f(x) = L requires c < x < c + δ; lim_{x -> c^-} f(x) = L requires c - δ < x < c. Two-sided limit exists iff both one-sided limits are equal.",
        },
        {
            "node_id": "srcdecl:foundation:calc:continuity_at_point",
            "label": "Definition of Continuity of a Function at a Point",
            "decl_type": "DEFINITION",
            "layer": "elementary_calculus",
            "chapter_section": "Calculus §8.2",
            "structural_refs": ["srcdecl:foundation:calc:function_limit_epsilon_delta"],
            "text": "f is continuous at c iff c is in domain of f, lim_{x -> c} f(x) exists, and lim_{x -> c} f(x) = f(c).",
        },
        {
            "node_id": "srcdecl:foundation:calc:continuity_on_interval",
            "label": "Definition of Continuity on an Interval",
            "decl_type": "DEFINITION",
            "layer": "elementary_calculus",
            "chapter_section": "Calculus §8.2",
            "structural_refs": ["srcdecl:foundation:calc:continuity_at_point"],
            "text": "f is continuous on open interval (a, b) iff f is continuous at every c in (a, b); continuous on closed [a, b] if continuous on (a, b) with appropriate one-sided continuity at endpoints.",
        },
        {
            "node_id": "srcdecl:foundation:calc:intermediate_value_theorem",
            "label": "The Intermediate Value Theorem (IVT)",
            "decl_type": "THEOREM",
            "layer": "elementary_calculus",
            "chapter_section": "Calculus §8.2",
            "structural_refs": ["srcdecl:foundation:calc:continuity_at_point", "srcdecl:foundation:num:completeness_supremum"],
            "text": "If f: [a, b] -> R is continuous and u is strictly between f(a) and f(b), then there exists c in (a, b) such that f(c) = u.",
        },
        {
            "node_id": "srcdecl:foundation:calc:extreme_value_theorem",
            "label": "The Extreme Value Theorem (EVT)",
            "decl_type": "THEOREM",
            "layer": "elementary_calculus",
            "chapter_section": "Calculus §8.2",
            "structural_refs": ["srcdecl:foundation:calc:continuity_at_point", "srcdecl:foundation:seq:bolzano_weierstrass_primitive"],
            "text": "If f: [a, b] -> R is continuous on closed bounded interval [a, b], then f attains an absolute maximum and absolute minimum on [a, b].",
        },
        {
            "node_id": "srcdecl:foundation:calc:derivative_difference_quotient",
            "label": "Definition of Derivative via Difference Quotient Limit",
            "decl_type": "DEFINITION",
            "layer": "elementary_calculus",
            "chapter_section": "Calculus §8.3",
            "structural_refs": ["srcdecl:foundation:calc:function_limit_epsilon_delta"],
            "text": "The derivative of f at x is f'(x) = lim_{h -> 0} (f(x + h) - f(x)) / h, provided this limit exists.",
        },
        {
            "node_id": "srcdecl:foundation:calc:differentiability_implies_continuity",
            "label": "Differentiability Implies Continuity",
            "decl_type": "THEOREM",
            "layer": "elementary_calculus",
            "chapter_section": "Calculus §8.3",
            "structural_refs": ["srcdecl:foundation:calc:derivative_difference_quotient", "srcdecl:foundation:calc:continuity_at_point"],
            "text": "If f is differentiable at c, then f is continuous at c.",
        },
        {
            "node_id": "srcdecl:foundation:calc:derivative_power_rule",
            "label": "Power Rule for Derivatives",
            "decl_type": "THEOREM",
            "layer": "elementary_calculus",
            "chapter_section": "Calculus §8.4",
            "structural_refs": ["srcdecl:foundation:calc:derivative_difference_quotient", "srcdecl:foundation:alg:binomial_theorem"],
            "text": "For any real constant n, d/dx (x^n) = n x^{n-1}.",
        },
        {
            "node_id": "srcdecl:foundation:calc:derivative_linearity",
            "label": "Linearity (Sum and Constant Multiple Rule) of Differentiation",
            "decl_type": "THEOREM",
            "layer": "elementary_calculus",
            "chapter_section": "Calculus §8.4",
            "structural_refs": ["srcdecl:foundation:calc:derivative_difference_quotient"],
            "text": "d/dx (c f(x) + g(x)) = c f'(x) + g'(x).",
        },
        {
            "node_id": "srcdecl:foundation:calc:derivative_product_rule",
            "label": "Product Rule (Leibniz Rule) for Derivatives",
            "decl_type": "THEOREM",
            "layer": "elementary_calculus",
            "chapter_section": "Calculus §8.4",
            "structural_refs": ["srcdecl:foundation:calc:derivative_difference_quotient", "srcdecl:foundation:calc:differentiability_implies_continuity"],
            "text": "d/dx (f(x) g(x)) = f'(x) g(x) + f(x) g'(x).",
        },
        {
            "node_id": "srcdecl:foundation:calc:derivative_quotient_rule",
            "label": "Quotient Rule for Derivatives",
            "decl_type": "THEOREM",
            "layer": "elementary_calculus",
            "chapter_section": "Calculus §8.4",
            "structural_refs": ["srcdecl:foundation:calc:derivative_product_rule"],
            "text": "d/dx (f(x) / g(x)) = (f'(x) g(x) - f(x) g'(x)) / (g(x))^2 for g(x) ≠ 0.",
        },
        {
            "node_id": "srcdecl:foundation:calc:derivative_chain_rule",
            "label": "Chain Rule for Composite Functions",
            "decl_type": "THEOREM",
            "layer": "elementary_calculus",
            "chapter_section": "Calculus §8.4",
            "structural_refs": ["srcdecl:foundation:calc:derivative_difference_quotient", "srcdecl:foundation:rel:function_composition"],
            "text": "If g is differentiable at x and f is differentiable at g(x), then (f ∘ g)'(x) = f'(g(x)) · g'(x).",
        },
        {
            "node_id": "srcdecl:foundation:calc:derivative_trig_functions",
            "label": "Derivatives of Elementary Trigonometric Functions",
            "decl_type": "THEOREM",
            "layer": "elementary_calculus",
            "chapter_section": "Calculus §8.4",
            "structural_refs": ["srcdecl:foundation:calc:derivative_difference_quotient", "srcdecl:foundation:geom:angle_sum_formulas"],
            "text": "d/dx (sin x) = cos x, d/dx (cos x) = -sin x, and d/dx (tan x) = sec^2 x.",
        },
        {
            "node_id": "srcdecl:foundation:calc:derivative_exponential_log",
            "label": "Derivatives of Natural Exponential and Logarithm",
            "decl_type": "THEOREM",
            "layer": "elementary_calculus",
            "chapter_section": "Calculus §8.4",
            "structural_refs": ["srcdecl:foundation:calc:derivative_difference_quotient"],
            "text": "d/dx (e^x) = e^x, and d/dx (ln x) = 1 / x for x > 0.",
        },
        {
            "node_id": "srcdecl:foundation:calc:rolles_theorem",
            "label": "Rolle's Theorem",
            "decl_type": "THEOREM",
            "layer": "elementary_calculus",
            "chapter_section": "Calculus §8.5",
            "structural_refs": ["srcdecl:foundation:calc:extreme_value_theorem", "srcdecl:foundation:calc:derivative_difference_quotient"],
            "text": "If f: [a, b] -> R is continuous on [a, b], differentiable on (a, b), and f(a) = f(b), then there exists c in (a, b) such that f'(c) = 0.",
        },
        {
            "node_id": "srcdecl:foundation:calc:mean_value_theorem",
            "label": "The Mean Value Theorem (MVT)",
            "decl_type": "THEOREM",
            "layer": "elementary_calculus",
            "chapter_section": "Calculus §8.5",
            "structural_refs": ["srcdecl:foundation:calc:rolles_theorem"],
            "text": "If f: [a, b] -> R is continuous on [a, b] and differentiable on (a, b), then there exists c in (a, b) such that f'(c) = (f(b) - f(a)) / (b - a).",
        },
        {
            "node_id": "srcdecl:foundation:calc:first_derivative_test",
            "label": "First Derivative Test for Local Extrema",
            "decl_type": "THEOREM",
            "layer": "elementary_calculus",
            "chapter_section": "Calculus §8.5",
            "structural_refs": ["srcdecl:foundation:calc:mean_value_theorem"],
            "text": "If f'(c) = 0 or f'(c) does not exist: if f' changes from + to - at c, f has a local max; if from - to +, local min.",
        },
        {
            "node_id": "srcdecl:foundation:calc:second_derivative_test",
            "label": "Second Derivative Test for Concavity and Extrema",
            "decl_type": "THEOREM",
            "layer": "elementary_calculus",
            "chapter_section": "Calculus §8.5",
            "structural_refs": ["srcdecl:foundation:calc:first_derivative_test"],
            "text": "If f'(c) = 0 and f''(c) exists: if f''(c) > 0 then f has local min at c; if f''(c) < 0 then f has local max at c.",
        },
        {
            "node_id": "srcdecl:foundation:calc:riemann_partition_sum",
            "label": "Definition of Riemann Partition and Riemann Sum",
            "decl_type": "DEFINITION",
            "layer": "elementary_calculus",
            "chapter_section": "Calculus §8.6",
            "structural_refs": ["srcdecl:foundation:num:real_numbers_axioms"],
            "text": "A partition P of [a, b] is a = x_0 < x_1 < ... < x_n = b. A Riemann sum is R(f, P, t) = sum_{i=1}^n f(t_i) (x_i - x_{i-1}) with t_i in [x_{i-1}, x_i].",
        },
        {
            "node_id": "srcdecl:foundation:calc:riemann_definite_integral",
            "label": "Definition of Definite Riemann Integral",
            "decl_type": "DEFINITION",
            "layer": "elementary_calculus",
            "chapter_section": "Calculus §8.6",
            "structural_refs": ["srcdecl:foundation:calc:riemann_partition_sum"],
            "text": "The definite integral int_a^b f(x) dx is the limit of Riemann sums as mesh ||P|| -> 0: int_a^b f(x) dx = lim_{||P|| -> 0} sum_{i=1}^n f(t_i) Δx_i.",
        },
        {
            "node_id": "srcdecl:foundation:calc:ftc_part1",
            "label": "Fundamental Theorem of Calculus (Part 1: Accumulation Derivative)",
            "decl_type": "THEOREM",
            "layer": "elementary_calculus",
            "chapter_section": "Calculus §8.7",
            "structural_refs": ["srcdecl:foundation:calc:riemann_definite_integral", "srcdecl:foundation:calc:derivative_difference_quotient"],
            "text": "If f is continuous on [a, b] and F(x) = int_a^x f(t) dt, then F is continuous on [a, b], differentiable on (a, b), and F'(x) = f(x).",
        },
        {
            "node_id": "srcdecl:foundation:calc:ftc_part2",
            "label": "Fundamental Theorem of Calculus (Part 2: Evaluation)",
            "decl_type": "THEOREM",
            "layer": "elementary_calculus",
            "chapter_section": "Calculus §8.7",
            "structural_refs": ["srcdecl:foundation:calc:ftc_part1"],
            "text": "If f is continuous on [a, b] and F is any antiderivative of f (F' = f), then int_a^b f(x) dx = F(b) - F(a).",
        },
        {
            "node_id": "srcdecl:foundation:calc:integration_by_parts",
            "label": "Integration by Parts Formula",
            "decl_type": "THEOREM",
            "layer": "elementary_calculus",
            "chapter_section": "Calculus §8.8",
            "structural_refs": ["srcdecl:foundation:calc:ftc_part2", "srcdecl:foundation:calc:derivative_product_rule"],
            "text": "For differentiable functions u and v: int u(x) v'(x) dx = u(x) v(x) - int v(x) u'(x) dx.",
        },
        {
            "node_id": "srcdecl:foundation:calc:integration_by_substitution",
            "label": "Integration by Substitution (u-Substitution)",
            "decl_type": "THEOREM",
            "layer": "elementary_calculus",
            "chapter_section": "Calculus §8.8",
            "structural_refs": ["srcdecl:foundation:calc:ftc_part2", "srcdecl:foundation:calc:derivative_chain_rule"],
            "text": "int_a^b f(g(x)) g'(x) dx = int_{g(a)}^{g(b)} f(u) du.",
        },
        {
            "node_id": "srcdecl:foundation:calc:taylors_theorem_primitive",
            "label": "Taylor's Theorem with Lagrange Remainder (Primitive Formulation)",
            "decl_type": "THEOREM",
            "layer": "elementary_calculus",
            "chapter_section": "Calculus §8.9",
            "structural_refs": ["srcdecl:foundation:calc:mean_value_theorem", "srcdecl:foundation:calc:derivative_power_rule"],
            "text": "If f is (n+1)-times differentiable on interval around a, f(x) = sum_{k=0}^n (f^{(k)}(a)/k!) (x-a)^k + (f^{(n+1)}(c)/(n+1)!) (x-a)^{n+1} for some c between a and x.",
        },
    ]

    declarations: list[FoundationDeclaration] = []
    for item in raw_declarations:
        text = item["text"]
        title = item["label"]
        sha = compute_sha256(text)
        char_count = len(text)
        profile = detect_foundation_representation_profile(text, title)

        decl = FoundationDeclaration(
            node_id=item["node_id"],
            source_id=SOURCE_ID,
            label=title,
            decl_type=item["decl_type"],
            chapter_section=item["chapter_section"],
            statement_sha256=sha,
            char_count=char_count,
            layer=item["layer"],
            structural_refs=item.get("structural_refs", []),
            representation_profile=profile,
        )
        declarations.append(decl)

    return declarations


def main() -> int:
    parser = argparse.ArgumentParser(description="MAPEOGEO Foundation Backfill Ingestion Generator")
    parser.add_argument(
        "--out",
        type=Path,
        default=ROOT / "artifacts" / "foundation_backfill" / "foundation_declarations.json",
        help="Path to output declarations JSON",
    )
    args = parser.parse_args()

    decls = generate_foundation_declarations()
    args.out.parent.mkdir(parents=True, exist_ok=True)

    out_data = {
        "source_id": SOURCE_ID,
        "stage": STAGE,
        "count": len(decls),
        "declarations": [d.to_dict() for d in decls],
    }
    args.out.write_text(json.dumps(out_data, indent=2), encoding="utf-8")
    print(f"Generated {len(decls)} foundation declarations to {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
